"""Generated from a real Mac M5 Pro / macOS 26.5.2 / Chromium 150 capture.

Source: full-edge-profile-2026-08-07T04-06-07.238Z.json
Dynamic site/session values are intentionally not included.
"""

from __future__ import annotations

CAPTURE_SCHEMA = 'rexiaohe.full-edge-profile-evidence.v1'
CAPTURED_AT = '2026-08-07T04:06:07.235Z'
CAPTURE_USER_AGENT = ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) '
 'Chrome/150.0.0.0 Safari/537.36')
MAC_M5_PRO_NAVIGATOR_HARDWARE = {'hardwareConcurrency': 15,
 'deviceMemoryGb': 16,
 'renderer': 'ANGLE (Apple, ANGLE Metal Renderer: Apple M5 Pro, Unspecified Version)',
 'architecture': 'arm',
 'platformVersion': '26.5.2'}
MAC_M5_PRO_SCREEN = {'width': 1512,
 'height': 982,
 'avail_width': 1512,
 'avail_height': 949,
 'avail_left': 0,
 'avail_top': 33,
 'color_depth': 30,
 'pixel_depth': 30,
 'viewport_width': 1512,
 'viewport_height': 828,
 'outer_width': 1512,
 'outer_height': 949,
 'screen_x': 0,
 'screen_y': 33,
 'device_pixel_ratio': 2,
 'orientation_type': 'landscape-primary',
 'orientation_angle': 0,
 'visual_viewport_offset_left': 0,
 'visual_viewport_offset_top': 0,
 'visual_viewport_page_left': 0,
 'visual_viewport_page_top': 0,
 'visual_viewport_scale': 1}
MAC_CHROMIUM150_CANVAS = {'text_width_scale': 0.8962605859033144,
 'actual_bounding_box_left': -0.41999998688697815,
 'actual_bounding_box_right_scale': 0.9996247700757742,
 'font_bounding_box_ascent': 11,
 'font_bounding_box_descent': 3,
 'actual_bounding_box_ascent': 7.279999732971191,
 'actual_bounding_box_descent': 2.119999885559082,
 'hanging_baseline': 8.800000190734863,
 'alphabetic_baseline': 0,
 'ideographic_baseline': -1.399993896484375}
MAC_CHROMIUM150_WEBGL1_EXTENSIONS = ('ANGLE_instanced_arrays',
 'EXT_blend_minmax',
 'EXT_clip_control',
 'EXT_color_buffer_half_float',
 'EXT_depth_clamp',
 'EXT_disjoint_timer_query',
 'EXT_float_blend',
 'EXT_frag_depth',
 'EXT_polygon_offset_clamp',
 'EXT_shader_texture_lod',
 'EXT_texture_compression_bptc',
 'EXT_texture_compression_rgtc',
 'EXT_texture_filter_anisotropic',
 'EXT_texture_mirror_clamp_to_edge',
 'EXT_sRGB',
 'KHR_parallel_shader_compile',
 'OES_element_index_uint',
 'OES_fbo_render_mipmap',
 'OES_standard_derivatives',
 'OES_texture_float',
 'OES_texture_float_linear',
 'OES_texture_half_float',
 'OES_texture_half_float_linear',
 'OES_vertex_array_object',
 'WEBGL_blend_func_extended',
 'WEBGL_color_buffer_float',
 'WEBGL_compressed_texture_astc',
 'WEBGL_compressed_texture_etc',
 'WEBGL_compressed_texture_etc1',
 'WEBGL_compressed_texture_pvrtc',
 'WEBGL_compressed_texture_s3tc',
 'WEBGL_compressed_texture_s3tc_srgb',
 'WEBGL_debug_renderer_info',
 'WEBGL_debug_shaders',
 'WEBGL_depth_texture',
 'WEBGL_draw_buffers',
 'WEBGL_lose_context',
 'WEBGL_multi_draw',
 'WEBGL_polygon_mode')
MAC_CHROMIUM150_WEBGL2_EXTENSIONS = ('EXT_clip_control',
 'EXT_color_buffer_float',
 'EXT_color_buffer_half_float',
 'EXT_conservative_depth',
 'EXT_depth_clamp',
 'EXT_disjoint_timer_query_webgl2',
 'EXT_float_blend',
 'EXT_polygon_offset_clamp',
 'EXT_render_snorm',
 'EXT_texture_compression_bptc',
 'EXT_texture_compression_rgtc',
 'EXT_texture_filter_anisotropic',
 'EXT_texture_mirror_clamp_to_edge',
 'EXT_texture_norm16',
 'KHR_parallel_shader_compile',
 'NV_shader_noperspective_interpolation',
 'OES_draw_buffers_indexed',
 'OES_sample_variables',
 'OES_shader_multisample_interpolation',
 'OES_texture_float_linear',
 'WEBGL_blend_func_extended',
 'WEBGL_clip_cull_distance',
 'WEBGL_compressed_texture_astc',
 'WEBGL_compressed_texture_etc',
 'WEBGL_compressed_texture_etc1',
 'WEBGL_compressed_texture_pvrtc',
 'WEBGL_compressed_texture_s3tc',
 'WEBGL_compressed_texture_s3tc_srgb',
 'WEBGL_debug_renderer_info',
 'WEBGL_debug_shaders',
 'WEBGL_lose_context',
 'WEBGL_multi_draw',
 'WEBGL_polygon_mode',
 'WEBGL_provoking_vertex',
 'WEBGL_render_shared_exponent',
 'WEBGL_stencil_texturing')
MAC_CHROMIUM150_WEBGPU_FEATURES = ('bgra8unorm-storage',
 'clip-distances',
 'core-features-and-limits',
 'depth-clip-control',
 'depth32float-stencil8',
 'dual-source-blending',
 'float32-blendable',
 'float32-filterable',
 'indirect-first-instance',
 'primitive-index',
 'rg11b10ufloat-renderable',
 'shader-f16',
 'subgroups',
 'texture-component-swizzle',
 'texture-compression-astc',
 'texture-compression-astc-sliced-3d',
 'texture-compression-bc',
 'texture-compression-bc-sliced-3d',
 'texture-compression-etc2',
 'texture-formats-tier1',
 'texture-formats-tier2',
 'timestamp-query')
MAC_CHROMIUM150_WEBGPU_LIMITS = {'max_texture_dimension_1d': 16384,
 'max_texture_dimension_2d': 16384,
 'max_texture_dimension_3d': 2048,
 'max_texture_array_layers': 2048,
 'max_bind_groups': 4,
 'max_bind_groups_plus_vertex_buffers': 24,
 'max_bindings_per_bind_group': 1000,
 'max_dynamic_uniform_buffers_per_pipeline_layout': 10,
 'max_dynamic_storage_buffers_per_pipeline_layout': 8,
 'max_sampled_textures_per_shader_stage': 48,
 'max_samplers_per_shader_stage': 16,
 'max_storage_buffers_per_shader_stage': 10,
 'max_storage_textures_per_shader_stage': 8,
 'max_uniform_buffers_per_shader_stage': 12,
 'max_uniform_buffer_binding_size': 65536,
 'max_storage_buffer_binding_size': 4294967292,
 'min_uniform_buffer_offset_alignment': 256,
 'min_storage_buffer_offset_alignment': 256,
 'max_vertex_buffers': 8,
 'max_buffer_size': 4294967292,
 'max_vertex_attributes': 30,
 'max_vertex_buffer_array_stride': 2048,
 'max_inter_stage_shader_variables': 28,
 'max_color_attachments': 8,
 'max_color_attachment_bytes_per_sample': 128,
 'max_compute_workgroup_storage_size': 32768,
 'max_compute_invocations_per_workgroup': 1024,
 'max_compute_workgroup_size_x': 1024,
 'max_compute_workgroup_size_y': 1024,
 'max_compute_workgroup_size_z': 64,
 'max_compute_workgroups_per_dimension': 65535,
 'max_immediate_size': 64,
 'max_storage_buffers_in_fragment_stage': 10,
 'max_storage_textures_in_fragment_stage': 8,
 'max_storage_buffers_in_vertex_stage': 10,
 'max_storage_textures_in_vertex_stage': 8}
MAC_CHROMIUM150_AUDIO = {'sample_rate': 48000,
 'max_channel_count': 2,
 'base_latency': 0.005333333333333333,
 'output_latency': 0}
MAC_CHROMIUM150_MEDIA_LISTS = {'supported_constraints': ('aspectRatio',
                           'autoGainControl',
                           'brightness',
                           'channelCount',
                           'colorTemperature',
                           'contrast',
                           'deviceId',
                           'displaySurface',
                           'echoCancellation',
                           'exposureCompensation',
                           'exposureMode',
                           'exposureTime',
                           'facingMode',
                           'focusDistance',
                           'focusMode',
                           'frameRate',
                           'groupId',
                           'height',
                           'iso',
                           'latency',
                           'noiseSuppression',
                           'pan',
                           'pointsOfInterest',
                           'resizeMode',
                           'restrictOwnAudio',
                           'sampleRate',
                           'sampleSize',
                           'saturation',
                           'sharpness',
                           'suppressLocalAudioPlayback',
                           'tilt',
                           'torch',
                           'voiceIsolation',
                           'whiteBalanceMode',
                           'width',
                           'zoom'),
 'can_play_probably_types': ('audio/aac',
                             'audio/flac',
                             'audio/mpeg',
                             'audio/mp4; codecs="mp4a.40.2"',
                             'audio/webm; codecs="opus"',
                             'audio/webm; codecs="vorbis"',
                             'video/mp4; codecs="avc1.42001e"',
                             'video/mp4; codecs="avc1.4d401f"',
                             'video/mp4; codecs="avc1.640028"',
                             'video/mp4; codecs="av01.0.05M.08"',
                             'video/mp4; codecs="hvc1.1.6.L93.B0"',
                             'video/webm; codecs="vp8"',
                             'video/webm; codecs="vp09.00.10.08"',
                             'video/webm; codecs="av01.0.05M.08"'),
 'can_play_maybe_types': ('audio/mp4',
                          'audio/ogg',
                          'audio/wav',
                          'audio/webm',
                          'video/mp4',
                          'video/ogg',
                          'video/webm'),
 'media_source_types': ('audio/aac',
                        'audio/mpeg',
                        'audio/mp4; codecs="mp4a.40.2"',
                        'audio/webm; codecs="opus"',
                        'audio/webm; codecs="vorbis"',
                        'video/mp4; codecs="avc1.42001e"',
                        'video/mp4; codecs="avc1.4d401f"',
                        'video/mp4; codecs="avc1.640028"',
                        'video/mp4; codecs="av01.0.05M.08"',
                        'video/mp4; codecs="hvc1.1.6.L93.B0"',
                        'video/webm; codecs="vp8"',
                        'video/webm; codecs="vp09.00.10.08"',
                        'video/webm; codecs="av01.0.05M.08"'),
 'media_recorder_types': ('audio/mp4',
                          'audio/webm',
                          'video/mp4',
                          'video/webm',
                          'audio/mp4; codecs="mp4a.40.2"',
                          'audio/webm; codecs="opus"',
                          'video/mp4; codecs="avc1.42001e"',
                          'video/mp4; codecs="avc1.4d401f"',
                          'video/mp4; codecs="avc1.640028"',
                          'video/mp4; codecs="av01.0.05M.08"',
                          'video/mp4; codecs="hvc1.1.6.L93.B0"',
                          'video/webm; codecs="vp8"',
                          'video/webm; codecs="av01.0.05M.08"'),
 'decoding_supported_types': ('audio/aac',
                              'audio/flac',
                              'audio/mpeg',
                              'audio/mp4; codecs="mp4a.40.2"',
                              'audio/webm; codecs="opus"',
                              'audio/webm; codecs="vorbis"',
                              'video/mp4; codecs="avc1.42001e"',
                              'video/mp4; codecs="avc1.4d401f"',
                              'video/mp4; codecs="avc1.640028"',
                              'video/mp4; codecs="av01.0.05M.08"',
                              'video/mp4; codecs="hvc1.1.6.L93.B0"',
                              'video/webm; codecs="vp8"',
                              'video/webm; codecs="vp09.00.10.08"',
                              'video/webm; codecs="av01.0.05M.08"'),
 'decoding_smooth_types': ('audio/aac',
                           'audio/flac',
                           'audio/mpeg',
                           'audio/mp4; codecs="mp4a.40.2"',
                           'audio/webm; codecs="opus"',
                           'audio/webm; codecs="vorbis"',
                           'video/mp4; codecs="avc1.42001e"',
                           'video/mp4; codecs="avc1.4d401f"',
                           'video/mp4; codecs="avc1.640028"',
                           'video/mp4; codecs="av01.0.05M.08"',
                           'video/mp4; codecs="hvc1.1.6.L93.B0"',
                           'video/webm; codecs="vp8"',
                           'video/webm; codecs="vp09.00.10.08"',
                           'video/webm; codecs="av01.0.05M.08"'),
 'decoding_power_efficient_types': ('audio/aac',
                                    'audio/flac',
                                    'audio/mpeg',
                                    'audio/mp4; codecs="mp4a.40.2"',
                                    'audio/webm; codecs="opus"',
                                    'audio/webm; codecs="vorbis"',
                                    'video/mp4; codecs="avc1.42001e"',
                                    'video/mp4; codecs="avc1.4d401f"',
                                    'video/mp4; codecs="avc1.640028"',
                                    'video/mp4; codecs="av01.0.05M.08"',
                                    'video/mp4; codecs="hvc1.1.6.L93.B0"',
                                    'video/webm; codecs="vp09.00.10.08"',
                                    'video/webm; codecs="av01.0.05M.08"'),
 'encoding_supported_types': (),
 'encoding_smooth_types': (),
 'encoding_power_efficient_types': (),
 'image_decoder_types': ('image/avif',
                         'image/bmp',
                         'image/gif',
                         'image/jpeg',
                         'image/png',
                         'image/webp'),
 'audio_decoder_codecs': ('mp4a.40.2', 'mp3', 'opus'),
 'audio_encoder_codecs': ('mp4a.40.2', 'opus'),
 'video_decoder_codecs': ('avc1.42001e',
                          'avc1.4d401f',
                          'avc1.640028',
                          'av01.0.05M.08',
                          'vp8',
                          'vp09.00.10.08',
                          'hvc1.1.6.L93.B0'),
 'video_encoder_codecs': ('av01.0.05M.08', 'vp8', 'vp09.00.10.08', 'hvc1.1.6.L93.B0')}
MAC_CHROMIUM150_RTC_AUDIO_CODECS = (('audio/opus', 48000, 2, 'minptime=10;useinbandfec=1'),
 ('audio/red', 48000, 2, None),
 ('audio/G722', 8000, 1, None),
 ('audio/PCMU', 8000, 1, None),
 ('audio/PCMA', 8000, 1, None),
 ('audio/CN', 8000, 1, None),
 ('audio/telephone-event', 48000, 1, None),
 ('audio/telephone-event', 8000, 1, None))
MAC_CHROMIUM150_RTC_VIDEO_CODECS = (('video/VP8', 90000, None, None),
 ('video/rtx', 90000, None, None),
 ('video/H264',
  90000,
  None,
  'level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f'),
 ('video/H264',
  90000,
  None,
  'level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f'),
 ('video/H264',
  90000,
  None,
  'level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f'),
 ('video/H264',
  90000,
  None,
  'level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f'),
 ('video/H264',
  90000,
  None,
  'level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f'),
 ('video/H264',
  90000,
  None,
  'level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f'),
 ('video/AV1', 90000, None, 'level-idx=5;profile=0;tier=0'),
 ('video/VP9', 90000, None, 'profile-id=0'),
 ('video/VP9', 90000, None, 'profile-id=2'),
 ('video/H264',
  90000,
  None,
  'level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640034'),
 ('video/H265', 90000, None, 'level-id=186;profile-id=1;tier-flag=0;tx-mode=SRST'),
 ('video/red', 90000, None, None),
 ('video/ulpfec', 90000, None, None))
MAC_CHROMIUM150_RTC_HEADER_EXTENSIONS = (('audio', 'urn:ietf:params:rtp-hdrext:ssrc-audio-level'),
 ('audio', 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time'),
 ('audio', 'http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01'),
 ('audio', 'urn:ietf:params:rtp-hdrext:sdes:mid'),
 ('video', 'urn:ietf:params:rtp-hdrext:toffset'),
 ('video', 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time'),
 ('video', 'urn:3gpp:video-orientation'),
 ('video', 'http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01'),
 ('video', 'http://www.webrtc.org/experiments/rtp-hdrext/playout-delay'),
 ('video', 'http://www.webrtc.org/experiments/rtp-hdrext/video-content-type'),
 ('video', 'http://www.webrtc.org/experiments/rtp-hdrext/video-timing'),
 ('video', 'http://www.webrtc.org/experiments/rtp-hdrext/color-space'),
 ('video', 'urn:ietf:params:rtp-hdrext:sdes:mid'),
 ('video', 'urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id'),
 ('video', 'urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id'))
MAC_CHROMIUM150_KEYBOARD_LAYOUT = (('KeyK', 'k'),
 ('KeyG', 'g'),
 ('Digit2', '2'),
 ('Digit0', '0'),
 ('KeyV', 'v'),
 ('KeyA', 'a'),
 ('Backquote', '`'),
 ('KeyL', 'l'),
 ('IntlBackslash', '§'),
 ('Quote', "'"),
 ('KeyW', 'w'),
 ('Digit8', '8'),
 ('KeyM', 'm'),
 ('KeyH', 'h'),
 ('Period', '.'),
 ('Digit7', '7'),
 ('Digit1', '1'),
 ('KeyP', 'p'),
 ('KeyD', 'd'),
 ('KeyF', 'f'),
 ('KeyO', 'o'),
 ('KeyQ', 'q'),
 ('KeyC', 'c'),
 ('KeyN', 'n'),
 ('BracketLeft', '['),
 ('KeyZ', 'z'),
 ('KeyY', 'y'),
 ('Digit3', '3'),
 ('Digit6', '6'),
 ('Digit5', '5'),
 ('KeyX', 'x'),
 ('Slash', '/'),
 ('Backslash', '\\'),
 ('Comma', ','),
 ('Minus', '-'),
 ('Digit4', '4'),
 ('KeyB', 'b'),
 ('KeyT', 't'),
 ('Digit9', '9'),
 ('KeyS', 's'),
 ('KeyI', 'i'),
 ('KeyU', 'u'),
 ('Equal', '='),
 ('KeyJ', 'j'),
 ('Semicolon', ';'),
 ('KeyR', 'r'),
 ('BracketRight', ']'),
 ('KeyE', 'e'))
MACOS_LOCAL_SPEECH_VOICES = (('zh-CN', '婷婷', '婷婷', True, True),
 ('en-US', 'Albert', 'Albert', True, False),
 ('it-IT', 'Alice', 'Alice', True, False),
 ('sv-SE', 'Alva', 'Alva', True, False),
 ('fr-CA', 'Amélie', 'Amélie', True, False),
 ('ms-MY', 'Amira', 'Amira', True, False),
 ('de-DE', 'Anna', 'Anna', True, False),
 ('en-US', 'Bad News', 'Bad News', True, False),
 ('en-US', 'Bahh', 'Bahh', True, False),
 ('en-US', 'Bells', 'Bells', True, False),
 ('en-US', 'Boing', 'Boing', True, False),
 ('en-US', 'Bubbles', 'Bubbles', True, False),
 ('he-IL', 'Carmit', 'Carmit', True, False),
 ('en-US', 'Cellos', 'Cellos', True, False),
 ('id-ID', 'Damayanti', 'Damayanti', True, False),
 ('en-GB', 'Daniel', 'Daniel', True, False),
 ('bg-BG', 'Daria', 'Daria', True, False),
 ('zh-CN', 'Eddy (中文（中国大陆）)', 'Eddy (中文（中国大陆）)', True, False),
 ('zh-TW', 'Eddy (中文（台湾）)', 'Eddy (中文（台湾）)', True, False),
 ('de-DE', 'Eddy (德语（德国）)', 'Eddy (德语（德国）)', True, False),
 ('en-GB', 'Eddy (英语（英国）)', 'Eddy (英语（英国）)', True, False),
 ('en-US', 'Eddy (英语（美国）)', 'Eddy (英语（美国）)', True, False),
 ('es-ES', 'Eddy (西班牙语（西班牙）)', 'Eddy (西班牙语（西班牙）)', True, False),
 ('es-MX', 'Eddy (西班牙语（墨西哥）)', 'Eddy (西班牙语（墨西哥）)', True, False),
 ('fi-FI', 'Eddy (芬兰语（芬兰）)', 'Eddy (芬兰语（芬兰）)', True, False),
 ('fr-CA', 'Eddy (法语（加拿大）)', 'Eddy (法语（加拿大）)', True, False),
 ('fr-FR', 'Eddy (法语（法国）)', 'Eddy (法语（法国）)', True, False),
 ('it-IT', 'Eddy (意大利语（意大利）)', 'Eddy (意大利语（意大利）)', True, False),
 ('ja-JP', 'Eddy (日语（日本）)', 'Eddy (日语（日本）)', True, False),
 ('ko-KR', 'Eddy (韩语（韩国）)', 'Eddy (韩语（韩国）)', True, False),
 ('pt-BR', 'Eddy (葡萄牙语（巴西）)', 'Eddy (葡萄牙语（巴西）)', True, False),
 ('nl-BE', 'Ellen', 'Ellen', True, False),
 ('zh-CN', 'Flo (中文（中国大陆）)', 'Flo (中文（中国大陆）)', True, False),
 ('zh-TW', 'Flo (中文（台湾）)', 'Flo (中文（台湾）)', True, False),
 ('de-DE', 'Flo (德语（德国）)', 'Flo (德语（德国）)', True, False),
 ('en-GB', 'Flo (英语（英国）)', 'Flo (英语（英国）)', True, False),
 ('en-US', 'Flo (英语（美国）)', 'Flo (英语（美国）)', True, False),
 ('es-ES', 'Flo (西班牙语（西班牙）)', 'Flo (西班牙语（西班牙）)', True, False),
 ('es-MX', 'Flo (西班牙语（墨西哥）)', 'Flo (西班牙语（墨西哥）)', True, False),
 ('fi-FI', 'Flo (芬兰语（芬兰）)', 'Flo (芬兰语（芬兰）)', True, False),
 ('fr-CA', 'Flo (法语（加拿大）)', 'Flo (法语（加拿大）)', True, False),
 ('fr-FR', 'Flo (法语（法国）)', 'Flo (法语（法国）)', True, False),
 ('it-IT', 'Flo (意大利语（意大利）)', 'Flo (意大利语（意大利）)', True, False),
 ('ja-JP', 'Flo (日语（日本）)', 'Flo (日语（日本）)', True, False),
 ('ko-KR', 'Flo (韩语（韩国）)', 'Flo (韩语（韩国）)', True, False),
 ('pt-BR', 'Flo (葡萄牙语（巴西）)', 'Flo (葡萄牙语（巴西）)', True, False),
 ('en-US', 'Fred', 'Fred', True, False),
 ('te-IN', 'Geeta', 'Geeta', True, False),
 ('en-US', 'Good News', 'Good News', True, False),
 ('zh-CN', 'Grandma (中文（中国大陆）)', 'Grandma (中文（中国大陆）)', True, False),
 ('zh-TW', 'Grandma (中文（台湾）)', 'Grandma (中文（台湾）)', True, False),
 ('de-DE', 'Grandma (德语（德国）)', 'Grandma (德语（德国）)', True, False),
 ('en-GB', 'Grandma (英语（英国）)', 'Grandma (英语（英国）)', True, False),
 ('en-US', 'Grandma (英语（美国）)', 'Grandma (英语（美国）)', True, False),
 ('es-ES', 'Grandma (西班牙语（西班牙）)', 'Grandma (西班牙语（西班牙）)', True, False),
 ('es-MX', 'Grandma (西班牙语（墨西哥）)', 'Grandma (西班牙语（墨西哥）)', True, False),
 ('fi-FI', 'Grandma (芬兰语（芬兰）)', 'Grandma (芬兰语（芬兰）)', True, False),
 ('fr-CA', 'Grandma (法语（加拿大）)', 'Grandma (法语（加拿大）)', True, False),
 ('fr-FR', 'Grandma (法语（法国）)', 'Grandma (法语（法国）)', True, False),
 ('it-IT', 'Grandma (意大利语（意大利）)', 'Grandma (意大利语（意大利）)', True, False),
 ('ja-JP', 'Grandma (日语（日本）)', 'Grandma (日语（日本）)', True, False),
 ('ko-KR', 'Grandma (韩语（韩国）)', 'Grandma (韩语（韩国）)', True, False),
 ('pt-BR', 'Grandma (葡萄牙语（巴西）)', 'Grandma (葡萄牙语（巴西）)', True, False),
 ('zh-CN', 'Grandpa (中文（中国大陆）)', 'Grandpa (中文（中国大陆）)', True, False),
 ('zh-TW', 'Grandpa (中文（台湾）)', 'Grandpa (中文（台湾）)', True, False),
 ('de-DE', 'Grandpa (德语（德国）)', 'Grandpa (德语（德国）)', True, False),
 ('en-GB', 'Grandpa (英语（英国）)', 'Grandpa (英语（英国）)', True, False),
 ('en-US', 'Grandpa (英语（美国）)', 'Grandpa (英语（美国）)', True, False),
 ('es-ES', 'Grandpa (西班牙语（西班牙）)', 'Grandpa (西班牙语（西班牙）)', True, False),
 ('es-MX', 'Grandpa (西班牙语（墨西哥）)', 'Grandpa (西班牙语（墨西哥）)', True, False),
 ('fi-FI', 'Grandpa (芬兰语（芬兰）)', 'Grandpa (芬兰语（芬兰）)', True, False),
 ('fr-CA', 'Grandpa (法语（加拿大）)', 'Grandpa (法语（加拿大）)', True, False),
 ('fr-FR', 'Grandpa (法语（法国）)', 'Grandpa (法语（法国）)', True, False),
 ('it-IT', 'Grandpa (意大利语（意大利）)', 'Grandpa (意大利语（意大利）)', True, False),
 ('ja-JP', 'Grandpa (日语（日本）)', 'Grandpa (日语（日本）)', True, False),
 ('ko-KR', 'Grandpa (韩语（韩国）)', 'Grandpa (韩语（韩国）)', True, False),
 ('pt-BR', 'Grandpa (葡萄牙语（巴西）)', 'Grandpa (葡萄牙语（巴西）)', True, False),
 ('ro-RO', 'Ioana', 'Ioana', True, False),
 ('fr-FR', 'Jacques', 'Jacques', True, False),
 ('en-US', 'Jester', 'Jester', True, False),
 ('pt-PT', 'Joana', 'Joana', True, False),
 ('en-US', 'Junior', 'Junior', True, False),
 ('th-TH', 'Kanya', 'Kanya', True, False),
 ('en-AU', 'Karen', 'Karen', True, False),
 ('en-US', 'Kathy', 'Kathy', True, False),
 ('ja-JP', 'Kyoko', 'Kyoko', True, False),
 ('hr-HR', 'Lana', 'Lana', True, False),
 ('sk-SK', 'Laura', 'Laura', True, False),
 ('hi-IN', 'Lekha', 'Lekha', True, False),
 ('uk-UA', 'Lesya', 'Lesya', True, False),
 ('vi-VN', 'Linh', 'Linh', True, False),
 ('pt-BR', 'Luciana', 'Luciana', True, False),
 ('ar-001', 'Majed', 'Majed', True, False),
 ('el-GR', 'Melina', 'Melina', True, False),
 ('ru-RU', 'Milena', 'Milena', True, False),
 ('en-IE', 'Moira', 'Moira', True, False),
 ('ca-ES', 'Montse', 'Montse', True, False),
 ('es-ES', 'Mónica', 'Mónica', True, False),
 ('nb-NO', 'Nora', 'Nora', True, False),
 ('en-US', 'Organ', 'Organ', True, False),
 ('es-MX', 'Paulina', 'Paulina', True, False),
 ('bn-IN', 'Piya', 'Piya', True, False),
 ('en-US', 'Ralph', 'Ralph', True, False),
 ('zh-CN', 'Reed (中文（中国大陆）)', 'Reed (中文（中国大陆）)', True, False),
 ('zh-TW', 'Reed (中文（台湾）)', 'Reed (中文（台湾）)', True, False),
 ('de-DE', 'Reed (德语（德国）)', 'Reed (德语（德国）)', True, False),
 ('en-GB', 'Reed (英语（英国）)', 'Reed (英语（英国）)', True, False),
 ('en-US', 'Reed (英语（美国）)', 'Reed (英语（美国）)', True, False),
 ('es-ES', 'Reed (西班牙语（西班牙）)', 'Reed (西班牙语（西班牙）)', True, False),
 ('es-MX', 'Reed (西班牙语（墨西哥）)', 'Reed (西班牙语（墨西哥）)', True, False),
 ('fi-FI', 'Reed (芬兰语（芬兰）)', 'Reed (芬兰语（芬兰）)', True, False),
 ('fr-CA', 'Reed (法语（加拿大）)', 'Reed (法语（加拿大）)', True, False),
 ('it-IT', 'Reed (意大利语（意大利）)', 'Reed (意大利语（意大利）)', True, False),
 ('ja-JP', 'Reed (日语（日本）)', 'Reed (日语（日本）)', True, False),
 ('ko-KR', 'Reed (韩语（韩国）)', 'Reed (韩语（韩国）)', True, False),
 ('pt-BR', 'Reed (葡萄牙语（巴西）)', 'Reed (葡萄牙语（巴西）)', True, False),
 ('en-IN', 'Rishi', 'Rishi', True, False),
 ('zh-CN', 'Rocko (中文（中国大陆）)', 'Rocko (中文（中国大陆）)', True, False),
 ('zh-TW', 'Rocko (中文（台湾）)', 'Rocko (中文（台湾）)', True, False),
 ('de-DE', 'Rocko (德语（德国）)', 'Rocko (德语（德国）)', True, False),
 ('en-GB', 'Rocko (英语（英国）)', 'Rocko (英语（英国）)', True, False),
 ('en-US', 'Rocko (英语（美国）)', 'Rocko (英语（美国）)', True, False),
 ('es-ES', 'Rocko (西班牙语（西班牙）)', 'Rocko (西班牙语（西班牙）)', True, False),
 ('es-MX', 'Rocko (西班牙语（墨西哥）)', 'Rocko (西班牙语（墨西哥）)', True, False),
 ('fi-FI', 'Rocko (芬兰语（芬兰）)', 'Rocko (芬兰语（芬兰）)', True, False),
 ('fr-CA', 'Rocko (法语（加拿大）)', 'Rocko (法语（加拿大）)', True, False),
 ('fr-FR', 'Rocko (法语（法国）)', 'Rocko (法语（法国）)', True, False),
 ('it-IT', 'Rocko (意大利语（意大利）)', 'Rocko (意大利语（意大利）)', True, False),
 ('ja-JP', 'Rocko (日语（日本）)', 'Rocko (日语（日本）)', True, False),
 ('ko-KR', 'Rocko (韩语（韩国）)', 'Rocko (韩语（韩国）)', True, False),
 ('pt-BR', 'Rocko (葡萄牙语（巴西）)', 'Rocko (葡萄牙语（巴西）)', True, False),
 ('en-US', 'Samantha', 'Samantha', True, False),
 ('zh-CN', 'Sandy (中文（中国大陆）)', 'Sandy (中文（中国大陆）)', True, False),
 ('zh-TW', 'Sandy (中文（台湾）)', 'Sandy (中文（台湾）)', True, False),
 ('de-DE', 'Sandy (德语（德国）)', 'Sandy (德语（德国）)', True, False),
 ('en-GB', 'Sandy (英语（英国）)', 'Sandy (英语（英国）)', True, False),
 ('en-US', 'Sandy (英语（美国）)', 'Sandy (英语（美国）)', True, False),
 ('es-ES', 'Sandy (西班牙语（西班牙）)', 'Sandy (西班牙语（西班牙）)', True, False),
 ('es-MX', 'Sandy (西班牙语（墨西哥）)', 'Sandy (西班牙语（墨西哥）)', True, False),
 ('fi-FI', 'Sandy (芬兰语（芬兰）)', 'Sandy (芬兰语（芬兰）)', True, False),
 ('fr-CA', 'Sandy (法语（加拿大）)', 'Sandy (法语（加拿大）)', True, False),
 ('fr-FR', 'Sandy (法语（法国）)', 'Sandy (法语（法国）)', True, False),
 ('it-IT', 'Sandy (意大利语（意大利）)', 'Sandy (意大利语（意大利）)', True, False),
 ('ja-JP', 'Sandy (日语（日本）)', 'Sandy (日语（日本）)', True, False),
 ('ko-KR', 'Sandy (韩语（韩国）)', 'Sandy (韩语（韩国）)', True, False),
 ('pt-BR', 'Sandy (葡萄牙语（巴西）)', 'Sandy (葡萄牙语（巴西）)', True, False),
 ('da-DK', 'Sara', 'Sara', True, False),
 ('fi-FI', 'Satu', 'Satu', True, False),
 ('zh-CN', 'Shelley (中文（中国大陆）)', 'Shelley (中文（中国大陆）)', True, False),
 ('zh-TW', 'Shelley (中文（台湾）)', 'Shelley (中文（台湾）)', True, False),
 ('de-DE', 'Shelley (德语（德国）)', 'Shelley (德语（德国）)', True, False),
 ('en-GB', 'Shelley (英语（英国）)', 'Shelley (英语（英国）)', True, False),
 ('en-US', 'Shelley (英语（美国）)', 'Shelley (英语（美国）)', True, False),
 ('es-ES', 'Shelley (西班牙语（西班牙）)', 'Shelley (西班牙语（西班牙）)', True, False),
 ('es-MX', 'Shelley (西班牙语（墨西哥）)', 'Shelley (西班牙语（墨西哥）)', True, False),
 ('fi-FI', 'Shelley (芬兰语（芬兰）)', 'Shelley (芬兰语（芬兰）)', True, False),
 ('fr-CA', 'Shelley (法语（加拿大）)', 'Shelley (法语（加拿大）)', True, False),
 ('fr-FR', 'Shelley (法语（法国）)', 'Shelley (法语（法国）)', True, False),
 ('it-IT', 'Shelley (意大利语（意大利）)', 'Shelley (意大利语（意大利）)', True, False),
 ('ja-JP', 'Shelley (日语（日本）)', 'Shelley (日语（日本）)', True, False),
 ('ko-KR', 'Shelley (韩语（韩国）)', 'Shelley (韩语（韩国）)', True, False),
 ('pt-BR', 'Shelley (葡萄牙语（巴西）)', 'Shelley (葡萄牙语（巴西）)', True, False),
 ('kn-IN', 'Soumya', 'Soumya', True, False),
 ('en-US', 'Superstar', 'Superstar', True, False),
 ('en-ZA', 'Tessa', 'Tessa', True, False),
 ('fr-FR', 'Thomas', 'Thomas', True, False),
 ('sl-SI', 'Tina', 'Tina', True, False),
 ('en-US', 'Trinoids', 'Trinoids', True, False),
 ('hu-HU', 'Tünde', 'Tünde', True, False),
 ('ta-IN', 'Vani', 'Vani', True, False),
 ('en-US', 'Whisper', 'Whisper', True, False),
 ('en-US', 'Wobble', 'Wobble', True, False),
 ('nl-NL', 'Xander', 'Xander', True, False),
 ('tr-TR', 'Yelda', 'Yelda', True, False),
 ('ko-KR', 'Yuna', 'Yuna', True, False),
 ('en-US', 'Zarvox', 'Zarvox', True, False),
 ('pl-PL', 'Zosia', 'Zosia', True, False),
 ('cs-CZ', 'Zuzana', 'Zuzana', True, False),
 ('yue-HK', '善怡', '善怡', True, False),
 ('zh-TW', '美嘉', '美嘉', True, False))
CHROME_MAC_REMOTE_SPEECH_VOICES = (('de-DE', 'Google Deutsch', 'Google Deutsch', False, False),
 ('en-US', 'Google US English', 'Google US English', False, False),
 ('en-GB', 'Google UK English Female', 'Google UK English Female', False, False),
 ('en-GB', 'Google UK English Male', 'Google UK English Male', False, False),
 ('es-ES', 'Google español', 'Google español', False, False),
 ('es-US', 'Google español de Estados Unidos', 'Google español de Estados Unidos', False, False),
 ('fr-FR', 'Google français', 'Google français', False, False),
 ('hi-IN', 'Google हिन्दी', 'Google हिन्दी', False, False),
 ('id-ID', 'Google Bahasa Indonesia', 'Google Bahasa Indonesia', False, False),
 ('it-IT', 'Google italiano', 'Google italiano', False, False),
 ('ja-JP', 'Google 日本語', 'Google 日本語', False, False),
 ('ko-KR', 'Google 한국의', 'Google 한국의', False, False),
 ('nl-NL', 'Google Nederlands', 'Google Nederlands', False, False),
 ('pl-PL', 'Google polski', 'Google polski', False, False),
 ('pt-BR', 'Google português do Brasil', 'Google português do Brasil', False, False),
 ('ru-RU', 'Google русский', 'Google русский', False, False),
 ('zh-CN', 'Google\xa0普通话（中国大陆）', 'Google\xa0普通话（中国大陆）', False, False),
 ('zh-HK', 'Google\xa0粤語（香港）', 'Google\xa0粤語（香港）', False, False),
 ('zh-TW', 'Google 國語（臺灣）', 'Google 國語（臺灣）', False, False))

__all__ = [name for name in globals() if name.isupper()]
