"""Real macOS speechSynthesis voice inventory from the Safari capture project."""

from __future__ import annotations

MACOS_SPEECH_CAPTURE_SOURCE = "safari_sandbox-main/fixtures/hcaptcha/baidu_page_snapshot.json"

# lang, name, voiceURI, localService, captured default
MACOS_SPEECH_VOICES: tuple[tuple[str, str, str, bool, bool], ...] = (
    ('zh-CN', '婷婷', 'com.apple.voice.super-compact.zh-CN.Tingting', True, True),
    ('zh-TW', '美嘉', 'com.apple.voice.super-compact.zh-TW.Meijia', True, True),
    ('it-IT', 'Alice', 'com.apple.voice.super-compact.it-IT.Alice', True, True),
    ('sv-SE', 'Alva', 'com.apple.voice.super-compact.sv-SE.Alva', True, True),
    ('fr-CA', 'Amélie', 'com.apple.voice.super-compact.fr-CA.Amelie', True, True),
    ('ms-MY', 'Amira', 'com.apple.voice.super-compact.ms-MY.Amira', True, True),
    ('de-DE', 'Anna', 'com.apple.voice.super-compact.de-DE.Anna', True, True),
    ('he-IL', 'Carmit', 'com.apple.voice.super-compact.he-IL.Carmit', True, True),
    ('id-ID', 'Damayanti', 'com.apple.voice.super-compact.id-ID.Damayanti', True, True),
    ('en-GB', 'Daniel', 'com.apple.voice.super-compact.en-GB.Daniel', True, True),
    ('bg-BG', 'Daria', 'com.apple.voice.super-compact.bg-BG.Daria', True, True),
    ('nl-BE', 'Ellen', 'com.apple.voice.super-compact.nl-BE.Ellen', True, True),
    ('ro-RO', 'Ioana', 'com.apple.voice.super-compact.ro-RO.Ioana', True, True),
    ('pt-PT', 'Joana', 'com.apple.voice.super-compact.pt-PT.Joana', True, True),
    ('th-TH', 'Kanya', 'com.apple.voice.super-compact.th-TH.Kanya', True, True),
    ('en-AU', 'Karen', 'com.apple.voice.super-compact.en-AU.Karen', True, True),
    ('ja-JP', 'Kyoko', 'com.apple.voice.super-compact.ja-JP.Kyoko', True, True),
    ('hr-HR', 'Lana', 'com.apple.voice.super-compact.hr-HR.Lana', True, True),
    ('sk-SK', 'Laura', 'com.apple.voice.super-compact.sk-SK.Laura', True, True),
    ('hi-IN', 'Lekha', 'com.apple.voice.super-compact.hi-IN.Lekha', True, True),
    ('uk-UA', 'Lesya', 'com.apple.voice.super-compact.uk-UA.Lesya', True, True),
    ('vi-VN', 'Linh', 'com.apple.voice.super-compact.vi-VN.Linh', True, True),
    ('pt-BR', 'Luciana', 'com.apple.voice.super-compact.pt-BR.Luciana', True, True),
    ('ar-001', 'Majed', 'com.apple.voice.super-compact.ar-001.Maged', True, True),
    ('hu-HU', 'Tünde', 'com.apple.voice.super-compact.hu-HU.Mariska', True, True),
    ('el-GR', 'Melina', 'com.apple.voice.super-compact.el-GR.Melina', True, True),
    ('ru-RU', 'Milena', 'com.apple.voice.super-compact.ru-RU.Milena', True, True),
    ('en-IE', 'Moira', 'com.apple.voice.super-compact.en-IE.Moira', True, True),
    ('es-ES', 'Mónica', 'com.apple.voice.super-compact.es-ES.Monica', True, True),
    ('ca-ES', 'Montse', 'com.apple.voice.super-compact.ca-ES.Montserrat', True, True),
    ('nb-NO', 'Nora', 'com.apple.voice.super-compact.nb-NO.Nora', True, True),
    ('es-MX', 'Paulina', 'com.apple.voice.super-compact.es-MX.Paulina', True, True),
    ('en-IN', 'Rishi', 'com.apple.voice.super-compact.en-IN.Rishi', True, True),
    ('en-US', 'Samantha', 'com.apple.voice.super-compact.en-US.Samantha', True, True),
    ('da-DK', 'Sara', 'com.apple.voice.super-compact.da-DK.Sara', True, True),
    ('fi-FI', 'Satu', 'com.apple.voice.super-compact.fi-FI.Satu', True, True),
    ('yue-HK', '善怡', 'com.apple.voice.super-compact.zh-HK.Sinji', True, True),
    ('en-ZA', 'Tessa', 'com.apple.voice.super-compact.en-ZA.Tessa', True, True),
    ('fr-FR', 'Thomas', 'com.apple.voice.super-compact.fr-FR.Thomas', True, True),
    ('sl-SI', 'Tina', 'com.apple.voice.super-compact.sl-SI.Tina', True, True),
    ('nl-NL', 'Xander', 'com.apple.voice.super-compact.nl-NL.Xander', True, True),
    ('tr-TR', 'Yelda', 'com.apple.voice.super-compact.tr-TR.Yelda', True, True),
    ('ko-KR', 'Yuna', 'com.apple.voice.super-compact.ko-KR.Yuna', True, True),
    ('pl-PL', 'Zosia', 'com.apple.voice.super-compact.pl-PL.Zosia', True, True),
    ('cs-CZ', 'Zuzana', 'com.apple.voice.super-compact.cs-CZ.Zuzana', True, True),
    ('ta-IN', 'Vani', 'com.apple.voice.super-compact.ta-IN.Vani', True, True),
    ('en-US', 'Albert', 'com.apple.speech.synthesis.voice.Albert', True, True),
    ('kn-IN', 'Soumya', 'com.apple.voice.compact.kn-IN.Alpana', True, True),
    ('en-US', 'Bad News', 'com.apple.speech.synthesis.voice.BadNews', True, True),
    ('en-US', 'Bahh', 'com.apple.speech.synthesis.voice.Bahh', True, True),
    ('en-US', 'Bells', 'com.apple.speech.synthesis.voice.Bells', True, True),
    ('en-US', 'Boing', 'com.apple.speech.synthesis.voice.Boing', True, True),
    ('en-US', 'Bubbles', 'com.apple.speech.synthesis.voice.Bubbles', True, True),
    ('en-US', 'Cellos', 'com.apple.speech.synthesis.voice.Cellos', True, True),
    ('en-US', 'Wobble', 'com.apple.speech.synthesis.voice.Deranged', True, True),
    ('en-US', 'Fred', 'com.apple.speech.synthesis.voice.Fred', True, True),
    ('te-IN', 'Geeta', 'com.apple.voice.compact.te-IN.Geeta', True, True),
    ('en-US', 'Good News', 'com.apple.speech.synthesis.voice.GoodNews', True, True),
    ('en-US', 'Jester', 'com.apple.speech.synthesis.voice.Hysterical', True, True),
    ('en-US', 'Junior', 'com.apple.speech.synthesis.voice.Junior', True, True),
    ('en-US', 'Kathy', 'com.apple.speech.synthesis.voice.Kathy', True, True),
    ('en-US', 'Organ', 'com.apple.speech.synthesis.voice.Organ', True, True),
    ('bn-IN', 'Piya', 'com.apple.voice.compact.bn-IN.Paya', True, True),
    ('en-US', 'Superstar', 'com.apple.speech.synthesis.voice.Princess', True, True),
    ('en-US', 'Ralph', 'com.apple.speech.synthesis.voice.Ralph', True, True),
    ('en-US', 'Trinoids', 'com.apple.speech.synthesis.voice.Trinoids', True, True),
    ('en-US', 'Whisper', 'com.apple.speech.synthesis.voice.Whisper', True, True),
    ('en-US', 'Zarvox', 'com.apple.speech.synthesis.voice.Zarvox', True, True),
)

__all__ = ["MACOS_SPEECH_CAPTURE_SOURCE", "MACOS_SPEECH_VOICES"]
