"""Generated from matching M5 internal/secondary-display browser captures.

Do not edit the inventory by hand; regenerate it with
``tools/generate_mac_font_catalog.py`` after validating new evidence.
"""

from __future__ import annotations

MACOS_TAHOE_CAPTURE_PLATFORM_VERSION = '26.5.2'

MACOS_TAHOE_CAPTURE_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36 Edg/150.0.0.0'

MACOS_TAHOE_FONT_FAMILIES: tuple[str, ...] = (
    '-apple-system',
    'Academy Engraved LET',
    'Al Bayan',
    'Al Nile',
    'Al Tarikh',
    'American Typewriter',
    'Andale Mono',
    'Apple Braille',
    'Apple Chancery',
    'Apple Color Emoji',
    'Apple LiGothic',
    'Apple LiSung',
    'Apple SD Gothic Neo',
    'Apple Symbols',
    'AppleGothic',
    'AppleMyungjo',
    'Arial',
    'Arial Black',
    'Arial Hebrew',
    'Arial Hebrew Scholar',
    'Arial Narrow',
    'Arial Rounded MT Bold',
    'Arial Unicode MS',
    'Avenir',
    'Avenir Next',
    'Avenir Next Condensed',
    'Ayuthaya',
    'Baghdad',
    'Bangla MN',
    'Bangla Sangam MN',
    'Baoli SC',
    'Baoli TC',
    'Baskerville',
    'Beirut',
    'BiauKaiHK',
    'BiauKaiTC',
    'Big Caslon',
    'BIZ UDGothic',
    'BIZ UDMincho',
    'BlinkMacSystemFont',
    'BM Dohyeon',
    'BM Hanna 11yrs Old',
    'BM Hanna Air',
    'BM Hanna Pro',
    'BM Jua',
    'BM Kirang Haerang',
    'BM Yeonsung',
    'Bodoni 72',
    'Bodoni 72 Oldstyle',
    'Bodoni 72 Smallcaps',
    'Bodoni Ornaments',
    'Bradley Hand',
    'Brush Script MT',
    'Chalkboard',
    'Chalkboard SE',
    'Chalkduster',
    'Charter',
    'Cochin',
    'Comic Sans MS',
    'Copperplate',
    'Corsiva Hebrew',
    'Courier New',
    'Damascus',
    'DecoType Naskh',
    'Devanagari MT',
    'Devanagari Sangam MN',
    'Didot',
    'DIN Alternate',
    'DIN Condensed',
    'Diwan Kufi',
    'Diwan Thuluth',
    'Euphemia UCAS',
    'Farah',
    'Farisi',
    'Futura',
    'Galvji',
    'GB18030 Bitmap',
    'Geeza Pro',
    'Geneva',
    'Georgia',
    'Gill Sans',
    'Grantha Sangam MN',
    'Gujarati MT',
    'Gujarati Sangam MN',
    'GungSeo',
    'Gurmukhi MN',
    'Gurmukhi MT',
    'Gurmukhi Sangam MN',
    'Hannotate SC',
    'Hannotate TC',
    'HanziPen SC',
    'HanziPen TC',
    'HeadLineA',
    'Hei',
    'Heiti SC',
    'Heiti TC',
    'Helvetica',
    'Helvetica Neue',
    'Herculanum',
    'Hiragino Maru Gothic ProN',
    'Hiragino Mincho ProN',
    'Hiragino Sans',
    'Hiragino Sans GB',
    'Hoefler Text',
    'Impact',
    'InaiMathi',
    'ITF Devanagari',
    'ITF Devanagari Marathi',
    'Kai',
    'Kailasa',
    'Kaiti SC',
    'Kaiti TC',
    'Kannada MN',
    'Kannada Sangam MN',
    'Kefa III',
    'Khmer MN',
    'Khmer Sangam MN',
    'Klee',
    'Kohinoor Bangla',
    'Kohinoor Devanagari',
    'Kohinoor Gujarati',
    'Kohinoor Telugu',
    'Kokonor',
    'Krungthep',
    'KufiStandardGK',
    'Lantinghei SC',
    'Lantinghei TC',
    'Lao MN',
    'Lao Sangam MN',
    'Libian SC',
    'Libian TC',
    'LiHei Pro',
    'LingWai SC',
    'LingWai TC',
    'LiSong Pro',
    'Lucida Grande',
    'Luminari',
    'Malayalam MN',
    'Malayalam Sangam MN',
    'Marker Felt',
    'Menlo',
    'Microsoft Sans Serif',
    'Mishafi',
    'Mishafi Gold',
    'Monaco',
    'Mshtakan',
    'Mukta Mahee',
    'Muna',
    'Myanmar MN',
    'Myanmar Sangam MN',
    'Nadeem',
    'Nanum Brush Script',
    'Nanum Gothic',
    'Nanum Myeongjo',
    'Nanum Pen Script',
    'New Peninim MT',
    'Noteworthy',
    'Noto Nastaliq Urdu',
    'Noto Sans Batak',
    'Noto Sans Kannada',
    'Noto Sans Myanmar',
    'Noto Sans NKo',
    'Noto Sans Oriya',
    'Noto Sans Syriac',
    'Noto Sans Tagalog',
    'Noto Serif Myanmar',
    'Optima',
    'Oriya MN',
    'Oriya Sangam MN',
    'Osaka',
    'Palatino',
    'Papyrus',
    'Party LET',
    'PCMyungjo',
    'Phosphate',
    'PilGi',
    'PingFang HK',
    'PingFang MO',
    'PingFang SC',
    'PingFang TC',
    'Plantagenet Cherokee',
    'PT Mono',
    'PT Sans',
    'PT Sans Caption',
    'PT Sans Narrow',
    'PT Serif',
    'PT Serif Caption',
    'Raanana',
    'Rockwell',
    'Sana',
    'Sathu',
    'Savoye LET',
    'Shree Devanagari 714',
    'SignPainter',
    'Silom',
    'SimSong',
    'Sinhala MN',
    'Sinhala Sangam MN',
    'Skia',
    'Snell Roundhand',
    'Songti SC',
    'Songti TC',
    'STFangsong',
    'STHeiti',
    'STIX Two Math',
    'STIX Two Text',
    'STKaiti',
    'STSong',
    'Sukhumvit Set',
    'Symbol',
    'Tahoma',
    'Tamil MN',
    'Tamil Sangam MN',
    'Telugu MN',
    'Telugu Sangam MN',
    'Thonburi',
    'Times New Roman',
    'Toppan Bunkyu Gothic',
    'Toppan Bunkyu Midashi Gothic',
    'Toppan Bunkyu Midashi Mincho',
    'Toppan Bunkyu Mincho',
    'Trattatello',
    'Trebuchet MS',
    'Tsukushi A Round Gothic',
    'Tsukushi B Round Gothic',
    'Verdana',
    'Waseem',
    'Wawati SC',
    'Wawati TC',
    'Webdings',
    'Weibei SC',
    'Weibei TC',
    'Wingdings',
    'Wingdings 2',
    'Wingdings 3',
    'Xingkai SC',
    'Xingkai TC',
    'Yuanti SC',
    'Yuanti TC',
    'YuGothic',
    'YuKyokasho',
    'YuKyokasho Yoko',
    'YuMincho',
    'YuMincho +36p Kana',
    'Yuppy SC',
    'Yuppy TC',
    'Zapf Dingbats',
    'Zapfino',
)

MACOS_TAHOE_LOCAL_FONTS: tuple[tuple, ...] = (
    ('AcademyEngravedLetPlain', 'Academy Engraved LET Plain:1.0', 'Academy Engraved LET', 'Plain'),
    ('AlBayan-Bold', 'Al Bayan Bold', 'Al Bayan', 'Bold'),
    ('AlBayan', 'Al Bayan Plain', 'Al Bayan', 'Plain'),
    ('AlNile', 'Al Nile', 'Al Nile', 'Regular'),
    ('AlNile-Bold', 'Al Nile Bold', 'Al Nile', 'Bold'),
    ('AlTarikh', 'Al Tarikh Regular', 'Al Tarikh', 'Regular'),
    ('AmericanTypewriter', 'American Typewriter', 'American Typewriter', 'Regular'),
    ('AmericanTypewriter-Bold', 'American Typewriter Bold', 'American Typewriter', 'Bold'),
    ('AmericanTypewriter-Condensed', 'American Typewriter Condensed', 'American Typewriter', 'Condensed'),
    ('AmericanTypewriter-CondensedBold', 'American Typewriter Condensed Bold', 'American Typewriter', 'Condensed Bold'),
    ('AmericanTypewriter-CondensedLight', 'American Typewriter Condensed Light', 'American Typewriter', 'Condensed Light'),
    ('AmericanTypewriter-Light', 'American Typewriter Light', 'American Typewriter', 'Light'),
    ('AmericanTypewriter-Semibold', 'American Typewriter Semibold', 'American Typewriter', 'Semibold'),
    ('AndaleMono', 'Andale Mono', 'Andale Mono', 'Regular'),
    ('AppleBraille', 'Apple Braille', 'Apple Braille', 'Regular'),
    ('AppleBraille-Outline6Dot', 'Apple Braille Outline 6 Dot', 'Apple Braille', 'Outline 6 Dot'),
    ('AppleBraille-Outline8Dot', 'Apple Braille Outline 8 Dot', 'Apple Braille', 'Outline 8 Dot'),
    ('AppleBraille-Pinpoint6Dot', 'Apple Braille Pinpoint 6 Dot', 'Apple Braille', 'Pinpoint 6 Dot'),
    ('AppleBraille-Pinpoint8Dot', 'Apple Braille Pinpoint 8 Dot', 'Apple Braille', 'Pinpoint 8 Dot'),
    ('Apple-Chancery', 'Apple Chancery', 'Apple Chancery', 'Chancery'),
    ('AppleColorEmoji', 'Apple Color Emoji', 'Apple Color Emoji', 'Regular'),
    ('LiGothicMed', '蘋果儷中黑', 'Apple LiGothic', 'Medium'),
    ('LiSungLight', '蘋果儷細宋', 'Apple LiSung', 'Light'),
    ('AppleSDGothicNeo-Bold', 'Apple SD Gothic Neo Bold', 'Apple SD Gothic Neo', 'Bold'),
    ('AppleSDGothicNeo-ExtraBold', 'Apple SD Gothic Neo ExtraBold', 'Apple SD Gothic Neo', 'ExtraBold'),
    ('AppleSDGothicNeo-Heavy', 'Apple SD Gothic Neo Heavy', 'Apple SD Gothic Neo', 'Heavy'),
    ('AppleSDGothicNeo-Light', 'Apple SD Gothic Neo Light', 'Apple SD Gothic Neo', 'Light'),
    ('AppleSDGothicNeo-Medium', 'Apple SD Gothic Neo Medium', 'Apple SD Gothic Neo', 'Medium'),
    ('AppleSDGothicNeo-Regular', 'Apple SD Gothic Neo Regular', 'Apple SD Gothic Neo', 'Regular'),
    ('AppleSDGothicNeo-SemiBold', 'Apple SD Gothic Neo SemiBold', 'Apple SD Gothic Neo', 'SemiBold'),
    ('AppleSDGothicNeo-Thin', 'Apple SD Gothic Neo Thin', 'Apple SD Gothic Neo', 'Thin'),
    ('AppleSDGothicNeo-UltraLight', 'Apple SD Gothic Neo UltraLight', 'Apple SD Gothic Neo', 'UltraLight'),
    ('AppleSymbols', 'Apple Symbols', 'Apple Symbols', 'Regular'),
    ('AppleGothic', 'AppleGothic Regular', 'AppleGothic', 'Regular'),
    ('AppleMyungjo', 'AppleMyungjo Regular', 'AppleMyungjo', 'Regular'),
    ('ArialMT', 'Arial', 'Arial', 'Regular'),
    ('Arial-BoldMT', 'Arial Bold', 'Arial', 'Bold'),
    ('Arial-BoldItalicMT', 'Arial Bold Italic', 'Arial', 'Bold Italic'),
    ('Arial-ItalicMT', 'Arial Italic', 'Arial', 'Italic'),
    ('Arial-Black', 'Arial Black', 'Arial Black', 'Regular'),
    ('ArialHebrew', 'Arial Hebrew', 'Arial Hebrew', 'Regular'),
    ('ArialHebrew-Bold', 'Arial Hebrew Bold', 'Arial Hebrew', 'Bold'),
    ('ArialHebrew-Light', 'Arial Hebrew Light', 'Arial Hebrew', 'Light'),
    ('ArialHebrewScholar', 'Arial Hebrew Scholar', 'Arial Hebrew Scholar', 'Regular'),
    ('ArialHebrewScholar-Bold', 'Arial Hebrew Scholar Bold', 'Arial Hebrew Scholar', 'Bold'),
    ('ArialHebrewScholar-Light', 'Arial Hebrew Scholar Light', 'Arial Hebrew Scholar', 'Light'),
    ('ArialNarrow', 'Arial Narrow', 'Arial Narrow', 'Regular'),
    ('ArialNarrow-Bold', 'Arial Narrow Bold', 'Arial Narrow', 'Bold'),
    ('ArialNarrow-BoldItalic', 'Arial Narrow Bold Italic', 'Arial Narrow', 'Bold Italic'),
    ('ArialNarrow-Italic', 'Arial Narrow Italic', 'Arial Narrow', 'Italic'),
    ('ArialRoundedMTBold', 'Arial Rounded MT Bold', 'Arial Rounded MT Bold', 'Regular'),
    ('ArialUnicodeMS', 'Arial Unicode MS', 'Arial Unicode MS', 'Regular'),
    ('Avenir-Black', 'Avenir Black', 'Avenir', 'Black'),
    ('Avenir-BlackOblique', 'Avenir Black Oblique', 'Avenir', 'Black Oblique'),
    ('Avenir-Book', 'Avenir Book', 'Avenir', 'Book'),
    ('Avenir-BookOblique', 'Avenir Book Oblique', 'Avenir', 'Book Oblique'),
    ('Avenir-Heavy', 'Avenir Heavy', 'Avenir', 'Heavy'),
    ('Avenir-HeavyOblique', 'Avenir Heavy Oblique', 'Avenir', 'Heavy Oblique'),
    ('Avenir-Light', 'Avenir Light', 'Avenir', 'Light'),
    ('Avenir-LightOblique', 'Avenir Light Oblique', 'Avenir', 'Light Oblique'),
    ('Avenir-Medium', 'Avenir Medium', 'Avenir', 'Medium'),
    ('Avenir-MediumOblique', 'Avenir Medium Oblique', 'Avenir', 'Medium Oblique'),
    ('Avenir-Oblique', 'Avenir Oblique', 'Avenir', 'Oblique'),
    ('Avenir-Roman', 'Avenir Roman', 'Avenir', 'Roman'),
    ('AvenirNext-Bold', 'Avenir Next Bold', 'Avenir Next', 'Bold'),
    ('AvenirNext-BoldItalic', 'Avenir Next Bold Italic', 'Avenir Next', 'Bold Italic'),
    ('AvenirNext-DemiBold', 'Avenir Next Demi Bold', 'Avenir Next', 'Demi Bold'),
    ('AvenirNext-DemiBoldItalic', 'Avenir Next Demi Bold Italic', 'Avenir Next', 'Demi Bold Italic'),
    ('AvenirNext-Heavy', 'Avenir Next Heavy', 'Avenir Next', 'Heavy'),
    ('AvenirNext-HeavyItalic', 'Avenir Next Heavy Italic', 'Avenir Next', 'Heavy Italic'),
    ('AvenirNext-Italic', 'Avenir Next Italic', 'Avenir Next', 'Italic'),
    ('AvenirNext-Medium', 'Avenir Next Medium', 'Avenir Next', 'Medium'),
    ('AvenirNext-MediumItalic', 'Avenir Next Medium Italic', 'Avenir Next', 'Medium Italic'),
    ('AvenirNext-Regular', 'Avenir Next Regular', 'Avenir Next', 'Regular'),
    ('AvenirNext-UltraLightItalic', 'Avenir Next Ultra Light Italic', 'Avenir Next', 'Ultra Light Italic'),
    ('AvenirNext-UltraLight', 'AvenirNext-UltraLight', 'Avenir Next', 'Ultra Light'),
    ('AvenirNextCondensed-Bold', 'Avenir Next Condensed Bold', 'Avenir Next Condensed', 'Bold'),
    ('AvenirNextCondensed-BoldItalic', 'Avenir Next Condensed Bold Italic', 'Avenir Next Condensed', 'Bold Italic'),
    ('AvenirNextCondensed-DemiBold', 'Avenir Next Condensed Demi Bold', 'Avenir Next Condensed', 'Demi Bold'),
    ('AvenirNextCondensed-DemiBoldItalic', 'Avenir Next Condensed Demi Bold Italic', 'Avenir Next Condensed', 'Demi Bold Italic'),
    ('AvenirNextCondensed-Heavy', 'Avenir Next Condensed Heavy', 'Avenir Next Condensed', 'Heavy'),
    ('AvenirNextCondensed-HeavyItalic', 'Avenir Next Condensed Heavy Italic', 'Avenir Next Condensed', 'Heavy Italic'),
    ('AvenirNextCondensed-Italic', 'Avenir Next Condensed Italic', 'Avenir Next Condensed', 'Italic'),
    ('AvenirNextCondensed-Medium', 'Avenir Next Condensed Medium', 'Avenir Next Condensed', 'Medium'),
    ('AvenirNextCondensed-Regular', 'Avenir Next Condensed Regular', 'Avenir Next Condensed', 'Regular'),
    ('AvenirNextCondensed-UltraLight', 'Avenir Next Condensed Ultra Light', 'Avenir Next Condensed', 'Ultra Light'),
    ('AvenirNextCondensed-UltraLightItalic', 'Avenir Next Condensed Ultra Light Italic', 'Avenir Next Condensed', 'Ultra Light Italic'),
    ('AvenirNextCondensed-MediumItalic', 'Avenir Next Medium Condensed Italic', 'Avenir Next Condensed', 'Medium Italic'),
    ('Ayuthaya', 'Ayuthaya', 'Ayuthaya', 'Regular'),
    ('Baghdad', 'Baghdad Regular', 'Baghdad', 'Regular'),
    ('BanglaMN', 'Bangla MN', 'Bangla MN', 'Regular'),
    ('BanglaMN-Bold', 'Bangla MN Bold', 'Bangla MN', 'Bold'),
    ('BanglaSangamMN', 'Bangla Sangam MN', 'Bangla Sangam MN', 'Regular'),
    ('BanglaSangamMN-Bold', 'Bangla Sangam MN Bold', 'Bangla Sangam MN', 'Bold'),
    ('STBaoliSC-Regular', '报隶-简 常规体', 'Baoli SC', 'Regular'),
    ('STBaoliTC-Regular', '报隶-繁 常规体', 'Baoli TC', 'Regular'),
    ('Baskerville', 'Baskerville', 'Baskerville', 'Regular'),
    ('Baskerville-Bold', 'Baskerville Bold', 'Baskerville', 'Bold'),
    ('Baskerville-BoldItalic', 'Baskerville Bold Italic', 'Baskerville', 'Bold Italic'),
    ('Baskerville-Italic', 'Baskerville Italic', 'Baskerville', 'Italic'),
    ('Baskerville-SemiBold', 'Baskerville SemiBold', 'Baskerville', 'SemiBold'),
    ('Baskerville-SemiBoldItalic', 'Baskerville SemiBold Italic', 'Baskerville', 'SemiBold Italic'),
    ('Beirut', 'Beirut Regular', 'Beirut', 'Regular'),
    ('BiauKaiHK-Regular', '標楷體-港澳', 'BiauKaiHK', 'Regular'),
    ('BiauKaiTC-Regular', '標楷體-繁', 'BiauKaiTC', 'Regular'),
    ('BigCaslon-Medium', 'Big Caslon Medium', 'Big Caslon', 'Medium'),
    ('BIZUDGothic-Regular', 'BIZ UDGothic', 'BIZ UDGothic', 'Regular'),
    ('BIZUDGothic-Bold', 'BIZ UDGothic Bold', 'BIZ UDGothic', 'Bold'),
    ('BIZUDMincho-Regular', 'BIZ UDMincho', 'BIZ UDMincho', 'Regular'),
    ('BMDoHyeon-OTF', 'BM DoHyeon OTF', 'BM Dohyeon', 'Regular'),
    ('BMHANNA11yrsoldOTF', 'BM HANNA 11yrs old OTF', 'BM Hanna 11yrs Old', 'Regular'),
    ('BMHANNAAirOTF', 'BM HANNA Air OTF', 'BM Hanna Air', 'Regular'),
    ('BMHANNAProOTF', 'BM HANNA Pro OTF', 'BM Hanna Pro', 'Regular'),
    ('BMJUAOTF', 'BM JUA OTF', 'BM Jua', 'Regular'),
    ('BMKIRANGHAERANG-OTF', 'BM KIRANGHAERANG OTF', 'BM Kirang Haerang', 'Regular'),
    ('BMYEONSUNG-OTF', 'BM YEONSUNG OTF', 'BM Yeonsung', 'Regular'),
    ('BodoniSvtyTwoITCTT-Bold', 'Bodoni 72 Bold', 'Bodoni 72', 'Bold'),
    ('BodoniSvtyTwoITCTT-Book', 'Bodoni 72 Book', 'Bodoni 72', 'Book'),
    ('BodoniSvtyTwoITCTT-BookIta', 'Bodoni 72 Book Italic', 'Bodoni 72', 'Book Italic'),
    ('BodoniSvtyTwoOSITCTT-Bold', 'Bodoni 72 Oldstyle Bold', 'Bodoni 72 Oldstyle', 'Bold'),
    ('BodoniSvtyTwoOSITCTT-Book', 'Bodoni 72 Oldstyle Book', 'Bodoni 72 Oldstyle', 'Book'),
    ('BodoniSvtyTwoOSITCTT-BookIt', 'Bodoni 72 Oldstyle Book Italic', 'Bodoni 72 Oldstyle', 'Book Italic'),
    ('BodoniSvtyTwoSCITCTT-Book', 'Bodoni 72 Smallcaps Book', 'Bodoni 72 Smallcaps', 'Book'),
    ('BodoniOrnamentsITCTT', 'Bodoni Ornaments', 'Bodoni Ornaments', 'Regular'),
    ('BradleyHandITCTT-Bold', 'Bradley Hand Bold', 'Bradley Hand', 'Bold'),
    ('BrushScriptMT', 'Brush Script MT Italic', 'Brush Script MT', 'Italic'),
    ('Chalkboard', 'Chalkboard', 'Chalkboard', 'Regular'),
    ('Chalkboard-Bold', 'Chalkboard Bold', 'Chalkboard', 'Bold'),
    ('ChalkboardSE-Bold', 'Chalkboard SE Bold', 'Chalkboard SE', 'Bold'),
    ('ChalkboardSE-Light', 'Chalkboard SE Light', 'Chalkboard SE', 'Light'),
    ('ChalkboardSE-Regular', 'Chalkboard SE Regular', 'Chalkboard SE', 'Regular'),
    ('Chalkduster', 'Chalkduster', 'Chalkduster', 'Regular'),
    ('Charter-Black', 'Charter Black', 'Charter', 'Black'),
    ('Charter-BlackItalic', 'Charter Black Italic', 'Charter', 'Black Italic'),
    ('Charter-Bold', 'Charter Bold', 'Charter', 'Bold'),
    ('Charter-BoldItalic', 'Charter BT Bold Italic', 'Charter', 'Bold Italic'),
    ('Charter-Italic', 'Charter Italic', 'Charter', 'Italic'),
    ('Charter-Roman', 'Charter Roman', 'Charter', 'Roman'),
    ('Cochin', 'Cochin', 'Cochin', 'Regular'),
    ('Cochin-Bold', 'Cochin Bold', 'Cochin', 'Bold'),
    ('Cochin-BoldItalic', 'Cochin Bold Italic', 'Cochin', 'Bold Italic'),
    ('Cochin-Italic', 'Cochin Italic', 'Cochin', 'Italic'),
    ('ComicSansMS', 'Comic Sans MS', 'Comic Sans MS', 'Regular'),
    ('ComicSansMS-Bold', 'Comic Sans MS Bold', 'Comic Sans MS', 'Bold'),
    ('Copperplate', 'Copperplate', 'Copperplate', 'Regular'),
    ('Copperplate-Bold', 'Copperplate Bold', 'Copperplate', 'Bold'),
    ('Copperplate-Light', 'Copperplate Light', 'Copperplate', 'Light'),
    ('CorsivaHebrew', 'Corsiva Hebrew', 'Corsiva Hebrew', 'Regular'),
    ('CorsivaHebrew-Bold', 'Corsiva Hebrew Bold', 'Corsiva Hebrew', 'Bold'),
    ('CourierNewPSMT', 'Courier New', 'Courier New', 'Regular'),
    ('CourierNewPS-BoldMT', 'Courier New Bold', 'Courier New', 'Bold'),
    ('CourierNewPS-BoldItalicMT', 'Courier New Bold Italic', 'Courier New', 'Bold Italic'),
    ('CourierNewPS-ItalicMT', 'Courier New Italic', 'Courier New', 'Italic'),
    ('DamascusBold', 'Damascus Bold', 'Damascus', 'Bold'),
    ('DamascusLight', 'Damascus Light', 'Damascus', 'Light'),
    ('DamascusMedium', 'Damascus Medium', 'Damascus', 'Medium'),
    ('Damascus', 'Damascus Regular', 'Damascus', 'Regular'),
    ('DamascusSemiBold', 'Damascus Semi Bold', 'Damascus', 'Semi Bold'),
    ('DecoTypeNaskh', 'DecoType Naskh Regular', 'DecoType Naskh', 'Regular'),
    ('DevanagariMT', 'Devanagari MT', 'Devanagari MT', 'Regular'),
    ('DevanagariMT-Bold', 'Devanagari MT Bold', 'Devanagari MT', 'Bold'),
    ('DevanagariSangamMN', 'Devanagari Sangam MN', 'Devanagari Sangam MN', 'Regular'),
    ('DevanagariSangamMN-Bold', 'Devanagari Sangam MN Bold', 'Devanagari Sangam MN', 'Bold'),
    ('Didot', 'Didot', 'Didot', 'Regular'),
    ('Didot-Bold', 'Didot Bold', 'Didot', 'Bold'),
    ('Didot-Italic', 'Didot Italic', 'Didot', 'Italic'),
    ('DINAlternate-Bold', 'DIN Alternate Bold', 'DIN Alternate', 'Bold'),
    ('DINCondensed-Bold', 'DIN Condensed Bold', 'DIN Condensed', 'Bold'),
    ('DiwanKufi', 'Diwan Kufi Regular', 'Diwan Kufi', 'Regular'),
    ('DiwanThuluth', 'Diwan Thuluth Regular', 'Diwan Thuluth', 'Regular'),
    ('EuphemiaUCAS', 'Euphemia UCAS', 'Euphemia UCAS', 'Regular'),
    ('EuphemiaUCAS-Bold', 'Euphemia UCAS Bold', 'Euphemia UCAS', 'Bold'),
    ('EuphemiaUCAS-Italic', 'Euphemia UCAS Italic', 'Euphemia UCAS', 'Italic'),
    ('Farah', 'Farah Regular', 'Farah', 'Regular'),
    ('Farisi', 'Farisi Regular', 'Farisi', 'Regular'),
    ('Futura-Bold', 'Futura Bold', 'Futura', 'Bold'),
    ('Futura-CondensedExtraBold', 'Futura Condensed ExtraBold', 'Futura', 'Condensed ExtraBold'),
    ('Futura-CondensedMedium', 'Futura Condensed Medium', 'Futura', 'Condensed Medium'),
    ('Futura-Medium', 'Futura Medium', 'Futura', 'Medium'),
    ('Futura-MediumItalic', 'Futura Medium Italic', 'Futura', 'Medium Italic'),
    ('Galvji', 'Galvji', 'Galvji', 'Regular'),
    ('Galvji-Oblique', 'Galvji Oblique', 'Galvji', 'Oblique'),
    ('Galvji-Bold', 'Galvji-Bold', 'Galvji', 'Bold'),
    ('Galvji-BoldOblique', 'Galvji-BoldOblique', 'Galvji', 'Bold Oblique'),
    ('GB18030Bitmap', 'GB18030 Bitmap', 'GB18030 Bitmap', 'Regular'),
    ('GeezaPro-Bold', 'Geeza Pro Bold', 'Geeza Pro', 'Bold'),
    ('GeezaPro', 'Geeza Pro Regular', 'Geeza Pro', 'Regular'),
    ('Geneva', 'Geneva', 'Geneva', 'Regular'),
    ('Georgia', 'Georgia', 'Georgia', 'Regular'),
    ('Georgia-Bold', 'Georgia Bold', 'Georgia', 'Bold'),
    ('Georgia-BoldItalic', 'Georgia Bold Italic', 'Georgia', 'Bold Italic'),
    ('Georgia-Italic', 'Georgia Italic', 'Georgia', 'Italic'),
    ('GillSans', 'Gill Sans', 'Gill Sans', 'Regular'),
    ('GillSans-Bold', 'Gill Sans Bold', 'Gill Sans', 'Bold'),
    ('GillSans-BoldItalic', 'Gill Sans Bold Italic', 'Gill Sans', 'Bold Italic'),
    ('GillSans-Italic', 'Gill Sans Italic', 'Gill Sans', 'Italic'),
    ('GillSans-Light', 'Gill Sans Light', 'Gill Sans', 'Light'),
    ('GillSans-LightItalic', 'Gill Sans Light Italic', 'Gill Sans', 'Light Italic'),
    ('GillSans-SemiBold', 'Gill Sans SemiBold', 'Gill Sans', 'SemiBold'),
    ('GillSans-SemiBoldItalic', 'Gill Sans SemiBold Italic', 'Gill Sans', 'SemiBold Italic'),
    ('GillSans-UltraBold', 'Gill Sans UltraBold', 'Gill Sans', 'UltraBold'),
    ('GranthaSangamMN-Bold', 'Grantha Sangam MN Bold', 'Grantha Sangam MN', 'Bold'),
    ('GranthaSangamMN-Regular', 'Grantha Sangam MN Regular', 'Grantha Sangam MN', 'Regular'),
    ('GujaratiMT', 'Gujarati MT', 'Gujarati MT', 'Regular'),
    ('GujaratiMT-Bold', 'Gujarati MT Bold', 'Gujarati MT', 'Bold'),
    ('GujaratiSangamMN', 'Gujarati Sangam MN', 'Gujarati Sangam MN', 'Regular'),
    ('GujaratiSangamMN-Bold', 'Gujarati Sangam MN Bold', 'Gujarati Sangam MN', 'Bold'),
    ('JCkg', 'GungSeo Regular', 'GungSeo', 'Regular'),
    ('GurmukhiMN', 'Gurmukhi MN', 'Gurmukhi MN', 'Regular'),
    ('GurmukhiMN-Bold', 'Gurmukhi MN Bold', 'Gurmukhi MN', 'Bold'),
    ('MonotypeGurmukhi', 'Gurmukhi MT', 'Gurmukhi MT', 'Regular'),
    ('GurmukhiSangamMN', 'Gurmukhi Sangam MN', 'Gurmukhi Sangam MN', 'Regular'),
    ('GurmukhiSangamMN-Bold', 'Gurmukhi Sangam MN Bold', 'Gurmukhi Sangam MN', 'Bold'),
    ('HannotateSC-W5', '手札体-简 常规体', 'Hannotate SC', 'Regular'),
    ('HannotateSC-W7', '手札体-简 粗体', 'Hannotate SC', 'Bold'),
    ('HannotateTC-W5', '手札体-繁 常规体', 'Hannotate TC', 'Regular'),
    ('HannotateTC-W7', '手札体-繁 粗体', 'Hannotate TC', 'Bold'),
    ('HanziPenSC-W3', '翩翩体-简 常规体', 'HanziPen SC', 'Regular'),
    ('HanziPenSC-W5', '翩翩体-简 粗体', 'HanziPen SC', 'Bold'),
    ('HanziPenTC-W3', '翩翩体-繁 常规体', 'HanziPen TC', 'Regular'),
    ('HanziPenTC-W5', '翩翩体-繁 粗体', 'HanziPen TC', 'Bold'),
    ('JCHEadA', 'HeadLineA Regular', 'HeadLineA', 'Regular'),
    ('SIL-Hei-Med-Jian', 'Hei Regular', 'Hei', 'Regular'),
    ('STHeitiSC-Medium', '黑体-简 中等', 'Heiti SC', 'Medium'),
    ('STHeitiSC-Light', '黑体-简 细体', 'Heiti SC', 'Light'),
    ('STHeitiTC-Medium', '黑体-繁 中等', 'Heiti TC', 'Medium'),
    ('STHeitiTC-Light', '黑体-繁 细体', 'Heiti TC', 'Light'),
    ('Helvetica', 'Helvetica', 'Helvetica', 'Regular'),
    ('Helvetica-Bold', 'Helvetica Bold', 'Helvetica', 'Bold'),
    ('Helvetica-BoldOblique', 'Helvetica Bold Oblique', 'Helvetica', 'Bold Oblique'),
    ('Helvetica-Light', 'Helvetica Light', 'Helvetica', 'Light'),
    ('Helvetica-LightOblique', 'Helvetica Light Oblique', 'Helvetica', 'Light Oblique'),
    ('Helvetica-Oblique', 'Helvetica Oblique', 'Helvetica', 'Oblique'),
    ('HelveticaNeue', 'Helvetica Neue', 'Helvetica Neue', 'Regular'),
    ('HelveticaNeue-Bold', 'Helvetica Neue Bold', 'Helvetica Neue', 'Bold'),
    ('HelveticaNeue-BoldItalic', 'Helvetica Neue Bold Italic', 'Helvetica Neue', 'Bold Italic'),
    ('HelveticaNeue-CondensedBlack', 'Helvetica Neue Condensed Black', 'Helvetica Neue', 'Condensed Black'),
    ('HelveticaNeue-CondensedBold', 'Helvetica Neue Condensed Bold', 'Helvetica Neue', 'Condensed Bold'),
    ('HelveticaNeue-Italic', 'Helvetica Neue Italic', 'Helvetica Neue', 'Italic'),
    ('HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', 'Light'),
    ('HelveticaNeue-LightItalic', 'Helvetica Neue Light Italic', 'Helvetica Neue', 'Light Italic'),
    ('HelveticaNeue-Medium', 'Helvetica Neue Medium', 'Helvetica Neue', 'Medium'),
    ('HelveticaNeue-MediumItalic', 'Helvetica Neue Medium Italic', 'Helvetica Neue', 'Medium Italic'),
    ('HelveticaNeue-Thin', 'Helvetica Neue Thin', 'Helvetica Neue', 'Thin'),
    ('HelveticaNeue-ThinItalic', 'Helvetica Neue Thin Italic', 'Helvetica Neue', 'Thin Italic'),
    ('HelveticaNeue-UltraLight', 'Helvetica Neue UltraLight', 'Helvetica Neue', 'UltraLight'),
    ('HelveticaNeue-UltraLightItalic', 'Helvetica Neue UltraLight Italic', 'Helvetica Neue', 'UltraLight Italic'),
    ('Herculanum', 'Herculanum', 'Herculanum', 'Regular'),
    ('HiraMaruProN-W4', 'HiraMaruProN-W4', 'Hiragino Maru Gothic ProN', 'W4'),
    ('HiraMinProN-W3', 'HiraMinProN-W3', 'Hiragino Mincho ProN', 'W3'),
    ('HiraMinProN-W6', 'HiraMinProN-W6', 'Hiragino Mincho ProN', 'W6'),
    ('HiraginoSans-W0', 'Hiragino Sans W0', 'Hiragino Sans', 'W0'),
    ('HiraginoSans-W1', 'Hiragino Sans W1', 'Hiragino Sans', 'W1'),
    ('HiraginoSans-W2', 'Hiragino Sans W2', 'Hiragino Sans', 'W2'),
    ('HiraginoSans-W3', 'Hiragino Sans W3', 'Hiragino Sans', 'W3'),
    ('HiraginoSans-W4', 'Hiragino Sans W4', 'Hiragino Sans', 'W4'),
    ('HiraginoSans-W5', 'Hiragino Sans W5', 'Hiragino Sans', 'W5'),
    ('HiraginoSans-W6', 'Hiragino Sans W6', 'Hiragino Sans', 'W6'),
    ('HiraginoSans-W7', 'Hiragino Sans W7', 'Hiragino Sans', 'W7'),
    ('HiraginoSans-W8', 'Hiragino Sans W8', 'Hiragino Sans', 'W8'),
    ('HiraginoSans-W9', 'Hiragino Sans W9', 'Hiragino Sans', 'W9'),
    ('HiraginoSansGB-W3', '冬青黑体简体中文 W3', 'Hiragino Sans GB', 'W3'),
    ('HiraginoSansGB-W6', '冬青黑体简体中文 W6', 'Hiragino Sans GB', 'W6'),
    ('HoeflerText-Regular', 'Hoefler Text', 'Hoefler Text', 'Regular'),
    ('HoeflerText-Black', 'Hoefler Text Black', 'Hoefler Text', 'Black'),
    ('HoeflerText-BlackItalic', 'Hoefler Text Black Italic', 'Hoefler Text', 'Black Italic'),
    ('HoeflerText-Italic', 'Hoefler Text Italic', 'Hoefler Text', 'Italic'),
    ('HoeflerText-Ornaments', 'Hoefler Text Ornaments', 'Hoefler Text', 'Ornaments'),
    ('Impact', 'Impact', 'Impact', 'Regular'),
    ('InaiMathi', 'InaiMathi', 'InaiMathi', 'Regular'),
    ('InaiMathi-Bold', 'InaiMathi Bold', 'InaiMathi', 'Bold'),
    ('ITFDevanagari-Bold', 'ITFDevanagari-Bold', 'ITF Devanagari', 'Bold'),
    ('ITFDevanagari-Book', 'ITFDevanagari-Book', 'ITF Devanagari', 'Book'),
    ('ITFDevanagari-Demi', 'ITFDevanagari-Demi', 'ITF Devanagari', 'Demi'),
    ('ITFDevanagari-Light', 'ITFDevanagari-Light', 'ITF Devanagari', 'Light'),
    ('ITFDevanagari-Medium', 'ITFDevanagari-Medium', 'ITF Devanagari', 'Medium'),
    ('ITFDevanagariMarathi-Medium', 'ITF Devanagari Marathi Medium', 'ITF Devanagari Marathi', 'Medium'),
    ('ITFDevanagariMarathi-Light', 'ITFDevanagari Marathi Light', 'ITF Devanagari Marathi', 'Light'),
    ('ITFDevanagariMarathi-Bold', 'ITFDevanagari Marathi-Bold', 'ITF Devanagari Marathi', 'Bold'),
    ('ITFDevanagariMarathi-Book', 'ITFDevanagari Marathi-Book', 'ITF Devanagari Marathi', 'Book'),
    ('ITFDevanagariMarathi-Demi', 'ITFDevanagari Marathi-Demi', 'ITF Devanagari Marathi', 'Demi'),
    ('SIL-Kai-Reg-Jian', 'Kai Regular', 'Kai', 'Regular'),
    ('Kailasa-Bold', 'Kailasa Bold', 'Kailasa', 'Bold'),
    ('Kailasa', 'Kailasa Regular', 'Kailasa', 'Regular'),
    ('STKaitiSC-Regular', '楷体-简 常规体', 'Kaiti SC', 'Regular'),
    ('STKaitiSC-Bold', '楷体-简 粗体', 'Kaiti SC', 'Bold'),
    ('STKaitiSC-Black', '楷体-简 黑体', 'Kaiti SC', 'Black'),
    ('STKaitiTC-Regular', '楷体-繁 常规体', 'Kaiti TC', 'Regular'),
    ('STKaitiTC-Bold', '楷体-繁 粗体', 'Kaiti TC', 'Bold'),
    ('STKaitiTC-Black', '楷体-繁 黑体', 'Kaiti TC', 'Black'),
    ('KannadaMN', 'Kannada MN', 'Kannada MN', 'Regular'),
    ('KannadaMN-Bold', 'Kannada MN Bold', 'Kannada MN', 'Bold'),
    ('KannadaSangamMN', 'Kannada Sangam MN', 'Kannada Sangam MN', 'Regular'),
    ('KannadaSangamMN-Bold', 'Kannada Sangam MN Bold', 'Kannada Sangam MN', 'Bold'),
    ('KefaIII-Bold', 'Kefa III Regular', 'Kefa III', 'Bold'),
    ('KefaIII-ExtraBold', 'Kefa III Regular', 'Kefa III', 'ExtraBold'),
    ('KefaIII-Light', 'Kefa III Regular', 'Kefa III', 'Light'),
    ('KefaIII-Regular', 'Kefa III Regular', 'Kefa III', 'Regular'),
    ('KhmerMN', 'Khmer MN', 'Khmer MN', 'Regular'),
    ('KhmerMN-Bold', 'Khmer MN Bold', 'Khmer MN', 'Bold'),
    ('KhmerSangamMN', 'Khmer Sangam MN', 'Khmer Sangam MN', 'Regular'),
    ('Klee-Demibold', 'Klee Demibold', 'Klee', 'Demibold'),
    ('Klee-Medium', 'Klee Medium', 'Klee', 'Medium'),
    ('KohinoorBangla-Regular', 'Kohinoor Bangla', 'Kohinoor Bangla', 'Regular'),
    ('KohinoorBangla-Bold', 'Kohinoor Bangla Bold', 'Kohinoor Bangla', 'Bold'),
    ('KohinoorBangla-Light', 'Kohinoor Bangla Light', 'Kohinoor Bangla', 'Light'),
    ('KohinoorBangla-Medium', 'Kohinoor Bangla Medium', 'Kohinoor Bangla', 'Medium'),
    ('KohinoorBangla-Semibold', 'Kohinoor Bangla Semibold', 'Kohinoor Bangla', 'Semibold'),
    ('KohinoorDevanagari-Bold', 'Kohinoor Devanagari Bold', 'Kohinoor Devanagari', 'Bold'),
    ('KohinoorDevanagari-Light', 'Kohinoor Devanagari Light', 'Kohinoor Devanagari', 'Light'),
    ('KohinoorDevanagari-Medium', 'Kohinoor Devanagari Medium', 'Kohinoor Devanagari', 'Medium'),
    ('KohinoorDevanagari-Regular', 'Kohinoor Devanagari Regular', 'Kohinoor Devanagari', 'Regular'),
    ('KohinoorDevanagari-Semibold', 'Kohinoor Devanagari Semibold', 'Kohinoor Devanagari', 'Semibold'),
    ('KohinoorGujarati-Bold', 'Kohinoor Gujarati Bold', 'Kohinoor Gujarati', 'Bold'),
    ('KohinoorGujarati-Light', 'Kohinoor Gujarati Light', 'Kohinoor Gujarati', 'Light'),
    ('KohinoorGujarati-Medium', 'Kohinoor Gujarati Medium', 'Kohinoor Gujarati', 'Medium'),
    ('KohinoorGujarati-Regular', 'Kohinoor Gujarati Regular', 'Kohinoor Gujarati', 'Regular'),
    ('KohinoorGujarati-Semibold', 'Kohinoor Gujarati Semibold', 'Kohinoor Gujarati', 'Semibold'),
    ('KohinoorTelugu-Regular', 'Kohinoor Telugu', 'Kohinoor Telugu', 'Regular'),
    ('KohinoorTelugu-Bold', 'Kohinoor Telugu Bold', 'Kohinoor Telugu', 'Bold'),
    ('KohinoorTelugu-Light', 'Kohinoor Telugu Light', 'Kohinoor Telugu', 'Light'),
    ('KohinoorTelugu-Medium', 'Kohinoor Telugu Medium', 'Kohinoor Telugu', 'Medium'),
    ('KohinoorTelugu-Semibold', 'Kohinoor Telugu Semibold', 'Kohinoor Telugu', 'Semibold'),
    ('Kokonor', 'Kokonor Regular', 'Kokonor', 'Regular'),
    ('Krungthep', 'Krungthep', 'Krungthep', 'Regular'),
    ('KufiStandardGK', 'KufiStandardGK Regular', 'KufiStandardGK', 'Regular'),
    ('FZLTZHK--GBK1-0', '兰亭黑-简 中黑', 'Lantinghei SC', 'Demibold'),
    ('FZLTTHK--GBK1-0', '兰亭黑-简 特黑', 'Lantinghei SC', 'Heavy'),
    ('FZLTXHK--GBK1-0', '兰亭黑-简 纤黑', 'Lantinghei SC', 'Extralight'),
    ('FZLTZHB--B51-0', '兰亭黑-繁 中黑', 'Lantinghei TC', 'Demibold'),
    ('FZLTTHB--B51-0', '兰亭黑-繁 特黑', 'Lantinghei TC', 'Heavy'),
    ('FZLTXHB--B51-0', '兰亭黑-繁 纤黑', 'Lantinghei TC', 'Extralight'),
    ('LaoMN', 'Lao MN', 'Lao MN', 'Regular'),
    ('LaoMN-Bold', 'Lao MN Bold', 'Lao MN', 'Bold'),
    ('LaoSangamMN', 'Lao Sangam MN', 'Lao Sangam MN', 'Regular'),
    ('STLibianSC-Regular', '隶变-简 常规体', 'Libian SC', 'Regular'),
    ('STLibianTC-Regular', '隶变-繁 常规体', 'Libian TC', 'Regular'),
    ('LiHeiPro', '儷黑 Pro', 'LiHei Pro', 'Medium'),
    ('MLingWaiMedium-SC', '凌慧体-简 中黑体', 'LingWai SC', 'Medium'),
    ('MLingWaiMedium-TC', '凌慧体-繁 中黑体', 'LingWai TC', 'Medium'),
    ('LiSongPro', '儷宋 Pro', 'LiSong Pro', 'Light'),
    ('LucidaGrande', 'Lucida Grande', 'Lucida Grande', 'Regular'),
    ('LucidaGrande-Bold', 'Lucida Grande Bold', 'Lucida Grande', 'Bold'),
    ('Luminari-Regular', 'Luminari', 'Luminari', 'Regular'),
    ('MalayalamMN', 'Malayalam MN', 'Malayalam MN', 'Regular'),
    ('MalayalamMN-Bold', 'Malayalam MN Bold', 'Malayalam MN', 'Bold'),
    ('MalayalamSangamMN', 'Malayalam Sangam MN', 'Malayalam Sangam MN', 'Regular'),
    ('MalayalamSangamMN-Bold', 'Malayalam Sangam MN Bold', 'Malayalam Sangam MN', 'Bold'),
    ('MarkerFelt-Thin', 'Marker Felt Thin', 'Marker Felt', 'Thin'),
    ('MarkerFelt-Wide', 'Marker Felt Wide', 'Marker Felt', 'Wide'),
    ('Menlo-Bold', 'Menlo Bold', 'Menlo', 'Bold'),
    ('Menlo-BoldItalic', 'Menlo Bold Italic', 'Menlo', 'Bold Italic'),
    ('Menlo-Italic', 'Menlo Italic', 'Menlo', 'Italic'),
    ('Menlo-Regular', 'Menlo Regular', 'Menlo', 'Regular'),
    ('MicrosoftSansSerif', 'Microsoft Sans Serif', 'Microsoft Sans Serif', 'Regular'),
    ('DiwanMishafi', 'Mishafi Regular', 'Mishafi', 'Regular'),
    ('DiwanMishafiGold', 'Mishafi Gold Regular', 'Mishafi Gold', 'Regular'),
    ('Monaco', 'Monaco', 'Monaco', 'Regular'),
    ('Mshtakan', 'Mshtakan', 'Mshtakan', 'Regular'),
    ('MshtakanBold', 'Mshtakan Bold', 'Mshtakan', 'Bold'),
    ('MshtakanBoldOblique', 'Mshtakan BoldOblique', 'Mshtakan', 'BoldOblique'),
    ('MshtakanOblique', 'Mshtakan Oblique', 'Mshtakan', 'Oblique'),
    ('MuktaMahee-Bold', 'MuktaMahee Bold', 'Mukta Mahee', 'Bold'),
    ('MuktaMahee-ExtraBold', 'MuktaMahee ExtraBold', 'Mukta Mahee', 'ExtraBold'),
    ('MuktaMahee-ExtraLight', 'MuktaMahee ExtraLight', 'Mukta Mahee', 'ExtraLight'),
    ('MuktaMahee-Light', 'MuktaMahee Light', 'Mukta Mahee', 'Light'),
    ('MuktaMahee-Medium', 'MuktaMahee Medium', 'Mukta Mahee', 'Medium'),
    ('MuktaMahee-Regular', 'MuktaMahee Regular', 'Mukta Mahee', 'Regular'),
    ('MuktaMahee-SemiBold', 'MuktaMahee SemiBold', 'Mukta Mahee', 'SemiBold'),
    ('MunaBlack', 'Muna Black', 'Muna', 'Black'),
    ('MunaBold', 'Muna Bold', 'Muna', 'Bold'),
    ('Muna', 'Muna Regular', 'Muna', 'Regular'),
    ('MyanmarMN', 'Myanmar MN', 'Myanmar MN', 'Regular'),
    ('MyanmarMN-Bold', 'Myanmar MN Bold', 'Myanmar MN', 'Bold'),
    ('MyanmarSangamMN', 'Myanmar Sangam MN', 'Myanmar Sangam MN', 'Regular'),
    ('MyanmarSangamMN-Bold', 'Myanmar Sangam MN Bold', 'Myanmar Sangam MN', 'Bold'),
    ('Nadeem', 'Nadeem Regular', 'Nadeem', 'Regular'),
    ('NanumBrush', 'Nanum Brush Script', 'Nanum Brush Script', 'Regular'),
    ('NanumGothic', 'NanumGothic', 'Nanum Gothic', 'Regular'),
    ('NanumGothicBold', 'NanumGothic Bold', 'Nanum Gothic', 'Bold'),
    ('NanumGothicExtraBold', 'NanumGothic ExtraBold', 'Nanum Gothic', 'ExtraBold'),
    ('NanumMyeongjo', 'NanumMyeongjo', 'Nanum Myeongjo', 'Regular'),
    ('NanumMyeongjoBold', 'NanumMyeongjoBold', 'Nanum Myeongjo', 'Bold'),
    ('NanumMyeongjoExtraBold', 'NanumMyeongjoExtraBold', 'Nanum Myeongjo', 'ExtraBold'),
    ('NanumPen', 'Nanum Pen Script', 'Nanum Pen Script', 'Regular'),
    ('NewPeninimMT', 'New Peninim MT', 'New Peninim MT', 'Regular'),
    ('NewPeninimMT-Bold', 'New Peninim MT Bold', 'New Peninim MT', 'Bold'),
    ('NewPeninimMT-BoldInclined', 'New Peninim MT Bold Inclined', 'New Peninim MT', 'Bold Inclined'),
    ('NewPeninimMT-Inclined', 'New Peninim MT Inclined', 'New Peninim MT', 'Inclined'),
    ('Noteworthy-Bold', 'Noteworthy Bold', 'Noteworthy', 'Bold'),
    ('Noteworthy-Light', 'Noteworthy Light', 'Noteworthy', 'Light'),
    ('NotoNastaliqUrdu', 'Noto Nastaliq Urdu', 'Noto Nastaliq Urdu', 'Regular'),
    ('NotoNastaliqUrdu-Bold', 'Noto Nastaliq Urdu Bold', 'Noto Nastaliq Urdu', 'Bold'),
    ('NotoSansBatak-Regular', 'Noto Sans Batak Regular', 'Noto Sans Batak', 'Regular'),
    ('NotoSansKannada-Black', 'Noto Sans Kannada Black', 'Noto Sans Kannada', 'Black'),
    ('NotoSansKannada-Bold', 'Noto Sans Kannada Bold', 'Noto Sans Kannada', 'Bold'),
    ('NotoSansKannada-ExtraBold', 'Noto Sans Kannada ExtraBold', 'Noto Sans Kannada', 'ExtraBold'),
    ('NotoSansKannada-ExtraLight', 'Noto Sans Kannada ExtraLight', 'Noto Sans Kannada', 'ExtraLight'),
    ('NotoSansKannada-Light', 'Noto Sans Kannada Light', 'Noto Sans Kannada', 'Light'),
    ('NotoSansKannada-Medium', 'Noto Sans Kannada Medium', 'Noto Sans Kannada', 'Medium'),
    ('NotoSansKannada-Regular', 'Noto Sans Kannada Regular', 'Noto Sans Kannada', 'Regular'),
    ('NotoSansKannada-SemiBold', 'Noto Sans Kannada SemiBold', 'Noto Sans Kannada', 'SemiBold'),
    ('NotoSansKannada-Thin', 'Noto Sans Kannada Thin', 'Noto Sans Kannada', 'Thin'),
    ('NotoSansMyanmar-Black', 'Noto Sans Myanmar Black', 'Noto Sans Myanmar', 'Black'),
    ('NotoSansMyanmar-Bold', 'Noto Sans Myanmar Bold', 'Noto Sans Myanmar', 'Bold'),
    ('NotoSansMyanmar-ExtraBold', 'Noto Sans Myanmar ExtraBold', 'Noto Sans Myanmar', 'ExtraBold'),
    ('NotoSansMyanmar-ExtraLight', 'Noto Sans Myanmar ExtraLight', 'Noto Sans Myanmar', 'ExtraLight'),
    ('NotoSansMyanmar-Light', 'Noto Sans Myanmar Light', 'Noto Sans Myanmar', 'Light'),
    ('NotoSansMyanmar-Medium', 'Noto Sans Myanmar Medium', 'Noto Sans Myanmar', 'Medium'),
    ('NotoSansMyanmar-Regular', 'Noto Sans Myanmar Regular', 'Noto Sans Myanmar', 'Regular'),
    ('NotoSansMyanmar-SemiBold', 'Noto Sans Myanmar SemiBold', 'Noto Sans Myanmar', 'SemiBold'),
    ('NotoSansMyanmar-Thin', 'Noto Sans Myanmar Thin', 'Noto Sans Myanmar', 'Thin'),
    ('NotoSansNKo-Regular', 'Noto Sans NKo Regular', 'Noto Sans NKo', 'Regular'),
    ('NotoSansOriya', 'Noto Sans Oriya', 'Noto Sans Oriya', 'Regular'),
    ('NotoSansOriya-Bold', 'Noto Sans Oriya Bold', 'Noto Sans Oriya', 'Bold'),
    ('NotoSansSyriac-Regular', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'Regular'),
    ('NotoSansSyriac-Regular_Black', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'Black'),
    ('NotoSansSyriac-Regular_Bold', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'Bold'),
    ('NotoSansSyriac-Regular_ExtraBold', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'ExtraBold'),
    ('NotoSansSyriac-Regular_ExtraLight', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'ExtraLight'),
    ('NotoSansSyriac-Regular_Light', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'Light'),
    ('NotoSansSyriac-Regular_Medium', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'Medium'),
    ('NotoSansSyriac-Regular_SemiBold', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'SemiBold'),
    ('NotoSansSyriac-Regular_Thin', 'Noto Sans Syriac Regular', 'Noto Sans Syriac', 'Thin'),
    ('NotoSansTagalog-Regular', 'Noto Sans Tagalog Regular', 'Noto Sans Tagalog', 'Regular'),
    ('NotoSerifMyanmar-Black', 'Noto Serif Myanmar Black', 'Noto Serif Myanmar', 'Black'),
    ('NotoSerifMyanmar-Bold', 'Noto Serif Myanmar Bold', 'Noto Serif Myanmar', 'Bold'),
    ('NotoSerifMyanmar-ExtraBold', 'Noto Serif Myanmar ExtraBold', 'Noto Serif Myanmar', 'ExtraBold'),
    ('NotoSerifMyanmar-ExtraLight', 'Noto Serif Myanmar ExtraLight', 'Noto Serif Myanmar', 'ExtraLight'),
    ('NotoSerifMyanmar-Light', 'Noto Serif Myanmar Light', 'Noto Serif Myanmar', 'Light'),
    ('NotoSerifMyanmar-Medium', 'Noto Serif Myanmar Medium', 'Noto Serif Myanmar', 'Medium'),
    ('NotoSerifMyanmar-Regular', 'Noto Serif Myanmar Regular', 'Noto Serif Myanmar', 'Regular'),
    ('NotoSerifMyanmar-SemiBold', 'Noto Serif Myanmar SemiBold', 'Noto Serif Myanmar', 'SemiBold'),
    ('NotoSerifMyanmar-Thin', 'Noto Serif Myanmar Thin', 'Noto Serif Myanmar', 'Thin'),
    ('Optima-Bold', 'Optima Bold', 'Optima', 'Bold'),
    ('Optima-BoldItalic', 'Optima Bold Italic', 'Optima', 'Bold Italic'),
    ('Optima-ExtraBlack', 'Optima ExtraBlack', 'Optima', 'ExtraBlack'),
    ('Optima-Italic', 'Optima Italic', 'Optima', 'Italic'),
    ('Optima-Regular', 'Optima Regular', 'Optima', 'Regular'),
    ('OriyaMN', 'Oriya MN', 'Oriya MN', 'Regular'),
    ('OriyaMN-Bold', 'Oriya MN Bold', 'Oriya MN', 'Bold'),
    ('OriyaSangamMN', 'Oriya Sangam MN', 'Oriya Sangam MN', 'Regular'),
    ('OriyaSangamMN-Bold', 'Oriya Sangam MN Bold', 'Oriya Sangam MN', 'Bold'),
    ('Osaka', 'Osaka', 'Osaka', 'Regular'),
    ('Osaka-Mono', 'Osaka-Mono', 'Osaka', 'Regular-Mono'),
    ('Palatino-Roman', 'Palatino', 'Palatino', 'Regular'),
    ('Palatino-Bold', 'Palatino Bold', 'Palatino', 'Bold'),
    ('Palatino-BoldItalic', 'Palatino Bold Italic', 'Palatino', 'Bold Italic'),
    ('Palatino-Italic', 'Palatino Italic', 'Palatino', 'Italic'),
    ('Papyrus', 'Papyrus', 'Papyrus', 'Regular'),
    ('Papyrus-Condensed', 'Papyrus Condensed', 'Papyrus', 'Condensed'),
    ('PartyLetPlain', 'Party LET Plain', 'Party LET', 'Plain'),
    ('JCsmPC', 'PCMyungjo Regular', 'PCMyungjo', 'Regular'),
    ('Phosphate-Inline', 'Phosphate Inline', 'Phosphate', 'Inline'),
    ('Phosphate-Solid', 'Phosphate Solid', 'Phosphate', 'Solid'),
    ('JCfg', 'PilGi Regular', 'PilGi', 'Regular'),
    ('PingFangHK-Semibold', '苹方-港 中粗体', 'PingFang HK', 'Semibold'),
    ('PingFangHK-Medium', '苹方-港 中黑体', 'PingFang HK', 'Medium'),
    ('PingFangHK-Regular', '苹方-港 常规体', 'PingFang HK', 'Regular'),
    ('PingFangHK-Ultralight', '苹方-港 极细体', 'PingFang HK', 'Ultralight'),
    ('PingFangHK-Thin', '苹方-港 纤细体', 'PingFang HK', 'Thin'),
    ('PingFangHK-Light', '苹方-港 细体', 'PingFang HK', 'Light'),
    ('PingFangMO-Semibold', '苹方-澳 中粗体', 'PingFang MO', 'Semibold'),
    ('PingFangMO-Medium', '苹方-澳 中黑体', 'PingFang MO', 'Medium'),
    ('PingFangMO-Regular', '苹方-澳 常规体', 'PingFang MO', 'Regular'),
    ('PingFangMO-Ultralight', '苹方-澳 极细体', 'PingFang MO', 'Ultralight'),
    ('PingFangMO-Thin', '苹方-澳 纤细体', 'PingFang MO', 'Thin'),
    ('PingFangMO-Light', '苹方-澳 细体', 'PingFang MO', 'Light'),
    ('PingFangSC-Semibold', '苹方-简 中粗体', 'PingFang SC', 'Semibold'),
    ('PingFangSC-Medium', '苹方-简 中黑体', 'PingFang SC', 'Medium'),
    ('PingFangSC-Regular', '苹方-简 常规体', 'PingFang SC', 'Regular'),
    ('PingFangSC-Ultralight', '苹方-简 极细体', 'PingFang SC', 'Ultralight'),
    ('PingFangSC-Thin', '苹方-简 纤细体', 'PingFang SC', 'Thin'),
    ('PingFangSC-Light', '苹方-简 细体', 'PingFang SC', 'Light'),
    ('PingFangTC-Semibold', '苹方-繁 中粗体', 'PingFang TC', 'Semibold'),
    ('PingFangTC-Medium', '苹方-繁 中黑体', 'PingFang TC', 'Medium'),
    ('PingFangTC-Regular', '苹方-繁 常规体', 'PingFang TC', 'Regular'),
    ('PingFangTC-Ultralight', '苹方-繁 极细体', 'PingFang TC', 'Ultralight'),
    ('PingFangTC-Thin', '苹方-繁 纤细体', 'PingFang TC', 'Thin'),
    ('PingFangTC-Light', '苹方-繁 细体', 'PingFang TC', 'Light'),
    ('PlantagenetCherokee', 'Plantagenet Cherokee', 'Plantagenet Cherokee', 'Regular'),
    ('PTMono-Regular', 'PT Mono', 'PT Mono', 'Regular'),
    ('PTMono-Bold', 'PT Mono Bold', 'PT Mono', 'Bold'),
    ('PTSans-Regular', 'PT Sans', 'PT Sans', 'Regular'),
    ('PTSans-Bold', 'PT Sans Bold', 'PT Sans', 'Bold'),
    ('PTSans-BoldItalic', 'PT Sans Bold Italic', 'PT Sans', 'Bold Italic'),
    ('PTSans-Italic', 'PT Sans Italic', 'PT Sans', 'Italic'),
    ('PTSans-Caption', 'PT Sans Caption', 'PT Sans Caption', 'Regular'),
    ('PTSans-CaptionBold', 'PT Sans Caption Bold', 'PT Sans Caption', 'Bold'),
    ('PTSans-Narrow', 'PT Sans Narrow', 'PT Sans Narrow', 'Regular'),
    ('PTSans-NarrowBold', 'PT Sans Narrow Bold', 'PT Sans Narrow', 'Bold'),
    ('PTSerif-Regular', 'PT Serif', 'PT Serif', 'Regular'),
    ('PTSerif-Bold', 'PT Serif Bold', 'PT Serif', 'Bold'),
    ('PTSerif-BoldItalic', 'PT Serif Bold Italic', 'PT Serif', 'Bold Italic'),
    ('PTSerif-Italic', 'PT Serif Italic', 'PT Serif', 'Italic'),
    ('PTSerif-Caption', 'PT Serif Caption', 'PT Serif Caption', 'Regular'),
    ('PTSerif-CaptionItalic', 'PT Serif Caption Italic', 'PT Serif Caption', 'Italic'),
    ('Raanana', 'Raanana', 'Raanana', 'Regular'),
    ('RaananaBold', 'Raanana Bold', 'Raanana', 'Bold'),
    ('Rockwell-Regular', 'Rockwell', 'Rockwell', 'Regular'),
    ('Rockwell-BoldItalic', 'Rockwell Bold Italic', 'Rockwell', 'Bold Italic'),
    ('Rockwell-Italic', 'Rockwell Italic', 'Rockwell', 'Italic'),
    ('Rockwell-Bold', 'Rockwell-Bold', 'Rockwell', 'Bold'),
    ('Sana', 'Sana Regular', 'Sana', 'Regular'),
    ('Sathu', 'Sathu', 'Sathu', 'Regular'),
    ('SavoyeLetPlain', 'Savoye LET Plain:1.0', 'Savoye LET', 'Plain'),
    ('ShreeDev0714', 'Shree Devanagari 714', 'Shree Devanagari 714', 'Regular'),
    ('ShreeDev0714-Bold', 'Shree Devanagari 714 Bold', 'Shree Devanagari 714', 'Bold'),
    ('ShreeDev0714-BoldItalic', 'Shree Devanagari 714 Bold Italic', 'Shree Devanagari 714', 'Bold Italic'),
    ('ShreeDev0714-Italic', 'Shree Devanagari 714 Italic', 'Shree Devanagari 714', 'Italic'),
    ('SignPainter-HouseScript', 'SignPainter-HouseScript', 'SignPainter', 'HouseScript'),
    ('SignPainter-HouseScriptSemibold', 'SignPainter-HouseScript Semibold', 'SignPainter', 'HouseScript Semibold'),
    ('Silom', 'Silom', 'Silom', 'Regular'),
    ('SimSong-Regular', '简宋 常规体', 'SimSong', 'Regular'),
    ('SimSong-Bold', '简宋 粗体', 'SimSong', 'Bold'),
    ('SinhalaMN', 'Sinhala MN', 'Sinhala MN', 'Regular'),
    ('SinhalaMN-Bold', 'Sinhala MN Bold', 'Sinhala MN', 'Bold'),
    ('SinhalaSangamMN', 'Sinhala Sangam MN', 'Sinhala Sangam MN', 'Regular'),
    ('SinhalaSangamMN-Bold', 'Sinhala Sangam MN Bold', 'Sinhala Sangam MN', 'Bold'),
    ('Skia-Regular', 'Skia', 'Skia', 'Regular'),
    ('Skia-Regular_Black', 'Skia', 'Skia', 'Black'),
    ('Skia-Regular_Black-Condensed', 'Skia', 'Skia', 'Black Condensed'),
    ('Skia-Regular_Black-Extended', 'Skia', 'Skia', 'Black Extended'),
    ('Skia-Regular_Bold', 'Skia', 'Skia', 'Bold'),
    ('Skia-Regular_Condensed', 'Skia', 'Skia', 'Condensed'),
    ('Skia-Regular_Extended', 'Skia', 'Skia', 'Extended'),
    ('Skia-Regular_Light', 'Skia', 'Skia', 'Light'),
    ('Skia-Regular_Light-Condensed', 'Skia', 'Skia', 'Light Condensed'),
    ('Skia-Regular_Light-Extended', 'Skia', 'Skia', 'Light Extended'),
    ('SnellRoundhand', 'Snell Roundhand', 'Snell Roundhand', 'Regular'),
    ('SnellRoundhand-Black', 'Snell Roundhand Black', 'Snell Roundhand', 'Black'),
    ('SnellRoundhand-Bold', 'Snell Roundhand Bold', 'Snell Roundhand', 'Bold'),
    ('STSongti-SC-Regular', '宋体-简 常规体', 'Songti SC', 'Regular'),
    ('STSongti-SC-Bold', '宋体-简 粗体', 'Songti SC', 'Bold'),
    ('STSongti-SC-Light', '宋体-简 细体', 'Songti SC', 'Light'),
    ('STSongti-SC-Black', '宋体-简 黑体', 'Songti SC', 'Black'),
    ('STSongti-TC-Regular', '宋体-繁 常规体', 'Songti TC', 'Regular'),
    ('STSongti-TC-Bold', '宋体-繁 粗体', 'Songti TC', 'Bold'),
    ('STSongti-TC-Light', '宋体-繁 细体', 'Songti TC', 'Light'),
    ('STFangsong', '华文仿宋', 'STFangsong', 'Regular'),
    ('STXihei', '华文细黑', 'STHeiti', 'Light'),
    ('STHeiti', '华文黑体', 'STHeiti', 'Regular'),
    ('STIXTwoMath-Regular', 'STIX Two Math Regular', 'STIX Two Math', 'Regular'),
    ('STIXTwoText', 'STIX Two Text', 'STIX Two Text', 'Regular'),
    ('STIXTwoText_Bold', 'STIX Two Text', 'STIX Two Text', 'Bold'),
    ('STIXTwoText_Medium', 'STIX Two Text', 'STIX Two Text', 'Medium'),
    ('STIXTwoText_SemiBold', 'STIX Two Text', 'STIX Two Text', 'SemiBold'),
    ('STIXTwoText-Italic', 'STIX Two Text Italic', 'STIX Two Text', 'Italic'),
    ('STIXTwoText-Italic_Bold-Italic', 'STIX Two Text Italic', 'STIX Two Text', 'Bold Italic'),
    ('STIXTwoText-Italic_Medium-Italic', 'STIX Two Text Italic', 'STIX Two Text', 'Medium Italic'),
    ('STIXTwoText-Italic_SemiBold-Italic', 'STIX Two Text Italic', 'STIX Two Text', 'SemiBold Italic'),
    ('STKaiti', '华文楷体', 'STKaiti', 'Regular'),
    ('STSong', '华文宋体', 'STSong', 'Regular'),
    ('SukhumvitSet-Bold', 'SukhumvitSet-Bold', 'Sukhumvit Set', 'Bold'),
    ('SukhumvitSet-Light', 'SukhumvitSet-Light', 'Sukhumvit Set', 'Light'),
    ('SukhumvitSet-Medium', 'SukhumvitSet-Medium', 'Sukhumvit Set', 'Medium'),
    ('SukhumvitSet-SemiBold', 'SukhumvitSet-SemiBold', 'Sukhumvit Set', 'Semi Bold'),
    ('SukhumvitSet-Text', 'SukhumvitSet-Text', 'Sukhumvit Set', 'Text'),
    ('SukhumvitSet-Thin', 'SukhumvitSet-Thin', 'Sukhumvit Set', 'Thin'),
    ('Symbol', 'Symbol', 'Symbol', 'Regular'),
    ('Tahoma', 'Tahoma', 'Tahoma', 'Regular'),
    ('Tahoma-Bold', 'Tahoma Bold', 'Tahoma', 'Bold'),
    ('TamilMN', 'Tamil MN', 'Tamil MN', 'Regular'),
    ('TamilMN-Bold', 'Tamil MN Bold', 'Tamil MN', 'Bold'),
    ('TamilSangamMN', 'Tamil Sangam MN', 'Tamil Sangam MN', 'Regular'),
    ('TamilSangamMN-Bold', 'Tamil Sangam MN Bold', 'Tamil Sangam MN', 'Bold'),
    ('TeluguMN', 'Telugu MN', 'Telugu MN', 'Regular'),
    ('TeluguMN-Bold', 'Telugu MN Bold', 'Telugu MN', 'Bold'),
    ('TeluguSangamMN', 'Telugu Sangam MN', 'Telugu Sangam MN', 'Regular'),
    ('TeluguSangamMN-Bold', 'Telugu Sangam MN Bold', 'Telugu Sangam MN', 'Bold'),
    ('Thonburi', 'Thonburi', 'Thonburi', 'Regular'),
    ('Thonburi-Bold', 'Thonburi Bold', 'Thonburi', 'Bold'),
    ('Thonburi-Light', 'Thonburi Light', 'Thonburi', 'Light'),
    ('TimesNewRomanPSMT', 'Times New Roman', 'Times New Roman', 'Regular'),
    ('TimesNewRomanPS-BoldMT', 'Times New Roman Bold', 'Times New Roman', 'Bold'),
    ('TimesNewRomanPS-BoldItalicMT', 'Times New Roman Bold Italic', 'Times New Roman', 'Bold Italic'),
    ('TimesNewRomanPS-ItalicMT', 'Times New Roman Italic', 'Times New Roman', 'Italic'),
    ('ToppanBunkyuGothicPr6N-DB', 'Toppan Bunkyu Gothic Demibold', 'Toppan Bunkyu Gothic', 'Demibold'),
    ('ToppanBunkyuGothicPr6N-Regular', 'Toppan Bunkyu Gothic Regular', 'Toppan Bunkyu Gothic', 'Regular'),
    ('ToppanBunkyuMidashiGothicStdN-ExtraBold', 'Toppan Bunkyu Midashi Gothic Extrabold', 'Toppan Bunkyu Midashi Gothic', 'Extrabold'),
    ('ToppanBunkyuMidashiMinchoStdN-ExtraBold', 'Toppan Bunkyu Midashi Mincho Extrabold', 'Toppan Bunkyu Midashi Mincho', 'Extrabold'),
    ('ToppanBunkyuMinchoPr6N-Regular', 'Toppan Bunkyu Mincho Regular', 'Toppan Bunkyu Mincho', 'Regular'),
    ('Trattatello', 'Trattatello', 'Trattatello', 'Regular'),
    ('TrebuchetMS', 'Trebuchet MS', 'Trebuchet MS', 'Regular'),
    ('TrebuchetMS-Bold', 'Trebuchet MS Bold', 'Trebuchet MS', 'Bold'),
    ('Trebuchet-BoldItalic', 'Trebuchet MS Bold Italic', 'Trebuchet MS', 'Bold Italic'),
    ('TrebuchetMS-Italic', 'Trebuchet MS Italic', 'Trebuchet MS', 'Italic'),
    ('TsukuARdGothic-Bold', 'Tsukushi A Round Gothic Bold', 'Tsukushi A Round Gothic', 'Bold'),
    ('TsukuARdGothic-Regular', 'Tsukushi A Round Gothic Regular', 'Tsukushi A Round Gothic', 'Regular'),
    ('TsukuBRdGothic-Bold', 'Tsukushi B Round Gothic Bold', 'Tsukushi B Round Gothic', 'Bold'),
    ('TsukuBRdGothic-Regular', 'Tsukushi B Round Gothic Regula', 'Tsukushi B Round Gothic', 'Regular'),
    ('Verdana', 'Verdana', 'Verdana', 'Regular'),
    ('Verdana-Bold', 'Verdana Bold', 'Verdana', 'Bold'),
    ('Verdana-BoldItalic', 'Verdana Bold Italic', 'Verdana', 'Bold Italic'),
    ('Verdana-Italic', 'Verdana Italic', 'Verdana', 'Italic'),
    ('WaseemLight', 'Waseem Light', 'Waseem', 'Light'),
    ('Waseem', 'Waseem Regular', 'Waseem', 'Regular'),
    ('DFWaWaSC-W5', '娃娃体-简 常规体', 'Wawati SC', 'Regular'),
    ('DFWaWaTC-W5', '娃娃体-繁 常规体', 'Wawati TC', 'Regular'),
    ('Webdings', 'Webdings', 'Webdings', 'Regular'),
    ('WeibeiSC-Bold', '魏碑-简 粗体', 'Weibei SC', 'Bold'),
    ('WeibeiTC-Bold', '魏碑-繁 粗体', 'Weibei TC', 'Bold'),
    ('Wingdings-Regular', 'Wingdings', 'Wingdings', 'Regular'),
    ('Wingdings2', 'Wingdings 2', 'Wingdings 2', 'Regular'),
    ('Wingdings3', 'Wingdings 3', 'Wingdings 3', 'Regular'),
    ('STXingkaiSC-Bold', '行楷-简 粗体', 'Xingkai SC', 'Bold'),
    ('STXingkaiSC-Light', '行楷-简 细体', 'Xingkai SC', 'Light'),
    ('STXingkaiTC-Bold', '行楷-繁 粗体', 'Xingkai TC', 'Bold'),
    ('STXingkaiTC-Light', '行楷-繁 细体', 'Xingkai TC', 'Light'),
    ('STYuanti-SC-Regular', '圆体-简 常规体', 'Yuanti SC', 'Regular'),
    ('STYuanti-SC-Bold', '圆体-简 粗体', 'Yuanti SC', 'Bold'),
    ('STYuanti-SC-Light', '圆体-简 细体', 'Yuanti SC', 'Light'),
    ('STYuanti-TC-Regular', '圆体-繁 常规体', 'Yuanti TC', 'Regular'),
    ('STYuanti-TC-Bold', '圆体-繁 粗体', 'Yuanti TC', 'Bold'),
    ('STYuanti-TC-Light', '圆体-繁 细体', 'Yuanti TC', 'Light'),
    ('YuGo-Bold', 'YuGothic Bold', 'YuGothic', 'Bold'),
    ('YuGo-Medium', 'YuGothic Medium', 'YuGothic', 'Medium'),
    ('YuKyo-Bold', 'YuKyokasho Bold', 'YuKyokasho', 'Bold'),
    ('YuKyo-Medium', 'YuKyokasho Medium', 'YuKyokasho', 'Medium'),
    ('YuKyo_Yoko-Bold', 'YuKyokasho Yoko Bold', 'YuKyokasho Yoko', 'Bold'),
    ('YuKyo_Yoko-Medium', 'YuKyokasho Yoko Medium', 'YuKyokasho Yoko', 'Medium'),
    ('YuMin-Demibold', 'YuMincho Demibold', 'YuMincho', 'Demibold'),
    ('YuMin-Extrabold', 'YuMincho Extrabold', 'YuMincho', 'Extrabold'),
    ('YuMin-Medium', 'YuMincho Medium', 'YuMincho', 'Medium'),
    ('YuMin_36pKn-Demibold', 'YuMincho +36p Kana Demibold', 'YuMincho +36p Kana', 'Demibold'),
    ('YuMin_36pKn-Extrabold', 'YuMincho +36p Kana Extrabold', 'YuMincho +36p Kana', 'Extrabold'),
    ('YuMin_36pKn-Medium', 'YuMincho +36p Kana Medium', 'YuMincho +36p Kana', 'Medium'),
    ('YuppySC-Regular', '雅痞-简 常规体', 'Yuppy SC', 'Regular'),
    ('YuppyTC-Regular', '雅痞-繁 常规体', 'Yuppy TC', 'Regular'),
    ('ZapfDingbatsITC', 'Zapf Dingbats', 'Zapf Dingbats', 'Regular'),
    ('Zapfino', 'Zapfino', 'Zapfino', 'Regular'),
)

MACOS_TAHOE_FONT_METRICS: tuple[tuple, ...] = (
    ('Al Bayan', 0.936332874056, False),
    ('Al Nile', 0.871846447103, False),
    ('American Typewriter', 1.005905795861, False),
    ('Andale Mono', 1.2712890625, True),
    ('Apple Braille', 0.926426007533, False),
    ('Apple Chancery', 0.86601459899, False),
    ('Apple Color Emoji', 1.0940498673, False),
    ('Apple SD Gothic Neo', 0.861775843635, False),
    ('Apple Symbols', 0.750565988438, False),
    ('AppleGothic', 1.031236115394, False),
    ('AppleMyungjo', 1.002187248233, False),
    ('Arial', 0.902869475965, False),
    ('Arial Black', 1.054556215212, False),
    ('Arial Hebrew', 0.871129569832, False),
    ('Arial Narrow', 0.765001231976, False),
    ('Arial Rounded MT Bold', 0.959076913849, False),
    ('Avenir', 0.897449835178, False),
    ('Avenir Next', 0.929505234449, False),
    ('Ayuthaya', 0.976131138213, False),
    ('Baskerville', 0.870231823719, False),
    ('Big Caslon', 0.846482037411, False),
    ('BlinkMacSystemFont', 0.883691938218, False),
    ('Brush Script MT', 0.745565326705, False),
    ('Chalkboard', 0.875249096447, False),
    ('Chalkboard SE', 0.882001263103, False),
    ('Chalkduster', 1.092260278633, False),
    ('Charter', 0.937124008839, False),
    ('Cochin', 0.884102004056, False),
    ('Comic Sans MS', 0.919304984196, False),
    ('Copperplate', 0.93005148729, False),
    ('Corsiva Hebrew', 0.825425084295, False),
    ('Courier', 1.2712890625, True),
    ('Courier New', 1.2712890625, True),
    ('Damascus', 0.922847640493, False),
    ('Devanagari MT', 0.927255226059, False),
    ('Devanagari Sangam MN', 0.86321422842, False),
    ('Didot', 0.910012550832, False),
    ('DIN Alternate', 0.854396394896, False),
    ('DIN Condensed', 0.66746320911, False),
    ('Futura', 0.931439923336, False),
    ('Galvji', 0.984263580113, False),
    ('Geneva', 0.996715227829, False),
    ('Georgia', 0.940941180629, False),
    ('Gill Sans', 0.848128898857, False),
    ('Heiti SC', 0.95514282844, False),
    ('Heiti TC', 0.95514282844, False),
    ('Helvetica', 0.902869475965, False),
    ('Helvetica Neue', 0.903287471093, False),
    ('Hiragino Maru Gothic ProN', 0.984945151786, False),
    ('Hiragino Mincho ProN', 0.961287623057, False),
    ('Hiragino Sans', 1.011197236814, False),
    ('Hiragino Sans GB', 0.988939314589, False),
    ('Hoefler Text', 0.870941755626, False),
    ('Impact', 0.836927416574, False),
    ('InaiMathi', 0.791554167, False),
    ('Kaiti SC', 0.852524387916, False),
    ('Kaiti TC', 0.852524387916, False),
    ('Lucida Grande', 0.970695117943, False),
    ('Luminari', 0.921585378551, False),
    ('Marker Felt', 0.857645088682, False),
    ('Menlo', 1.274848090278, True),
    ('Microsoft Sans Serif', 0.903052833562, False),
    ('Monaco', 1.2712890625, True),
    ('Noteworthy', 0.82519704486, False),
    ('Optima', 0.908510500215, False),
    ('Palatino', 0.9067199855, False),
    ('Papyrus', 0.839261058717, False),
    ('Phosphate', 0.851875806719, False),
    ('PingFang HK', 0.926125678439, False),
    ('PingFang SC', 0.926125678439, False),
    ('PingFang TC', 0.926125678439, False),
    ('Rockwell', 1.000099008935, False),
    ('Savoye LET', 0.633016579056, False),
    ('SignPainter', 0.682552069232, False),
    ('Skia', 0.945575127169, False),
    ('Snell Roundhand', 0.827228274299, False),
    ('Tahoma', 0.922755440792, False),
    ('Thonburi', 0.996665221212, False),
    ('Times', 0.875665876136, False),
    ('Times New Roman', 0.875665876136, False),
    ('Trebuchet MS', 0.906753323245, False),
    ('Verdana', 1.053539413993, False),
    ('Zapfino', 1.334619201639, False),
)

__all__ = [
    "MACOS_TAHOE_CAPTURE_PLATFORM_VERSION",
    "MACOS_TAHOE_CAPTURE_USER_AGENT",
    "MACOS_TAHOE_FONT_FAMILIES",
    "MACOS_TAHOE_FONT_METRICS",
    "MACOS_TAHOE_LOCAL_FONTS",
]
