"""Additive NVIDIA product/PCI snapshot; generated, do not hand edit.

This module augments but never replaces the existing Windows profile catalogs.
"""

NVIDIA_OPEN_GPU_SOURCE = 'https://raw.githubusercontent.com/NVIDIA/open-gpu-kernel-modules/main/README.md'
DAWN_GPU_INFO_SOURCE = 'https://dawn.googlesource.com/dawn/+/23cf554e645f61acabcd10aac24bfe6d6b0eeeec/src/dawn/gpu_info.json?format=TEXT'
SNAPSHOT_GENERATED_AT_UTC = '2026-08-08T15:16:57.191057Z'
NVIDIA_SOURCE_SHA256 = '6aeda24d054d9eea8558c94048792e0dcead1635cab652b1cbad23fb50684cf8'
DAWN_SOURCE_SHA256 = 'e3dad696331b69eaa2632ec306f76ef2871c1642ac24f4d2df392b15b20336c3'

# id, exact product name, Dawn architecture, tier, form factor,
# browser eligible, exact PCI Device IDs.
NVIDIA_OPEN_GPU_PRODUCT_ROWS = (
    ('win_nvidia_open_matrox_d_series_d2450', 'Matrox D-Series D2450', 'turing', 'mainstream', 'desktop', True, ('1F76',)),
    ('win_nvidia_open_matrox_d_series_d2480', 'Matrox D-Series D2480', 'turing', 'mainstream', 'desktop', True, ('1F76',)),
    ('win_nvidia_open_a10', 'NVIDIA A10', 'ampere', 'mainstream', 'desktop', False, ('2236',)),
    ('win_nvidia_open_a100_80gb_pcie', 'NVIDIA A100 80GB PCIe', 'ampere', 'mainstream', 'desktop', False, ('20B5',)),
    ('win_nvidia_open_a100_pcie_40gb', 'NVIDIA A100-PCIE-40GB', 'ampere', 'mainstream', 'desktop', False, ('20F1',)),
    ('win_nvidia_open_a100_pg509_200', 'NVIDIA A100-PG509-200', 'ampere', 'mainstream', 'desktop', False, ('20B0',)),
    ('win_nvidia_open_a100_sxm_64gb', 'NVIDIA A100-SXM-64GB', 'ampere', 'mainstream', 'desktop', False, ('20B3',)),
    ('win_nvidia_open_a100_sxm4_40gb', 'NVIDIA A100-SXM4-40GB', 'ampere', 'mainstream', 'desktop', False, ('20B0',)),
    ('win_nvidia_open_a100_sxm4_80gb', 'NVIDIA A100-SXM4-80GB', 'ampere', 'mainstream', 'desktop', False, ('20B2',)),
    ('win_nvidia_open_a10g', 'NVIDIA A10G', 'ampere', 'mainstream', 'desktop', False, ('2237',)),
    ('win_nvidia_open_a10m', 'NVIDIA A10M', 'ampere', 'mainstream', 'desktop', False, ('2238',)),
    ('win_nvidia_open_a16', 'NVIDIA A16', 'ampere', 'mainstream', 'desktop', False, ('25B6',)),
    ('win_nvidia_open_a2', 'NVIDIA A2', 'ampere', 'mainstream', 'desktop', False, ('25B6',)),
    ('win_nvidia_open_a30', 'NVIDIA A30', 'ampere', 'mainstream', 'desktop', False, ('20B7',)),
    ('win_nvidia_open_a40', 'NVIDIA A40', 'ampere', 'mainstream', 'desktop', False, ('2235',)),
    ('win_nvidia_open_a800_40gb_active', 'NVIDIA A800 40GB Active', 'ampere', 'mainstream', 'desktop', False, ('20F6',)),
    ('win_nvidia_open_a800_80gb_pcie', 'NVIDIA A800 80GB PCIe', 'ampere', 'mainstream', 'desktop', False, ('20F5',)),
    ('win_nvidia_open_a800_80gb_pcie_lc', 'NVIDIA A800 80GB PCIe LC', 'ampere', 'mainstream', 'desktop', False, ('20F5',)),
    ('win_nvidia_open_a800_sxm4_40gb', 'NVIDIA A800-SXM4-40GB', 'ampere', 'mainstream', 'desktop', False, ('20BD',)),
    ('win_nvidia_open_a800_sxm4_80gb', 'NVIDIA A800-SXM4-80GB', 'ampere', 'mainstream', 'desktop', False, ('20F3',)),
    ('win_nvidia_open_ax800', 'NVIDIA AX800', 'ampere', 'mainstream', 'desktop', False, ('20FD',)),
    ('win_nvidia_open_b200', 'NVIDIA B200', 'unmapped', 'mainstream', 'desktop', False, ('2901', '2909')),
    ('win_nvidia_open_b300_sxm6_ac', 'NVIDIA B300 SXM6 AC', 'unmapped', 'mainstream', 'desktop', False, ('3182',)),
    ('win_nvidia_open_cmp_30hx', 'NVIDIA CMP 30HX', 'turing', 'mainstream', 'desktop', False, ('2189',)),
    ('win_nvidia_open_cmp_40hx', 'NVIDIA CMP 40HX', 'turing', 'mainstream', 'desktop', False, ('1F0B',)),
    ('win_nvidia_open_cmp_50hx', 'NVIDIA CMP 50HX', 'turing', 'mainstream', 'desktop', False, ('1E09',)),
    ('win_nvidia_open_cmp_70hx', 'NVIDIA CMP 70HX', 'ampere', 'mainstream', 'desktop', False, ('248A',)),
    ('win_nvidia_open_cmp_90hx', 'NVIDIA CMP 90HX', 'ampere', 'mainstream', 'desktop', False, ('220D',)),
    ('win_nvidia_open_dgx_display', 'NVIDIA DGX Display', 'turing', 'mainstream', 'desktop', False, ('1FB0',)),
    ('win_nvidia_open_drive_p2021', 'NVIDIA DRIVE P2021', 'unmapped', 'mainstream', 'desktop', False, ('29BB',)),
    ('win_nvidia_open_gb10', 'NVIDIA GB10', 'unmapped', 'mainstream', 'desktop', False, ('2E12',)),
    ('win_nvidia_open_gb200', 'NVIDIA GB200', 'unmapped', 'mainstream', 'desktop', False, ('2941',)),
    ('win_nvidia_open_gb300', 'NVIDIA GB300', 'unmapped', 'mainstream', 'desktop', False, ('31C2', '31C3')),
    ('win_nvidia_open_gh200_120gb', 'NVIDIA GH200 120GB', 'unmapped', 'mainstream', 'desktop', False, ('2342',)),
    ('win_nvidia_open_gh200_144g_hbm3e', 'NVIDIA GH200 144G HBM3e', 'unmapped', 'mainstream', 'desktop', False, ('2348',)),
    ('win_nvidia_open_gh200_480gb', 'NVIDIA GH200 480GB', 'unmapped', 'mainstream', 'desktop', False, ('2342',)),
    ('win_nvidia_open_geforce_gtx_1630', 'NVIDIA GeForce GTX 1630', 'turing', 'mainstream', 'desktop', True, ('1F83',)),
    ('win_nvidia_open_geforce_gtx_1650', 'NVIDIA GeForce GTX 1650', 'turing', 'entry', 'desktop', True, ('1F0A', '1F82', '1F91', '1F96', '1F99', '1F9D', '1FDD', '2188')),
    ('win_nvidia_open_geforce_gtx_1650_super', 'NVIDIA GeForce GTX 1650 SUPER', 'turing', 'entry', 'desktop', True, ('2187',)),
    ('win_nvidia_open_geforce_gtx_1650_ti', 'NVIDIA GeForce GTX 1650 Ti', 'turing', 'entry', 'desktop', True, ('1F95', '2192')),
    ('win_nvidia_open_geforce_gtx_1650_ti_with_max_q_design', 'NVIDIA GeForce GTX 1650 Ti with Max-Q Design', 'turing', 'laptop', 'portable', True, ('1F95',)),
    ('win_nvidia_open_geforce_gtx_1650_with_max_q_design', 'NVIDIA GeForce GTX 1650 with Max-Q Design', 'turing', 'laptop', 'portable', True, ('1F91', '1F96', '1F99', '1F9D')),
    ('win_nvidia_open_geforce_gtx_1660', 'NVIDIA GeForce GTX 1660', 'turing', 'mainstream', 'desktop', True, ('2184',)),
    ('win_nvidia_open_geforce_gtx_1660_super', 'NVIDIA GeForce GTX 1660 SUPER', 'turing', 'mainstream', 'desktop', True, ('21C4',)),
    ('win_nvidia_open_geforce_gtx_1660_ti', 'NVIDIA GeForce GTX 1660 Ti', 'turing', 'mainstream', 'desktop', True, ('2182', '2191', '21D1')),
    ('win_nvidia_open_geforce_gtx_1660_ti_with_max_q_design', 'NVIDIA GeForce GTX 1660 Ti with Max-Q Design', 'turing', 'laptop', 'portable', True, ('2191',)),
    ('win_nvidia_open_geforce_mx450', 'NVIDIA GeForce MX450', 'turing', 'laptop', 'portable', True, ('1F97', '1F98', '1F9C')),
    ('win_nvidia_open_geforce_mx550', 'NVIDIA GeForce MX550', 'turing', 'laptop', 'portable', True, ('1F9F', '1FA0')),
    ('win_nvidia_open_geforce_mx570', 'NVIDIA GeForce MX570', 'ampere', 'laptop', 'portable', True, ('25A6',)),
    ('win_nvidia_open_geforce_mx570_a', 'NVIDIA GeForce MX570 A', 'ampere', 'laptop', 'portable', True, ('25AA',)),
    ('win_nvidia_open_geforce_rtx_2050', 'NVIDIA GeForce RTX 2050', 'ampere', 'laptop', 'portable', True, ('25A7', '25A9', '25AD', '25ED')),
    ('win_nvidia_open_geforce_rtx_2060', 'NVIDIA GeForce RTX 2060', 'turing', 'mainstream', 'desktop', True, ('1E89', '1F03', '1F08', '1F11', '1F12', '1F15', '1F51', '1F55')),
    ('win_nvidia_open_geforce_rtx_2060_super', 'NVIDIA GeForce RTX 2060 SUPER', 'turing', 'mainstream', 'desktop', True, ('1F06', '1F42', '1F47')),
    ('win_nvidia_open_geforce_rtx_2060_with_max_q_design', 'NVIDIA GeForce RTX 2060 with Max-Q Design', 'turing', 'laptop', 'portable', True, ('1F12',)),
    ('win_nvidia_open_geforce_rtx_2070', 'NVIDIA GeForce RTX 2070', 'turing', 'high', 'desktop', True, ('1F02', '1F07', '1F10', '1F14', '1F50', '1F54')),
    ('win_nvidia_open_geforce_rtx_2070_super', 'NVIDIA GeForce RTX 2070 SUPER', 'turing', 'high', 'desktop', True, ('1E84', '1EC2', '1EC7')),
    ('win_nvidia_open_geforce_rtx_2070_super_turing', 'NVIDIA GeForce RTX 2070 Super', 'turing', 'high', 'desktop', True, ('1E91', '1ED1')),
    ('win_nvidia_open_geforce_rtx_2070_super_with_max_q_design', 'NVIDIA GeForce RTX 2070 Super with Max-Q Design', 'turing', 'laptop', 'portable', True, ('1E91', '1ED1')),
    ('win_nvidia_open_geforce_rtx_2070_with_max_q_design', 'NVIDIA GeForce RTX 2070 with Max-Q Design', 'turing', 'laptop', 'portable', True, ('1F10', '1F14', '1F50', '1F54')),
    ('win_nvidia_open_geforce_rtx_2080', 'NVIDIA GeForce RTX 2080', 'turing', 'high', 'desktop', True, ('1E82', '1E87', '1E90', '1ED0')),
    ('win_nvidia_open_geforce_rtx_2080_super', 'NVIDIA GeForce RTX 2080 SUPER', 'turing', 'high', 'desktop', True, ('1E81',)),
    ('win_nvidia_open_geforce_rtx_2080_super_turing', 'NVIDIA GeForce RTX 2080 Super', 'turing', 'high', 'desktop', True, ('1E93', '1ED3')),
    ('win_nvidia_open_geforce_rtx_2080_super_with_max_q_design', 'NVIDIA GeForce RTX 2080 Super with Max-Q Design', 'turing', 'laptop', 'portable', True, ('1E93', '1ED3')),
    ('win_nvidia_open_geforce_rtx_2080_ti', 'NVIDIA GeForce RTX 2080 Ti', 'turing', 'high', 'desktop', True, ('1E04', '1E07')),
    ('win_nvidia_open_geforce_rtx_2080_with_max_q_design', 'NVIDIA GeForce RTX 2080 with Max-Q Design', 'turing', 'laptop', 'portable', True, ('1E90', '1ED0')),
    ('win_nvidia_open_geforce_rtx_3050', 'NVIDIA GeForce RTX 3050', 'ampere', 'entry', 'desktop', True, ('2507', '2582', '2584')),
    ('win_nvidia_open_geforce_rtx_3050_4gb_laptop_gpu', 'NVIDIA GeForce RTX 3050 4GB Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25AB',)),
    ('win_nvidia_open_geforce_rtx_3050_6gb_laptop_gpu', 'NVIDIA GeForce RTX 3050 6GB Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25AC', '25EC')),
    ('win_nvidia_open_geforce_rtx_3050_a_laptop_gpu', 'NVIDIA GeForce RTX 3050 A Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('2822', '28A3', '28E3')),
    ('win_nvidia_open_geforce_rtx_3050_laptop_gpu', 'NVIDIA GeForce RTX 3050 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25A2', '25A5', '25E2', '25E5')),
    ('win_nvidia_open_geforce_rtx_3050_oem', 'NVIDIA GeForce RTX 3050 OEM', 'ampere', 'entry', 'desktop', True, ('2508',)),
    ('win_nvidia_open_geforce_rtx_3050_ti_laptop_gpu', 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'ampere', 'laptop', 'portable', True, ('2523', '2563', '25A0', '25A2', '25E0')),
    ('win_nvidia_open_geforce_rtx_3050ti_laptop_gpu', 'NVIDIA GeForce RTX 3050Ti Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25A0',)),
    ('win_nvidia_open_geforce_rtx_3060', 'NVIDIA GeForce RTX 3060', 'ampere', 'mainstream', 'desktop', True, ('2487', '24C7', '2503', '2504', '2544')),
    ('win_nvidia_open_geforce_rtx_3060_laptop_gpu', 'NVIDIA GeForce RTX 3060 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('249C', '24A0', '2520', '2521', '2560', '25A0', '25A2')),
    ('win_nvidia_open_geforce_rtx_3060_ti', 'NVIDIA GeForce RTX 3060 Ti', 'ampere', 'mainstream', 'desktop', True, ('2414', '2486', '2489', '24C9')),
    ('win_nvidia_open_geforce_rtx_3070', 'NVIDIA GeForce RTX 3070', 'ampere', 'high', 'desktop', True, ('2484', '2488')),
    ('win_nvidia_open_geforce_rtx_3070_laptop_gpu', 'NVIDIA GeForce RTX 3070 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('249D', '24DD')),
    ('win_nvidia_open_geforce_rtx_3070_ti', 'NVIDIA GeForce RTX 3070 Ti', 'ampere', 'high', 'desktop', True, ('2207', '2482')),
    ('win_nvidia_open_geforce_rtx_3070_ti_laptop_gpu', 'NVIDIA GeForce RTX 3070 Ti Laptop GPU', 'ampere', 'laptop', 'portable', True, ('24A0', '24E0')),
    ('win_nvidia_open_geforce_rtx_3080', 'NVIDIA GeForce RTX 3080', 'ampere', 'high', 'desktop', True, ('2206', '220A', '2216')),
    ('win_nvidia_open_geforce_rtx_3080_laptop_gpu', 'NVIDIA GeForce RTX 3080 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('249C', '24DC')),
    ('win_nvidia_open_geforce_rtx_3080_ti', 'NVIDIA GeForce RTX 3080 Ti', 'ampere', 'high', 'desktop', True, ('2208',)),
    ('win_nvidia_open_geforce_rtx_3080_ti_laptop_gpu', 'NVIDIA GeForce RTX 3080 Ti Laptop GPU', 'ampere', 'laptop', 'portable', True, ('2420', '2460')),
    ('win_nvidia_open_geforce_rtx_3090', 'NVIDIA GeForce RTX 3090', 'ampere', 'enthusiast', 'desktop', True, ('2204',)),
    ('win_nvidia_open_geforce_rtx_3090_ti', 'NVIDIA GeForce RTX 3090 Ti', 'ampere', 'enthusiast', 'desktop', True, ('2203',)),
    ('win_nvidia_open_geforce_rtx_4050_laptop_gpu', 'NVIDIA GeForce RTX 4050 Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('28A1', '28E1')),
    ('win_nvidia_open_geforce_rtx_4060', 'NVIDIA GeForce RTX 4060', 'lovelace', 'mainstream', 'desktop', True, ('2808', '2882')),
    ('win_nvidia_open_geforce_rtx_4060_laptop_gpu', 'NVIDIA GeForce RTX 4060 Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('28A0', '28E0')),
    ('win_nvidia_open_geforce_rtx_4060_ti', 'NVIDIA GeForce RTX 4060 Ti', 'lovelace', 'mainstream', 'desktop', True, ('2788', '2803', '2805')),
    ('win_nvidia_open_geforce_rtx_4070', 'NVIDIA GeForce RTX 4070', 'lovelace', 'high', 'desktop', True, ('2709', '2786')),
    ('win_nvidia_open_geforce_rtx_4070_laptop_gpu', 'NVIDIA GeForce RTX 4070 Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('2820', '2860')),
    ('win_nvidia_open_geforce_rtx_4070_super', 'NVIDIA GeForce RTX 4070 SUPER', 'lovelace', 'high', 'desktop', True, ('2783',)),
    ('win_nvidia_open_geforce_rtx_4070_ti', 'NVIDIA GeForce RTX 4070 Ti', 'lovelace', 'high', 'desktop', True, ('2782',)),
    ('win_nvidia_open_geforce_rtx_4070_ti_super', 'NVIDIA GeForce RTX 4070 Ti SUPER', 'lovelace', 'high', 'desktop', True, ('2689', '2705')),
    ('win_nvidia_open_geforce_rtx_4080', 'NVIDIA GeForce RTX 4080', 'lovelace', 'high', 'desktop', True, ('2704',)),
    ('win_nvidia_open_geforce_rtx_4080_laptop_gpu', 'NVIDIA GeForce RTX 4080 Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('27A0', '27E0')),
    ('win_nvidia_open_geforce_rtx_4080_super', 'NVIDIA GeForce RTX 4080 SUPER', 'lovelace', 'high', 'desktop', True, ('2702',)),
    ('win_nvidia_open_geforce_rtx_4090', 'NVIDIA GeForce RTX 4090', 'lovelace', 'enthusiast', 'desktop', True, ('2684',)),
    ('win_nvidia_open_geforce_rtx_4090_d', 'NVIDIA GeForce RTX 4090 D', 'lovelace', 'enthusiast', 'desktop', True, ('2685',)),
    ('win_nvidia_open_geforce_rtx_4090_laptop_gpu', 'NVIDIA GeForce RTX 4090 Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('2717', '2757')),
    ('win_nvidia_open_geforce_rtx_5050', 'NVIDIA GeForce RTX 5050', 'blackwell', 'entry', 'desktop', True, ('2D83',)),
    ('win_nvidia_open_geforce_rtx_5050_laptop_gpu', 'NVIDIA GeForce RTX 5050 Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2D98', '2DD8')),
    ('win_nvidia_open_geforce_rtx_5060', 'NVIDIA GeForce RTX 5060', 'blackwell', 'mainstream', 'desktop', True, ('2D05', '2F06')),
    ('win_nvidia_open_geforce_rtx_5060_laptop_gpu', 'NVIDIA GeForce RTX 5060 Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2D19', '2D59')),
    ('win_nvidia_open_geforce_rtx_5060_ti', 'NVIDIA GeForce RTX 5060 Ti', 'blackwell', 'mainstream', 'desktop', True, ('2D04',)),
    ('win_nvidia_open_geforce_rtx_5070', 'NVIDIA GeForce RTX 5070', 'blackwell', 'high', 'desktop', True, ('2F04',)),
    ('win_nvidia_open_geforce_rtx_5070_laptop_gpu', 'NVIDIA GeForce RTX 5070 Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2D18', '2D58')),
    ('win_nvidia_open_geforce_rtx_5070_ti', 'NVIDIA GeForce RTX 5070 Ti', 'blackwell', 'high', 'desktop', True, ('2C05',)),
    ('win_nvidia_open_geforce_rtx_5070_ti_laptop_gpu', 'NVIDIA GeForce RTX 5070 Ti Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2F18', '2F58')),
    ('win_nvidia_open_geforce_rtx_5080', 'NVIDIA GeForce RTX 5080', 'blackwell', 'high', 'desktop', True, ('2C02',)),
    ('win_nvidia_open_geforce_rtx_5080_laptop_gpu', 'NVIDIA GeForce RTX 5080 Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2C19', '2C59')),
    ('win_nvidia_open_geforce_rtx_5090', 'NVIDIA GeForce RTX 5090', 'blackwell', 'enthusiast', 'desktop', True, ('2B85',)),
    ('win_nvidia_open_geforce_rtx_5090_d', 'NVIDIA GeForce RTX 5090 D', 'blackwell', 'enthusiast', 'desktop', True, ('2B87',)),
    ('win_nvidia_open_geforce_rtx_5090_d_v2', 'NVIDIA GeForce RTX 5090 D v2', 'blackwell', 'enthusiast', 'desktop', True, ('2B8C',)),
    ('win_nvidia_open_geforce_rtx_5090_laptop_gpu', 'NVIDIA GeForce RTX 5090 Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2C18', '2C58')),
    ('win_nvidia_open_h100', 'NVIDIA H100', 'unmapped', 'mainstream', 'desktop', False, ('2339',)),
    ('win_nvidia_open_h100_80gb_hbm3', 'NVIDIA H100 80GB HBM3', 'unmapped', 'mainstream', 'desktop', False, ('2330',)),
    ('win_nvidia_open_h100_nvl', 'NVIDIA H100 NVL', 'unmapped', 'mainstream', 'desktop', False, ('2321',)),
    ('win_nvidia_open_h100_pcie', 'NVIDIA H100 PCIe', 'unmapped', 'mainstream', 'desktop', False, ('2331',)),
    ('win_nvidia_open_h20', 'NVIDIA H20', 'unmapped', 'mainstream', 'desktop', False, ('2329',)),
    ('win_nvidia_open_h20_nvl16', 'NVIDIA H20 NVL16', 'unmapped', 'mainstream', 'desktop', False, ('230E',)),
    ('win_nvidia_open_h20_3e', 'NVIDIA H20-3e', 'unmapped', 'mainstream', 'desktop', False, ('232C',)),
    ('win_nvidia_open_h200', 'NVIDIA H200', 'unmapped', 'mainstream', 'desktop', False, ('2335',)),
    ('win_nvidia_open_h200_nvl', 'NVIDIA H200 NVL', 'unmapped', 'mainstream', 'desktop', False, ('233B',)),
    ('win_nvidia_open_h800', 'NVIDIA H800', 'unmapped', 'mainstream', 'desktop', False, ('2324',)),
    ('win_nvidia_open_h800_nvl', 'NVIDIA H800 NVL', 'unmapped', 'mainstream', 'desktop', False, ('233A',)),
    ('win_nvidia_open_h800_pcie', 'NVIDIA H800 PCIe', 'unmapped', 'mainstream', 'desktop', False, ('2322',)),
    ('win_nvidia_open_l2', 'NVIDIA L2', 'lovelace', 'mainstream', 'desktop', False, ('27B6',)),
    ('win_nvidia_open_l20', 'NVIDIA L20', 'lovelace', 'mainstream', 'desktop', False, ('26BA',)),
    ('win_nvidia_open_l4', 'NVIDIA L4', 'lovelace', 'mainstream', 'desktop', False, ('27B8',)),
    ('win_nvidia_open_l40', 'NVIDIA L40', 'lovelace', 'mainstream', 'desktop', False, ('26B5',)),
    ('win_nvidia_open_l40s', 'NVIDIA L40S', 'lovelace', 'mainstream', 'desktop', False, ('26B9',)),
    ('win_nvidia_open_pg506_232', 'NVIDIA PG506-232', 'ampere', 'mainstream', 'desktop', False, ('20B6',)),
    ('win_nvidia_open_pg509_210', 'NVIDIA PG509-210', 'ampere', 'mainstream', 'desktop', False, ('20B2',)),
    ('win_nvidia_open_rtx_1000_ada_generation_laptop_gpu', 'NVIDIA RTX 1000 Ada Generation Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('28B9',)),
    ('win_nvidia_open_rtx_2000_ada_generation', 'NVIDIA RTX 2000 Ada Generation', 'lovelace', 'workstation', 'desktop', True, ('28B0',)),
    ('win_nvidia_open_rtx_2000_ada_generation_embedded_gpu', 'NVIDIA RTX 2000 Ada Generation Embedded GPU', 'lovelace', 'workstation', 'desktop', True, ('28F8',)),
    ('win_nvidia_open_rtx_2000_ada_generation_laptop_gpu', 'NVIDIA RTX 2000 Ada Generation Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('28B8',)),
    ('win_nvidia_open_rtx_2000e_ada_generation', 'NVIDIA RTX 2000E Ada Generation', 'lovelace', 'workstation', 'desktop', True, ('28B0',)),
    ('win_nvidia_open_rtx_3000_ada_generation_laptop_gpu', 'NVIDIA RTX 3000 Ada Generation Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('2838',)),
    ('win_nvidia_open_rtx_3500_ada_generation_embedded_gpu', 'NVIDIA RTX 3500 Ada Generation Embedded GPU', 'lovelace', 'workstation', 'desktop', True, ('27FB',)),
    ('win_nvidia_open_rtx_3500_ada_generation_laptop_gpu', 'NVIDIA RTX 3500 Ada Generation Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('27BB',)),
    ('win_nvidia_open_rtx_4000_ada_generation', 'NVIDIA RTX 4000 Ada Generation', 'lovelace', 'workstation', 'desktop', True, ('27B2',)),
    ('win_nvidia_open_rtx_4000_ada_generation_laptop_gpu', 'NVIDIA RTX 4000 Ada Generation Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('27BA',)),
    ('win_nvidia_open_rtx_4000_sff_ada_generation', 'NVIDIA RTX 4000 SFF Ada Generation', 'lovelace', 'workstation', 'desktop', True, ('27B0',)),
    ('win_nvidia_open_rtx_4500_ada_generation', 'NVIDIA RTX 4500 Ada Generation', 'lovelace', 'workstation', 'desktop', True, ('27B1',)),
    ('win_nvidia_open_rtx_500_ada_generation_laptop_gpu', 'NVIDIA RTX 500 Ada Generation Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('28BA', '28BB')),
    ('win_nvidia_open_rtx_5000_ada_generation', 'NVIDIA RTX 5000 Ada Generation', 'lovelace', 'workstation', 'desktop', True, ('26B2',)),
    ('win_nvidia_open_rtx_5000_ada_generation_embedded_gpu', 'NVIDIA RTX 5000 Ada Generation Embedded GPU', 'lovelace', 'workstation', 'desktop', True, ('2770',)),
    ('win_nvidia_open_rtx_5000_ada_generation_laptop_gpu', 'NVIDIA RTX 5000 Ada Generation Laptop GPU', 'lovelace', 'laptop', 'portable', True, ('2730',)),
    ('win_nvidia_open_rtx_5880_ada_generation', 'NVIDIA RTX 5880 Ada Generation', 'lovelace', 'high', 'desktop', True, ('26B3',)),
    ('win_nvidia_open_rtx_6000_ada_generation', 'NVIDIA RTX 6000 Ada Generation', 'lovelace', 'workstation', 'desktop', True, ('26B1',)),
    ('win_nvidia_open_rtx_6000d', 'NVIDIA RTX 6000D', 'blackwell', 'workstation', 'desktop', True, ('2BB9',)),
    ('win_nvidia_open_rtx_a1000', 'NVIDIA RTX A1000', 'ampere', 'workstation', 'desktop', True, ('25B0',)),
    ('win_nvidia_open_rtx_a1000_6gb_laptop_gpu', 'NVIDIA RTX A1000 6GB Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25BC',)),
    ('win_nvidia_open_rtx_a1000_embedded_gpu', 'NVIDIA RTX A1000 Embedded GPU', 'ampere', 'workstation', 'desktop', True, ('25F9',)),
    ('win_nvidia_open_rtx_a1000_laptop_gpu', 'NVIDIA RTX A1000 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25B9',)),
    ('win_nvidia_open_rtx_a2000', 'NVIDIA RTX A2000', 'ampere', 'workstation', 'desktop', True, ('2531',)),
    ('win_nvidia_open_rtx_a2000_12gb', 'NVIDIA RTX A2000 12GB', 'ampere', 'workstation', 'desktop', True, ('2571',)),
    ('win_nvidia_open_rtx_a2000_8gb_laptop_gpu', 'NVIDIA RTX A2000 8GB Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25BA',)),
    ('win_nvidia_open_rtx_a2000_embedded_gpu', 'NVIDIA RTX A2000 Embedded GPU', 'ampere', 'workstation', 'desktop', True, ('25FA',)),
    ('win_nvidia_open_rtx_a2000_laptop_gpu', 'NVIDIA RTX A2000 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25B8',)),
    ('win_nvidia_open_rtx_a3000_12gb_laptop_gpu', 'NVIDIA RTX A3000 12GB Laptop GPU', 'ampere', 'laptop', 'portable', True, ('24B9', '24BB')),
    ('win_nvidia_open_rtx_a3000_laptop_gpu', 'NVIDIA RTX A3000 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('24B8',)),
    ('win_nvidia_open_rtx_a400', 'NVIDIA RTX A400', 'ampere', 'workstation', 'desktop', True, ('25B2',)),
    ('win_nvidia_open_rtx_a4000', 'NVIDIA RTX A4000', 'ampere', 'workstation', 'desktop', True, ('24B0',)),
    ('win_nvidia_open_rtx_a4000_laptop_gpu', 'NVIDIA RTX A4000 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('24B7',)),
    ('win_nvidia_open_rtx_a4000h', 'NVIDIA RTX A4000H', 'ampere', 'workstation', 'desktop', True, ('24B1',)),
    ('win_nvidia_open_rtx_a4500', 'NVIDIA RTX A4500', 'ampere', 'workstation', 'desktop', True, ('2232',)),
    ('win_nvidia_open_rtx_a4500_embedded_gpu', 'NVIDIA RTX A4500 Embedded GPU', 'ampere', 'workstation', 'desktop', True, ('24FA',)),
    ('win_nvidia_open_rtx_a4500_laptop_gpu', 'NVIDIA RTX A4500 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('24BA',)),
    ('win_nvidia_open_rtx_a500_embedded_gpu', 'NVIDIA RTX A500 Embedded GPU', 'ampere', 'workstation', 'desktop', True, ('25FB',)),
    ('win_nvidia_open_rtx_a500_laptop_gpu', 'NVIDIA RTX A500 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('25BB', '25BD')),
    ('win_nvidia_open_rtx_a5000', 'NVIDIA RTX A5000', 'ampere', 'workstation', 'desktop', True, ('2231',)),
    ('win_nvidia_open_rtx_a5000_laptop_gpu', 'NVIDIA RTX A5000 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('24B6',)),
    ('win_nvidia_open_rtx_a5500', 'NVIDIA RTX A5500', 'ampere', 'workstation', 'desktop', True, ('2233',)),
    ('win_nvidia_open_rtx_a5500_laptop_gpu', 'NVIDIA RTX A5500 Laptop GPU', 'ampere', 'laptop', 'portable', True, ('2438',)),
    ('win_nvidia_open_rtx_a6000', 'NVIDIA RTX A6000', 'ampere', 'workstation', 'desktop', True, ('2230',)),
    ('win_nvidia_open_rtx_pro_1000_blackwell_generation_laptop_gpu', 'NVIDIA RTX PRO 1000 Blackwell Generation Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2DB8',)),
    ('win_nvidia_open_rtx_pro_2000_blackwell', 'NVIDIA RTX PRO 2000 Blackwell', 'blackwell', 'workstation', 'desktop', True, ('2D30',)),
    ('win_nvidia_open_rtx_pro_2000_blackwell_embedded_gpu', 'NVIDIA RTX PRO 2000 Blackwell Embedded GPU', 'blackwell', 'workstation', 'desktop', True, ('2D79',)),
    ('win_nvidia_open_rtx_pro_2000_blackwell_generation_laptop_gpu', 'NVIDIA RTX PRO 2000 Blackwell Generation Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2D39',)),
    ('win_nvidia_open_rtx_pro_3000_blackwell_generation_laptop_gpu', 'NVIDIA RTX PRO 3000 Blackwell Generation Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2F38',)),
    ('win_nvidia_open_rtx_pro_4000_blackwell', 'NVIDIA RTX PRO 4000 Blackwell', 'blackwell', 'workstation', 'desktop', True, ('2C34',)),
    ('win_nvidia_open_rtx_pro_4000_blackwell_embedded_gpu', 'NVIDIA RTX PRO 4000 Blackwell Embedded GPU', 'blackwell', 'workstation', 'desktop', True, ('2C79',)),
    ('win_nvidia_open_rtx_pro_4000_blackwell_generation_laptop_gpu', 'NVIDIA RTX PRO 4000 Blackwell Generation Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2C39',)),
    ('win_nvidia_open_rtx_pro_4000_blackwell_sff_edition', 'NVIDIA RTX PRO 4000 Blackwell SFF Edition', 'blackwell', 'workstation', 'desktop', True, ('2C33',)),
    ('win_nvidia_open_rtx_pro_4500_blackwell', 'NVIDIA RTX PRO 4500 Blackwell', 'blackwell', 'workstation', 'desktop', True, ('2C31',)),
    ('win_nvidia_open_rtx_pro_4500_blackwell_server_edition', 'NVIDIA RTX PRO 4500 Blackwell Server Edition', 'blackwell', 'workstation', 'desktop', True, ('2C3A',)),
    ('win_nvidia_open_rtx_pro_500_blackwell_embedded_gpu', 'NVIDIA RTX PRO 500 Blackwell Embedded GPU', 'blackwell', 'workstation', 'desktop', True, ('2DF9',)),
    ('win_nvidia_open_rtx_pro_500_blackwell_generation_laptop_gpu', 'NVIDIA RTX PRO 500 Blackwell Generation Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2DB9',)),
    ('win_nvidia_open_rtx_pro_5000_72gb_blackwell', 'NVIDIA RTX PRO 5000 72GB Blackwell', 'blackwell', 'workstation', 'desktop', True, ('2BB3',)),
    ('win_nvidia_open_rtx_pro_5000_blackwell', 'NVIDIA RTX PRO 5000 Blackwell', 'blackwell', 'workstation', 'desktop', True, ('2BB3',)),
    ('win_nvidia_open_rtx_pro_5000_blackwell_embedded_gpu', 'NVIDIA RTX PRO 5000 Blackwell Embedded GPU', 'blackwell', 'workstation', 'desktop', True, ('2C77',)),
    ('win_nvidia_open_rtx_pro_5000_blackwell_generation_laptop_gpu', 'NVIDIA RTX PRO 5000 Blackwell Generation Laptop GPU', 'blackwell', 'laptop', 'portable', True, ('2C38',)),
    ('win_nvidia_open_rtx_pro_6000_blackwell_max_q_workstation_edition', 'NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition', 'blackwell', 'laptop', 'portable', True, ('2BB4',)),
    ('win_nvidia_open_rtx_pro_6000_blackwell_server_edition', 'NVIDIA RTX PRO 6000 Blackwell Server Edition', 'blackwell', 'workstation', 'desktop', True, ('2BB5',)),
    ('win_nvidia_open_rtx_pro_6000_blackwell_workstation_edition', 'NVIDIA RTX PRO 6000 Blackwell Workstation Edition', 'blackwell', 'workstation', 'desktop', True, ('2BB1',)),
    ('win_nvidia_open_rtx_spark_n1x_5120_core_blackwell_rtx_gpu', 'NVIDIA RTX Spark N1X (5120-core Blackwell RTX GPU)', 'unmapped', 'workstation', 'desktop', False, ('2E06',)),
    ('win_nvidia_open_rtx_spark_n1x_6144_core_blackwell_rtx_gpu', 'NVIDIA RTX Spark N1X (6144-core Blackwell RTX GPU)', 'unmapped', 'workstation', 'desktop', False, ('2E03',)),
    ('win_nvidia_open_t1000', 'NVIDIA T1000', 'turing', 'workstation', 'desktop', True, ('1FB0',)),
    ('win_nvidia_open_t1000_8gb', 'NVIDIA T1000 8GB', 'turing', 'workstation', 'desktop', False, ('1FF0',)),
    ('win_nvidia_open_t1200_laptop_gpu', 'NVIDIA T1200 Laptop GPU', 'turing', 'laptop', 'portable', True, ('1FBC',)),
    ('win_nvidia_open_t400', 'NVIDIA T400', 'turing', 'workstation', 'desktop', True, ('1FB2',)),
    ('win_nvidia_open_t400_4gb', 'NVIDIA T400 4GB', 'turing', 'workstation', 'desktop', False, ('1FF2',)),
    ('win_nvidia_open_t400e', 'NVIDIA T400E', 'turing', 'workstation', 'desktop', True, ('1FF2',)),
    ('win_nvidia_open_t500', 'NVIDIA T500', 'turing', 'workstation', 'desktop', True, ('1FBB',)),
    ('win_nvidia_open_t550_laptop_gpu', 'NVIDIA T550 Laptop GPU', 'turing', 'laptop', 'portable', True, ('1FB7',)),
    ('win_nvidia_open_t600', 'NVIDIA T600', 'turing', 'workstation', 'desktop', True, ('1FB1',)),
    ('win_nvidia_open_t600_laptop_gpu', 'NVIDIA T600 Laptop GPU', 'turing', 'laptop', 'portable', True, ('1FB6', '1FBA')),
    ('win_nvidia_open_titan_rtx', 'NVIDIA TITAN RTX', 'turing', 'workstation', 'desktop', True, ('1E02',)),
    ('win_nvidia_open_quadro_rtx_3000', 'Quadro RTX 3000', 'turing', 'workstation', 'desktop', False, ('1F36', '1F76')),
    ('win_nvidia_open_quadro_rtx_3000_with_max_q_design', 'Quadro RTX 3000 with Max-Q Design', 'turing', 'laptop', 'portable', False, ('1F36',)),
    ('win_nvidia_open_quadro_rtx_4000', 'Quadro RTX 4000', 'turing', 'workstation', 'desktop', False, ('1EB1', '1EB6')),
    ('win_nvidia_open_quadro_rtx_4000_with_max_q_design', 'Quadro RTX 4000 with Max-Q Design', 'turing', 'laptop', 'portable', False, ('1EB6',)),
    ('win_nvidia_open_quadro_rtx_5000', 'Quadro RTX 5000', 'turing', 'workstation', 'desktop', False, ('1EB0', '1EB5', '1EF5')),
    ('win_nvidia_open_quadro_rtx_5000_with_max_q_design', 'Quadro RTX 5000 with Max-Q Design', 'turing', 'laptop', 'portable', False, ('1EB5',)),
    ('win_nvidia_open_quadro_rtx_6000', 'Quadro RTX 6000', 'turing', 'workstation', 'desktop', False, ('1E30', '1E36', '1E78')),
    ('win_nvidia_open_quadro_rtx_8000', 'Quadro RTX 8000', 'turing', 'workstation', 'desktop', False, ('1E30', '1E78')),
    ('win_nvidia_open_quadro_t1000', 'Quadro T1000', 'turing', 'workstation', 'desktop', False, ('1FB9', '1FF9')),
    ('win_nvidia_open_quadro_t1000_with_max_q_design', 'Quadro T1000 with Max-Q Design', 'turing', 'laptop', 'portable', False, ('1FB9',)),
    ('win_nvidia_open_quadro_t2000', 'Quadro T2000', 'turing', 'workstation', 'desktop', False, ('1FB8',)),
    ('win_nvidia_open_quadro_t2000_with_max_q_design', 'Quadro T2000 with Max-Q Design', 'turing', 'laptop', 'portable', False, ('1FB8',)),
    ('win_nvidia_open_tesla_t4', 'Tesla T4', 'turing', 'mainstream', 'desktop', False, ('1EB8',)),
)

def count_products(*, browser_eligible_only: bool = False) -> int:
    if not browser_eligible_only:
        return len(NVIDIA_OPEN_GPU_PRODUCT_ROWS)
    return sum(1 for row in NVIDIA_OPEN_GPU_PRODUCT_ROWS if row[5])

def count_device_pairs(*, browser_eligible_only: bool = False) -> int:
    return sum(len(row[6]) for row in NVIDIA_OPEN_GPU_PRODUCT_ROWS if row[5] or not browser_eligible_only)
