"""
PC userAgent / userAgentData catalog.

This module stores realistic PC Chromium-family UA strings and delegates
UA-CH/userAgentData generation to fingerprint_profile_export/ua.py. The user
explicitly pointed out that ua.py already generates userAgentData, so do not
copy the GREASE brand/order logic here.
"""

from __future__ import annotations

import random
import sys
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parent
UA_GENERATOR_DIR = ROOT

if str(UA_GENERATOR_DIR) not in sys.path:
    sys.path.insert(0, str(UA_GENERATOR_DIR))

from ua import (  # type: ignore  # noqa: E402
    clamp_supported_chromium_major,
    generate_headers_from_ua,
    generate_ua_data_from_ua,
    get_base_platform,
    has_specific_full_version,
    parse_ua,
)


def _chrome_ua(version: str) -> str:
    major = str(version or "149").split(".", 1)[0]
    return (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        f"Chrome/{major}.0.0.0 Safari/537.36"
    )


def _edge_ua(chrome_version: str, edge_version: str) -> str:
    chrome_major = str(chrome_version or "149").split(".", 1)[0]
    edge_major = str(edge_version or chrome_major).split(".", 1)[0]
    return (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        f"Chrome/{chrome_major}.0.0.0 Safari/537.36 Edg/{edge_major}.0.0.0"
    )


def _chrome_arm64_ua(version: str) -> str:
    major = str(version or "149").split(".", 1)[0]
    return (
        "Mozilla/5.0 (Windows NT 10.0; Win64; ARM64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        f"Chrome/{major}.0.0.0 Safari/537.36"
    )


def _edge_arm64_ua(chrome_version: str, edge_version: str) -> str:
    chrome_major = str(chrome_version or "149").split(".", 1)[0]
    edge_major = str(edge_version or chrome_major).split(".", 1)[0]
    return (
        "Mozilla/5.0 (Windows NT 10.0; Win64; ARM64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        f"Chrome/{chrome_major}.0.0.0 Safari/537.36 Edg/{edge_major}.0.0.0"
    )


def _app_version_from_ua(ua_string: str) -> str:
    prefix = "Mozilla/"
    return ua_string[len(prefix):] if ua_string.startswith(prefix) else ua_string


def normalize_pc_user_agent_version(ua_string: str) -> str:
    import re

    ua_string = re.sub(
        r"\bChrome/(\d+)(?:\.\d+){0,3}",
        lambda match: f"Chrome/{clamp_supported_chromium_major(match.group(1))}.0.0.0",
        str(ua_string or ""),
    )
    ua_string = re.sub(
        r"\bEdg/(\d+)(?:\.\d+){0,3}",
        lambda match: f"Edg/{clamp_supported_chromium_major(match.group(1))}.0.0.0",
        ua_string,
    )
    return ua_string


def _custom_full_version_options(original_ua_string: str) -> dict[str, str]:
    parsed = parse_ua(original_ua_string)
    options: dict[str, str] = {}
    if has_specific_full_version(parsed.get("fullChromeVersion")):
        options["chromeFullVersion"] = str(parsed["fullChromeVersion"])
    if parsed.get("isEdge") and has_specific_full_version(parsed.get("fullEdgeVersion")):
        options["edgeFullVersion"] = str(parsed["fullEdgeVersion"])
    return options


# id, browser, channel, ua, weight, tags
#
# Windows 10 and Windows 11 both commonly expose "Windows NT 10.0" in Chromium
# UA strings because modern Chromium UA is reduced. Platform details belong in
# userAgentData.platform/platformVersion, generated by ua.py.
#
# Keep this pool constrained to Chrome/Edge major versions 140-150. The UA
# string itself intentionally uses major.0.0.0; full-version UA-CH values are
# resolved by ua.py from the same major version.
PC_USER_AGENT_ROWS: tuple[tuple[str, str, str, str, int, tuple[str, ...]], ...] = (
    # Chrome stable/recent Windows x64.
    ("pc_chrome_150_win64", "chrome", "stable", _chrome_ua("150.0.7879.54"), 14, ("windows", "chromium")),
    ("pc_chrome_149_win64", "chrome", "stable", _chrome_ua("149.0.7827.54"), 18, ("windows", "chromium")),
    ("pc_chrome_148_win64", "chrome", "stable", _chrome_ua("148.0.7778.97"), 36, ("windows", "chromium")),
    ("pc_chrome_147_win64", "chrome", "stable", _chrome_ua("147.0.7640.22"), 32, ("windows", "chromium")),
    ("pc_chrome_146_win64", "chrome", "stable", _chrome_ua("146.0.7590.99"), 24, ("windows", "chromium")),
    ("pc_chrome_145_win64", "chrome", "stable", _chrome_ua("145.0.7541.65"), 18, ("windows", "chromium")),
    ("pc_chrome_144_win64", "chrome", "stable", _chrome_ua("144.0.7492.33"), 14, ("windows", "chromium")),
    ("pc_chrome_143_win64", "chrome", "stable", _chrome_ua("143.0.7445.112"), 10, ("windows", "chromium")),
    ("pc_chrome_142_win64", "chrome", "older", _chrome_ua("142.0.7399.78"), 8, ("windows", "chromium", "older")),
    ("pc_chrome_141_win64", "chrome", "older", _chrome_ua("141.0.7350.44"), 6, ("windows", "chromium", "older")),
    ("pc_chrome_140_win64", "chrome", "older", _chrome_ua("140.0.7301.21"), 5, ("windows", "chromium", "older")),

    # Edge stable/recent Windows x64.
    ("pc_edge_150_win64", "edge", "stable", _edge_ua("150.0.0.0", "150.0.4078.48"), 18, ("windows", "chromium", "edge")),
    ("pc_edge_149_win64", "edge", "stable", _edge_ua("149.0.0.0", "149.0.4022.52"), 16, ("windows", "chromium", "edge")),
    ("pc_edge_148_win64", "edge", "stable", _edge_ua("148.0.0.0", "148.0.3967.54"), 22, ("windows", "chromium", "edge")),
    ("pc_edge_147_win64", "edge", "stable", _edge_ua("147.0.0.0", "147.0.3780.22"), 18, ("windows", "chromium", "edge")),
    ("pc_edge_146_win64", "edge", "stable", _edge_ua("146.0.0.0", "146.0.3733.99"), 12, ("windows", "chromium", "edge")),
    ("pc_edge_145_win64", "edge", "stable", _edge_ua("145.0.0.0", "145.0.3686.65"), 10, ("windows", "chromium", "edge")),
    ("pc_edge_144_win64", "edge", "older", _edge_ua("144.0.0.0", "144.0.3639.33"), 7, ("windows", "chromium", "edge", "older")),
    ("pc_edge_143_win64", "edge", "older", _edge_ua("143.0.0.0", "143.0.3592.112"), 6, ("windows", "chromium", "edge", "older")),
    ("pc_edge_142_win64", "edge", "older", _edge_ua("142.0.0.0", "142.0.3545.78"), 5, ("windows", "chromium", "edge", "older")),
    ("pc_edge_141_win64", "edge", "older", _edge_ua("141.0.0.0", "141.0.3498.44"), 4, ("windows", "chromium", "edge", "older")),
    ("pc_edge_140_win64", "edge", "older", _edge_ua("140.0.0.0", "140.0.3451.12"), 4, ("windows", "chromium", "edge", "older")),

    # Windows on ARM64 / Snapdragon X PCs. These low-weight rows let the
    # generator build real ARM Windows combinations without mixing ARM hardware
    # into ordinary Win64 x64 profiles.
    ("pc_chrome_150_win_arm64", "chrome", "stable", _chrome_arm64_ua("150.0.7879.54"), 1, ("windows", "chromium", "arm64")),
    ("pc_chrome_149_win_arm64", "chrome", "stable", _chrome_arm64_ua("149.0.7827.54"), 1, ("windows", "chromium", "arm64")),
    ("pc_chrome_148_win_arm64", "chrome", "stable", _chrome_arm64_ua("148.0.7778.97"), 1, ("windows", "chromium", "arm64")),
    ("pc_chrome_147_win_arm64", "chrome", "stable", _chrome_arm64_ua("147.0.7640.22"), 1, ("windows", "chromium", "arm64")),
    ("pc_chrome_146_win_arm64", "chrome", "stable", _chrome_arm64_ua("146.0.7590.99"), 1, ("windows", "chromium", "arm64")),
    ("pc_chrome_145_win_arm64", "chrome", "stable", _chrome_arm64_ua("145.0.7541.65"), 1, ("windows", "chromium", "arm64")),
    ("pc_chrome_144_win_arm64", "chrome", "older", _chrome_arm64_ua("144.0.7492.33"), 1, ("windows", "chromium", "arm64", "older")),
    ("pc_chrome_143_win_arm64", "chrome", "older", _chrome_arm64_ua("143.0.7445.112"), 1, ("windows", "chromium", "arm64", "older")),
    ("pc_chrome_142_win_arm64", "chrome", "older", _chrome_arm64_ua("142.0.7399.78"), 1, ("windows", "chromium", "arm64", "older")),
    ("pc_chrome_141_win_arm64", "chrome", "older", _chrome_arm64_ua("141.0.7350.44"), 1, ("windows", "chromium", "arm64", "older")),
    ("pc_chrome_140_win_arm64", "chrome", "older", _chrome_arm64_ua("140.0.7301.21"), 1, ("windows", "chromium", "arm64", "older")),
    ("pc_edge_150_win_arm64", "edge", "stable", _edge_arm64_ua("150.0.0.0", "150.0.4078.48"), 1, ("windows", "chromium", "edge", "arm64")),
    ("pc_edge_149_win_arm64", "edge", "stable", _edge_arm64_ua("149.0.0.0", "149.0.4022.52"), 1, ("windows", "chromium", "edge", "arm64")),
    ("pc_edge_148_win_arm64", "edge", "stable", _edge_arm64_ua("148.0.0.0", "148.0.3967.54"), 1, ("windows", "chromium", "edge", "arm64")),
    ("pc_edge_147_win_arm64", "edge", "stable", _edge_arm64_ua("147.0.0.0", "147.0.3780.22"), 1, ("windows", "chromium", "edge", "arm64")),
    ("pc_edge_146_win_arm64", "edge", "stable", _edge_arm64_ua("146.0.0.0", "146.0.3733.99"), 1, ("windows", "chromium", "edge", "arm64")),
    ("pc_edge_145_win_arm64", "edge", "stable", _edge_arm64_ua("145.0.0.0", "145.0.3686.65"), 1, ("windows", "chromium", "edge", "arm64")),
    ("pc_edge_144_win_arm64", "edge", "older", _edge_arm64_ua("144.0.0.0", "144.0.3639.33"), 1, ("windows", "chromium", "edge", "arm64", "older")),
    ("pc_edge_143_win_arm64", "edge", "older", _edge_arm64_ua("143.0.0.0", "143.0.3592.112"), 1, ("windows", "chromium", "edge", "arm64", "older")),
    ("pc_edge_142_win_arm64", "edge", "older", _edge_arm64_ua("142.0.0.0", "142.0.3545.78"), 1, ("windows", "chromium", "edge", "arm64", "older")),
    ("pc_edge_141_win_arm64", "edge", "older", _edge_arm64_ua("141.0.0.0", "141.0.3498.44"), 1, ("windows", "chromium", "edge", "arm64", "older")),
    ("pc_edge_140_win_arm64", "edge", "older", _edge_arm64_ua("140.0.0.0", "140.0.3451.12"), 1, ("windows", "chromium", "edge", "arm64", "older")),

    # macOS PC-class Chrome/Edge UA strings. Keep these in the PC catalog, not
    # mobile, because they are desktop/laptop browsers.
    (
        "pc_chrome_149_macos",
        "chrome",
        "stable",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36",
        7,
        ("mac", "chromium"),
    ),
    (
        "pc_chrome_148_macos",
        "chrome",
        "stable",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",
        10,
        ("mac", "chromium"),
    ),
    (
        "pc_edge_149_macos",
        "edge",
        "stable",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36 Edg/149.0.0.0",
        3,
        ("mac", "chromium", "edge"),
    ),
)


def build_pc_user_agent_profile(row: tuple[str, str, str, str, int, tuple[str, ...]]) -> dict[str, object]:
    profile_id, browser, channel, ua_string, weight, tags = row
    ua_data = generate_ua_data_from_ua(ua_string)
    headers = generate_headers_from_ua(ua_string)
    base_platform = get_base_platform(ua_string)
    return {
        "id": profile_id,
        "browser": browser,
        "channel": channel,
        "weight": weight,
        "tags": tags,
        "userAgent": ua_string,
        "appVersion": _app_version_from_ua(ua_string),
        "platform": base_platform,
        "userAgentData": ua_data,
        "headers": headers,
        "navigator": {
            "userAgent": ua_string,
            "appVersion": _app_version_from_ua(ua_string),
            "platform": base_platform,
            "vendor": "Google Inc.",
            "userAgentData": ua_data,
        },
    }


def build_pc_user_agent_profile_from_ua(
    user_agent: str,
    profile_id: str = "custom_user_agent",
    browser: str | None = None,
) -> dict[str, object]:
    original_ua_string = str(user_agent or "").strip()
    ua_string = normalize_pc_user_agent_version(original_ua_string)
    if not ua_string:
        raise ValueError("user_agent is required")
    browser_name = browser or ("edge" if " Edg/" in ua_string else "chrome")
    version_options = _custom_full_version_options(original_ua_string)
    ua_data = generate_ua_data_from_ua(ua_string, version_options)
    headers = generate_headers_from_ua(ua_string, version_options)
    base_platform = get_base_platform(ua_string)
    tags = ("custom",)
    if "ARM64" in ua_string.upper():
        tags = ("custom", "arm64")
    return {
        "id": profile_id,
        "browser": browser_name,
        "channel": "custom",
        "weight": 1,
        "tags": tags,
        "userAgent": ua_string,
        "appVersion": _app_version_from_ua(ua_string),
        "platform": base_platform,
        "userAgentData": ua_data,
        "headers": headers,
        "navigator": {
            "userAgent": ua_string,
            "appVersion": _app_version_from_ua(ua_string),
            "platform": base_platform,
            "vendor": "Google Inc.",
            "userAgentData": ua_data,
        },
    }


PC_USER_AGENT_PROFILES: tuple[dict[str, object], ...] = tuple(
    build_pc_user_agent_profile(row) for row in PC_USER_AGENT_ROWS
)


def get_pc_user_agent_profiles(
    browser: str | None = None,
    tag: str | None = None,
) -> tuple[dict[str, object], ...]:
    browser_key = str(browser or "").strip().lower()
    tag_key = str(tag or "").strip().lower()
    output = []
    for profile in PC_USER_AGENT_PROFILES:
        if browser_key and str(profile.get("browser", "")).lower() != browser_key:
            continue
        if tag_key:
            tags = tuple(str(item).lower() for item in profile.get("tags", ()))
            if tag_key not in tags:
                continue
        output.append(profile)
    return tuple(output)


def choose_pc_user_agent_profile(
    rng: random.Random,
    browser: str | None = None,
    tag: str | None = None,
) -> dict[str, object]:
    profiles = get_pc_user_agent_profiles(browser=browser, tag=tag)
    if not profiles:
        profiles = PC_USER_AGENT_PROFILES
    weights = [int(profile.get("weight", 1)) for profile in profiles]
    return rng.choices(profiles, weights=weights, k=1)[0]


def build_pc_user_agent_patch(profile: dict[str, object]) -> dict[str, object]:
    return {
        "navigator": profile.get("navigator", {}),
        "userAgentData": profile.get("userAgentData", {}),
        "headers": profile.get("headers", {}),
        "userAgentProfileId": profile.get("id", ""),
        "browser": profile.get("browser", ""),
        "browserChannel": profile.get("channel", ""),
    }


def iter_pc_user_agents(browser: str | None = None) -> Iterable[str]:
    for profile in get_pc_user_agent_profiles(browser=browser):
        yield str(profile.get("userAgent", ""))
