"""Windows 11 font inventories for generated Chromium profiles."""

from __future__ import annotations


MICROSOFT_WINDOWS_11_FONT_SOURCE = (
    "https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list"
)

WINDOWS_CORE_FONT_FAMILIES: tuple[str, ...] = (
    "Arial",
    "Arial Black",
    "Bahnschrift",
    "Calibri",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Cascadia Code",
    "Cascadia Mono",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Corbel",
    "Courier New",
    "Ebrima",
    "Franklin Gothic Medium",
    "Gabriola",
    "Gadugi",
    "Georgia",
    "HoloLens MDL2 Assets",
    "Impact",
    "Ink Free",
    "Javanese Text",
    "Leelawadee UI",
    "Lucida Console",
    "Lucida Sans Unicode",
    "Malgun Gothic",
    "Marlett",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei UI",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft YaHei UI",
    "Microsoft Yi Baiti",
    "MingLiU-ExtB",
    "PMingLiU-ExtB",
    "MingLiU_HKSCS-ExtB",
    "Mongolian Baiti",
    "MS Gothic",
    "MS PGothic",
    "MS UI Gothic",
    "MV Boli",
    "Myanmar Text",
    "Nirmala UI",
    "NSimSun",
    "Palatino Linotype",
    "Segoe Fluent Icons",
    "Segoe MDL2 Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Symbol",
    "Segoe UI Variable",
    "SimSun",
    "SimSun-ExtB",
    "Sitka Banner",
    "Sitka Display",
    "Sitka Heading",
    "Sitka Small",
    "Sitka Subheading",
    "Sitka Text",
    "Sylfaen",
    "Symbol",
    "Tahoma",
    "Times New Roman",
    "Trebuchet MS",
    "Verdana",
    "Webdings",
    "Wingdings",
    "Yu Gothic",
    "Yu Gothic UI",
)

WINDOWS_CORE_LOCAL_FONTS: tuple[tuple[str, str, str, str], ...] = (
    ("ArialMT", "Arial", "Arial", "Regular"),
    ("Arial-Black", "Arial Black", "Arial", "Black"),
    ("Bahnschrift", "Bahnschrift", "Bahnschrift", "Regular"),
    ("Calibri", "Calibri", "Calibri", "Regular"),
    ("Cambria", "Cambria", "Cambria", "Regular"),
    ("CambriaMath", "Cambria Math", "Cambria Math", "Regular"),
    ("Candara", "Candara", "Candara", "Regular"),
    ("CascadiaCode-Roman", "Cascadia Code Regular", "Cascadia Code", "Roman"),
    ("CascadiaMono-Roman", "Cascadia Mono Regular", "Cascadia Mono", "Roman"),
    ("ComicSansMS", "Comic Sans MS", "Comic Sans MS", "Regular"),
    ("Consolas", "Consolas", "Consolas", "Regular"),
    ("Constantia", "Constantia", "Constantia", "Regular"),
    ("Corbel", "Corbel", "Corbel", "Regular"),
    ("CourierNewPSMT", "Courier New", "Courier New", "Regular"),
    ("Ebrima", "Ebrima", "Ebrima", "Regular"),
    ("FranklinGothic-Medium", "Franklin Gothic Medium", "Franklin Gothic Medium", "Regular"),
    ("Gabriola", "Gabriola", "Gabriola", "Regular"),
    ("Gadugi", "Gadugi", "Gadugi", "Regular"),
    ("Georgia", "Georgia", "Georgia", "Regular"),
    ("HoloLensMDL2Assets", "HoloLens MDL2 Assets", "HoloLens MDL2 Assets", "Regular"),
    ("Impact", "Impact", "Impact", "Regular"),
    ("InkFree", "Ink Free", "Ink Free", "Regular"),
    ("JavaneseText", "Javanese Text", "Javanese Text", "Regular"),
    ("LeelawadeeUI", "Leelawadee UI", "Leelawadee UI", "Regular"),
    ("LucidaConsole", "Lucida Console", "Lucida Console", "Regular"),
    ("LucidaSansUnicode", "Lucida Sans Unicode", "Lucida Sans Unicode", "Regular"),
    ("MalgunGothic", "Malgun Gothic", "Malgun Gothic", "Regular"),
    ("Marlett", "Marlett", "Marlett", "Regular"),
    ("Microsoft Himalaya", "Microsoft Himalaya", "Microsoft Himalaya", "Regular"),
    ("MicrosoftJhengHeiRegular", "Microsoft JhengHei", "Microsoft JhengHei", "Regular"),
    ("MicrosoftJhengHeiUIRegular", "Microsoft JhengHei UI", "Microsoft JhengHei UI", "Regular"),
    ("MicrosoftNewTaiLue", "Microsoft New Tai Lue", "Microsoft New Tai Lue", "Regular"),
    ("MicrosoftPhagsPa", "Microsoft PhagsPa", "Microsoft PhagsPa", "Regular"),
    ("MicrosoftSansSerif", "Microsoft Sans Serif", "Microsoft Sans Serif", "Regular"),
    ("MicrosoftTaiLe", "Microsoft Tai Le", "Microsoft Tai Le", "Regular"),
    ("MicrosoftYaHei", "Microsoft YaHei", "Microsoft YaHei", "Regular"),
    ("MicrosoftYaHeiUI", "Microsoft YaHei UI", "Microsoft YaHei UI", "Regular"),
    ("Microsoft-Yi-Baiti", "Microsoft Yi Baiti", "Microsoft Yi Baiti", "Regular"),
    ("MingLiU-ExtB", "MingLiU-ExtB", "MingLiU-ExtB", "Regular"),
    ("PMingLiU-ExtB", "PMingLiU-ExtB", "PMingLiU-ExtB", "Regular"),
    ("Ming-Lt-HKSCS-ExtB", "MingLiU_HKSCS-ExtB", "MingLiU_HKSCS-ExtB", "Regular"),
    ("MongolianBaiti", "Mongolian Baiti", "Mongolian Baiti", "Regular"),
    ("MS-Gothic", "MS Gothic", "MS Gothic", "Regular"),
    ("MS-PGothic", "MS PGothic", "MS PGothic", "Regular"),
    ("MS-UIGothic", "MS UI Gothic", "MS UI Gothic", "Regular"),
    ("MVBoli", "MV Boli", "MV Boli", "Regular"),
    ("MyanmarText", "Myanmar Text", "Myanmar Text", "Regular"),
    ("NirmalaUI", "Nirmala UI", "Nirmala UI", "Regular"),
    ("NSimSun", "NSimSun", "NSimSun", "Regular"),
    ("PalatinoLinotype-Roman", "Palatino Linotype", "Palatino Linotype", "Regular"),
    ("SegoeFluentIcons", "Segoe Fluent Icons", "Segoe Fluent Icons", "Regular"),
    ("SegoeMDL2Assets", "Segoe MDL2 Assets", "Segoe MDL2 Assets", "Regular"),
    ("SegoePrint", "Segoe Print", "Segoe Print", "Regular"),
    ("SegoeScript", "Segoe Script", "Segoe Script", "Regular"),
    ("SegoeUI", "Segoe UI", "Segoe UI", "Regular"),
    ("SegoeUIEmoji", "Segoe UI Emoji", "Segoe UI Emoji", "Regular"),
    ("SegoeUIHistoric", "Segoe UI Historic", "Segoe UI Historic", "Regular"),
    ("SegoeUISymbol", "Segoe UI Symbol", "Segoe UI Symbol", "Regular"),
    ("SegoeUIVariable", "Segoe UI Variable", "Segoe UI Variable", "Regular"),
    ("SimSun", "SimSun", "SimSun", "Regular"),
    ("SimSun-ExtB", "SimSun-ExtB", "SimSun-ExtB", "Regular"),
    ("Sylfaen", "Sylfaen", "Sylfaen", "Regular"),
    ("SymbolMT", "Symbol", "Symbol", "Regular"),
    ("Tahoma", "Tahoma", "Tahoma", "Regular"),
    ("TimesNewRomanPSMT", "Times New Roman", "Times New Roman", "Regular"),
    ("TrebuchetMS", "Trebuchet MS", "Trebuchet MS", "Regular"),
    ("Verdana", "Verdana", "Verdana", "Regular"),
    ("Webdings", "Webdings", "Webdings", "Regular"),
    ("Wingdings-Regular", "Wingdings", "Wingdings", "Regular"),
    ("YuGothic-Regular", "Yu Gothic Regular", "Yu Gothic", "Regular"),
    ("YuGothicUI-Regular", "Yu Gothic UI Regular", "Yu Gothic UI", "Regular"),
)

WINDOWS_CORE_FONT_METRICS: tuple[tuple[str, float, bool], ...] = (
    # Ratios measured against Arial with GDI+ GenericTypographic using the
    # fixed reference text "Sphinx of black quartz 0123456789" on the
    # Windows 11 reference host.  Unsupported icon faces are excluded rather
    # than assigned invented 1.0 values.
    ("Arial", 1.000000, False),
    ("Arial Black", 1.226479, False),
    ("Bahnschrift", 0.981220, False),
    ("Calibri", 0.907191, False),
    ("Cambria", 0.972126, False),
    ("Cambria Math", 0.972126, False),
    ("Candara", 0.931047, False),
    ("Cascadia Code", 1.233299, True),
    ("Cascadia Mono", 1.233299, True),
    ("Comic Sans MS", 1.074527, False),
    ("Consolas", 1.157246, True),
    ("Constantia", 0.949578, False),
    ("Corbel", 0.907907, False),
    ("Courier New", 1.263104, True),
    ("Ebrima", 0.984646, False),
    ("Franklin Gothic Medium", 0.995266, False),
    ("Gabriola", 0.684715, False),
    ("Gadugi", 0.984646, False),
    ("Georgia", 0.994176, False),
    ("Impact", 0.900526, False),
    ("Ink Free", 1.010829, False),
    ("Javanese Text", 0.976891, False),
    ("Leelawadee UI", 0.984646, False),
    ("Lucida Console", 1.268243, True),
    ("Lucida Sans Unicode", 1.123112, False),
    ("Malgun Gothic", 1.023483, False),
    ("Microsoft Himalaya", 0.612352, False),
    ("Microsoft JhengHei", 1.046622, False),
    ("Microsoft JhengHei UI", 1.046622, False),
    ("Microsoft New Tai Lue", 0.984646, False),
    ("Microsoft PhagsPa", 0.984646, False),
    ("Microsoft Sans Serif", 0.997633, False),
    ("Microsoft Tai Le", 0.984646, False),
    ("Microsoft YaHei", 1.072129, False),
    ("Microsoft YaHei UI", 1.072129, False),
    ("Microsoft Yi Baiti", 0.868853, False),
    ("Mongolian Baiti", 0.914074, False),
    ("MS Gothic", 1.052415, True),
    ("MS PGothic", 0.929584, True),
    ("MS UI Gothic", 0.929584, True),
    ("MV Boli", 1.115170, False),
    ("Myanmar Text", 0.984646, False),
    ("Nirmala UI", 0.984646, False),
    ("Palatino Linotype", 0.969790, False),
    ("Segoe Print", 1.214924, False),
    ("Segoe Script", 1.301598, False),
    ("Segoe UI", 0.984646, False),
    ("Segoe UI Emoji", 0.984646, False),
    ("Segoe UI Historic", 0.984646, False),
    ("Segoe UI Symbol", 0.984646, False),
    ("SimSun", 1.052415, False),
    ("NSimSun", 1.052415, False),
    ("Sitka Banner", 0.852421, False),
    ("Sitka Display", 0.887771, False),
    ("Sitka Heading", 0.932078, False),
    ("Sitka Small", 1.143384, False),
    ("Sitka Subheading", 0.985146, False),
    ("Sitka Text", 1.056100, False),
    ("Sylfaen", 0.933072, False),
    ("Tahoma", 0.992401, False),
    ("Times New Roman", 0.914074, False),
    ("Trebuchet MS", 0.991062, False),
    ("Verdana", 1.146439, False),
    ("Yu Gothic", 1.024791, False),
    ("Yu Gothic UI", 0.984646, False),
)

_LANGUAGE_FONT_ADDITIONS: dict[
    str,
    tuple[
        tuple[str, ...],
        tuple[tuple[str, str, str, str], ...],
        tuple[tuple[str, float, bool], ...],
    ],
] = {
    "ar": (
        (
            "Aldhabi", "Andalus", "Arabic Typesetting", "Microsoft Uighur",
            "Sakkal Majalla", "Simplified Arabic", "Traditional Arabic",
            "Urdu Typesetting",
        ),
        (),
        (),
    ),
    "fa": (
        ("Aldhabi", "Arabic Typesetting", "Simplified Arabic", "Traditional Arabic"),
        (),
        (),
    ),
    "ur": (
        ("Urdu Typesetting", "Arabic Typesetting", "Traditional Arabic"),
        (),
        (),
    ),
    "bn": (("Shonar Bangla", "Vrinda"), (), ()),
    "as": (("Shonar Bangla", "Vrinda"), (), ()),
    "iu": (("Euphemia",), (), ()),
    "chr": (("Plantagenet Cherokee",), (), ()),
    "hi": (("Aparajita", "Kokila", "Mangal", "Sanskrit Text", "Utsaah"), (), ()),
    "mr": (("Aparajita", "Kokila", "Mangal", "Sanskrit Text", "Utsaah"), (), ()),
    "kok": (("Aparajita", "Kokila", "Mangal", "Sanskrit Text", "Utsaah"), (), ()),
    "ne": (("Aparajita", "Kokila", "Mangal", "Sanskrit Text", "Utsaah"), (), ()),
    "am": (("Nyala",), (), ()),
    "ti": (("Nyala",), (), ()),
    "gu": (("Shruti",), (), ()),
    "pa": (("Raavi",), (), ()),
    "zh-cn": (
        ("DengXian", "FangSong", "KaiTi", "SimHei"),
        (
            ("DengXian", "DengXian Regular", "DengXian", "Regular"),
            ("DengXian-Bold", "DengXian Bold", "DengXian", "Bold"),
            ("DengXian-Light", "DengXian Light", "DengXian", "Light"),
            ("FangSong", "FangSong", "FangSong", "Regular"),
            ("KaiTi", "KaiTi", "KaiTi", "Regular"),
            ("SimHei", "SimHei", "SimHei", "Regular"),
        ),
        (
            ("DengXian", 0.959700, False),
            ("FangSong", 1.052415, False),
            ("KaiTi", 1.052415, False),
            ("SimHei", 1.052415, False),
        ),
    ),
    "zh-sg": (
        ("DengXian", "FangSong", "KaiTi", "SimHei"),
        (
            ("DengXian", "DengXian Regular", "DengXian", "Regular"),
            ("FangSong", "FangSong", "FangSong", "Regular"),
            ("KaiTi", "KaiTi", "KaiTi", "Regular"),
            ("SimHei", "SimHei", "SimHei", "Regular"),
        ),
        (
            ("DengXian", 0.959700, False),
            ("FangSong", 1.052415, False),
            ("KaiTi", 1.052415, False),
            ("SimHei", 1.052415, False),
        ),
    ),
    "zh-tw": (
        ("DFKai-SB", "MingLiU", "MingLiU_HKSCS", "PMingLiU"),
        (),
        (),
    ),
    "zh-hk": (
        ("DFKai-SB", "MingLiU", "MingLiU_HKSCS", "PMingLiU"),
        (),
        (),
    ),
    "he": (("Aharoni", "David", "FrankRuehl", "Gisha", "Levenim MT", "Miriam", "Narkisim", "Rod"), (), ()),
    "yi": (("Aharoni", "David", "FrankRuehl", "Gisha", "Miriam", "Narkisim"), (), ()),
    "ja": (
        (
            "BIZ UDGothic", "BIZ UDPGothic", "BIZ UDMincho Medium",
            "BIZ UDPMincho Medium", "Meiryo", "Meiryo UI", "MS Mincho",
            "MS PMincho", "UD Digi Kyokasho N-B", "UD Digi Kyokasho N-R",
            "UD Digi Kyokasho NK-B", "UD Digi Kyokasho NK-R",
            "UD Digi Kyokasho NP-B", "UD Digi Kyokasho NP-R", "Yu Mincho",
        ),
        (),
        (),
    ),
    "kn": (("Tunga",), (), ()),
    "km": (("DaunPenh", "Khmer UI", "MoolBoran"), (), ()),
    "ko": (
        ("Batang", "BatangChe", "Dotum", "DotumChe", "Gulim", "GulimChe", "Gungsuh", "GungsuhChe"),
        (),
        (),
    ),
    "lo": (("DokChampa", "Lao UI"), (), ()),
    "ml": (("Kartika",), (), ()),
    "or": (("Kalinga",), (), ()),
    "si": (("Iskoola Pota",), (), ()),
    "syr": (("Estrangelo Edessa",), (), ()),
    "ta": (("Latha", "Vijaya"), (), ()),
    "te": (("Gautami", "Vani"), (), ()),
    "th": (
        (
            "Angsana New", "AngsanaUPC", "Browallia New", "BrowalliaUPC",
            "Cordia New", "CordiaUPC", "DilleniaUPC", "EucrosiaUPC",
            "FreesiaUPC", "IrisUPC", "JasmineUPC", "KodchiangUPC",
            "Leelawadee", "LilyUPC",
        ),
        (),
        (),
    ),
}


def _language_key(locale: str) -> str:
    normalized = str(locale).strip().replace("_", "-").lower()
    if normalized in _LANGUAGE_FONT_ADDITIONS:
        return normalized
    return normalized.split("-", 1)[0]


def build_windows_font_profile(locale: str) -> dict[str, object]:
    additions = _LANGUAGE_FONT_ADDITIONS.get(_language_key(locale), ((), (), ()))
    return {
        "id": f"windows-11-{_language_key(locale) or 'default'}",
        "source": MICROSOFT_WINDOWS_11_FONT_SOURCE,
        "families": tuple(dict.fromkeys((*WINDOWS_CORE_FONT_FAMILIES, *additions[0]))),
        "allowUnknownFamilies": False,
        "localFonts": tuple(dict.fromkeys((*WINDOWS_CORE_LOCAL_FONTS, *additions[1]))),
        "metrics": tuple(dict.fromkeys((*WINDOWS_CORE_FONT_METRICS, *additions[2]))),
    }


__all__ = [
    "MICROSOFT_WINDOWS_11_FONT_SOURCE",
    "WINDOWS_CORE_FONT_FAMILIES",
    "WINDOWS_CORE_FONT_METRICS",
    "WINDOWS_CORE_LOCAL_FONTS",
    "build_windows_font_profile",
]
