"""Complete Windows Chromium 150 baseline for the Edge sandbox.

The random country-profile composer starts from this platform-specific
baseline and then replaces locale, hardware, display, font, and GPU choices.
Keeping the baseline independent from the macOS preset prevents platform
values from leaking through fields that a caller did not explicitly replace.
"""

from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

try:
    from .edge_profile import (
        BatteryProfile,
        CanvasProfile,
        CssProfile,
        EdgeProfile,
        FontMetricProfile,
        FontProfile,
        GeolocationProfile,
        HardwareDevicesProfile,
        LocalFontProfile,
        LocaleProfile,
        MediaDeviceProfile,
        MediaPreferencesProfile,
        MediaProfile,
        MemoryProfile,
        MimeTypeProfile,
        NavigatorProfile,
        NetworkProfile,
        PermissionsProfile,
        PluginListProfile,
        PluginProfile,
        RtcCodecProfile,
        RtcHeaderExtensionProfile,
        ScreenProfile,
        SensorsProfile,
        SpeechProfile,
        SpeechVoiceProfile,
        StorageProfile,
        TimingProfile,
        UserAgentBrandProfile,
        UserAgentDataProfile,
        WebAudioProfile,
        WebGlProfile,
        WebGpuProfile,
        WindowProfile,
        XrProfile,
    )
except ImportError:
    from edge_profile import (
        BatteryProfile,
        CanvasProfile,
        CssProfile,
        EdgeProfile,
        FontMetricProfile,
        FontProfile,
        GeolocationProfile,
        HardwareDevicesProfile,
        LocalFontProfile,
        LocaleProfile,
        MediaDeviceProfile,
        MediaPreferencesProfile,
        MediaProfile,
        MemoryProfile,
        MimeTypeProfile,
        NavigatorProfile,
        NetworkProfile,
        PermissionsProfile,
        PluginListProfile,
        PluginProfile,
        RtcCodecProfile,
        RtcHeaderExtensionProfile,
        ScreenProfile,
        SensorsProfile,
        SpeechProfile,
        SpeechVoiceProfile,
        StorageProfile,
        TimingProfile,
        UserAgentBrandProfile,
        UserAgentDataProfile,
        WebAudioProfile,
        WebGlProfile,
        WebGpuProfile,
        WindowProfile,
        XrProfile,
    )


CHROMIUM_150_FULL_VERSION = "150.0.0.0"
WINDOWS_CHROME_150_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    f"Chrome/{CHROMIUM_150_FULL_VERSION} Safari/537.36"
)

WINDOWS_WEBGL1_EXTENSIONS = (
    "ANGLE_instanced_arrays",
    "EXT_blend_minmax",
    "EXT_color_buffer_half_float",
    "EXT_float_blend",
    "EXT_frag_depth",
    "EXT_shader_texture_lod",
    "EXT_texture_compression_bptc",
    "EXT_texture_filter_anisotropic",
    "OES_element_index_uint",
    "OES_fbo_render_mipmap",
    "OES_standard_derivatives",
    "OES_texture_float",
    "OES_texture_float_linear",
    "OES_texture_half_float",
    "OES_texture_half_float_linear",
    "OES_vertex_array_object",
    "WEBGL_color_buffer_float",
    "WEBGL_compressed_texture_s3tc",
    "WEBGL_compressed_texture_s3tc_srgb",
    "WEBGL_debug_renderer_info",
    "WEBGL_debug_shaders",
    "WEBGL_depth_texture",
    "WEBGL_draw_buffers",
    "WEBGL_lose_context",
    "WEBGL_multi_draw",
)

WINDOWS_WEBGL2_EXTENSIONS = (
    "EXT_color_buffer_float",
    "EXT_color_buffer_half_float",
    "EXT_float_blend",
    "EXT_texture_compression_bptc",
    "EXT_texture_filter_anisotropic",
    "OES_draw_buffers_indexed",
    "OES_texture_float_linear",
    "WEBGL_compressed_texture_s3tc",
    "WEBGL_compressed_texture_s3tc_srgb",
    "WEBGL_debug_renderer_info",
    "WEBGL_debug_shaders",
    "WEBGL_lose_context",
    "WEBGL_multi_draw",
)

WINDOWS_COMPRESSED_TEXTURE_FORMATS = (
    *range(0x83F0, 0x83F4),
    *range(0x8C4C, 0x8C50),
    *range(0x8E8C, 0x8E90),
)

WINDOWS_FONT_FAMILIES = (
    "Arial",
    "Calibri",
    "Cambria",
    "Consolas",
    "Courier New",
    "Microsoft Sans Serif",
    "Microsoft YaHei",
    "Segoe UI",
    "Tahoma",
    "Times New Roman",
    "Verdana",
)

WINDOWS_LOCAL_FONTS = (
    LocalFontProfile("ArialMT", "Arial", "Arial", "Regular"),
    LocalFontProfile("Calibri", "Calibri", "Calibri", "Regular"),
    LocalFontProfile("Cambria", "Cambria", "Cambria", "Regular"),
    LocalFontProfile("Consolas", "Consolas", "Consolas", "Regular"),
    LocalFontProfile("SegoeUI", "Segoe UI", "Segoe UI", "Regular"),
    LocalFontProfile("Tahoma", "Tahoma", "Tahoma", "Regular"),
    LocalFontProfile("TimesNewRomanPSMT", "Times New Roman", "Times New Roman", "Regular"),
    LocalFontProfile("Verdana", "Verdana", "Verdana", "Regular"),
)

WINDOWS_FONT_METRICS = (
    FontMetricProfile("Arial", 1.0, False),
    FontMetricProfile("Consolas", 1.0, True),
    FontMetricProfile("Courier New", 1.0, True),
    FontMetricProfile("Segoe UI", 1.0, False),
)


def _time_zone_offset(time_zone: str) -> int:
    try:
        zone = ZoneInfo(time_zone)
    except ZoneInfoNotFoundError as exc:
        raise ValueError(f"unknown IANA time zone: {time_zone}") from exc
    offset = datetime.now(zone).utcoffset()
    return 0 if offset is None else -int(offset.total_seconds() // 60)


def _pdf_plugins() -> PluginListProfile:
    mime_types = (
        MimeTypeProfile("application/pdf", "pdf", "Portable Document Format"),
        MimeTypeProfile("text/pdf", "pdf", "Portable Document Format"),
    )
    return PluginListProfile(
        plugins=tuple(
            PluginProfile(
                name=name,
                filename="internal-pdf-viewer",
                description="Portable Document Format",
                mime_types=mime_types,
            )
            for name in (
                "PDF Viewer",
                "Chrome PDF Viewer",
                "Chromium PDF Viewer",
                "Microsoft Edge PDF Viewer",
                "WebKit built-in PDF",
            )
        )
    )


def windows_edge_150_profile(
    *,
    windows_platform_version: str = "19.0.0",
    locale: str = "en-US",
    time_zone: str = "UTC",
    time_zone_offset_minutes: int | None = None,
    hardware_concurrency: int = 16,
    device_memory_gb: float = 8.0,
    screen_width: int = 1920,
    screen_height: int = 1080,
    avail_height: int = 1040,
    inner_width: float = 0.0,
    inner_height: float = 0.0,
    device_pixel_ratio: float = 1.0,
    font_families: tuple[str, ...] | None = None,
    local_fonts: tuple[LocalFontProfile, ...] | None = None,
    font_metrics: tuple[FontMetricProfile, ...] | None = None,
    allow_unknown_font_families: bool = False,
    local_fonts_permission: str = "prompt",
) -> EdgeProfile:
    """Return a complete Windows Chromium 150 baseline profile."""

    if not windows_platform_version:
        raise ValueError("windows_platform_version must not be empty")
    if screen_width <= 0 or screen_height <= 0 or avail_height <= 0:
        raise ValueError("Windows screen dimensions must be positive")
    if inner_width < 0 or inner_height < 0 or device_pixel_ratio <= 0:
        raise ValueError("Windows window dimensions and DPR are outside supported bounds")
    if hardware_concurrency <= 0 or device_memory_gb <= 0:
        raise ValueError("Windows hardware values must be positive")

    resolved_offset = (
        _time_zone_offset(time_zone)
        if time_zone_offset_minutes is None
        else time_zone_offset_minutes
    )
    resolved_families = WINDOWS_FONT_FAMILIES if font_families is None else tuple(font_families)
    resolved_local_fonts = WINDOWS_LOCAL_FONTS if local_fonts is None else tuple(local_fonts)
    resolved_metrics = WINDOWS_FONT_METRICS if font_metrics is None else tuple(font_metrics)

    renderer = (
        "ANGLE (Microsoft, Microsoft Basic Render Driver (0x0000008C) "
        "Direct3D11 vs_5_0 ps_5_0, D3D11)"
    )

    return EdgeProfile(
        id="windows-chrome-150-d3d11",
        locale=LocaleProfile(locale, time_zone, resolved_offset),
        navigator=NavigatorProfile(
            user_agent=WINDOWS_CHROME_150_USER_AGENT,
            app_version=WINDOWS_CHROME_150_USER_AGENT.removeprefix("Mozilla/"),
            app_code_name="Mozilla",
            app_name="Netscape",
            platform="Win32",
            product="Gecko",
            product_sub="20030107",
            vendor="Google Inc.",
            vendor_sub="",
            language=locale,
            languages=(locale, "en"),
            hardware_concurrency=hardware_concurrency,
            device_memory_gb=device_memory_gb,
            max_touch_points=0,
            cookie_enabled=True,
            on_line=True,
            webdriver=False,
            pdf_viewer_enabled=True,
            do_not_track=None,
            user_agent_data=UserAgentDataProfile(
                brands=(
                    UserAgentBrandProfile("Not;A=Brand", "8", "8.0.0.0"),
                    UserAgentBrandProfile("Chromium", "150", CHROMIUM_150_FULL_VERSION),
                    UserAgentBrandProfile("Google Chrome", "150", CHROMIUM_150_FULL_VERSION),
                ),
                mobile=False,
                platform="Windows",
                architecture="x86",
                bitness="64",
                model="",
                platform_version=windows_platform_version,
                ua_full_version=CHROMIUM_150_FULL_VERSION,
                wow64=False,
                form_factors=("Desktop",),
            ),
            network=NetworkProfile("4g", 50, 10.0, False),
        ),
        screen=ScreenProfile(
            width=screen_width,
            height=screen_height,
            avail_width=screen_width,
            avail_height=avail_height,
            avail_left=0,
            avail_top=0,
            color_depth=24,
            pixel_depth=24,
            viewport_width=inner_width,
            viewport_height=inner_height,
            outer_width=float(screen_width),
            outer_height=float(avail_height),
            screen_x=0.0,
            screen_y=0.0,
            device_pixel_ratio=device_pixel_ratio,
            orientation_type="landscape-primary",
            orientation_angle=0,
            visual_viewport_offset_left=0.0,
            visual_viewport_offset_top=0.0,
            visual_viewport_page_left=0.0,
            visual_viewport_page_top=0.0,
            visual_viewport_scale=1.0,
        ),
        window=WindowProfile(inner_width, inner_height, float(screen_width), float(avail_height)),
        canvas=CanvasProfile(
            data_url_salt="",
            text_width_scale=1.0,
            actual_bounding_box_left=0.0,
            actual_bounding_box_right_scale=1.0,
            font_bounding_box_ascent=12.0,
            font_bounding_box_descent=3.0,
            actual_bounding_box_ascent=8.0,
            actual_bounding_box_descent=1.0,
            hanging_baseline=9.600000381469727,
            alphabetic_baseline=0.0,
            ideographic_baseline=-1.1999969482421875,
        ),
        webgl=WebGlProfile(
            vendor="WebKit",
            renderer="WebKit WebGL",
            unmasked_vendor="Google Inc. (Microsoft)",
            unmasked_renderer=renderer,
            webgl1_version="WebGL 1.0 (OpenGL ES 2.0 Chromium)",
            webgl1_shading_language_version="WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)",
            webgl2_version="WebGL 2.0 (OpenGL ES 3.0 Chromium)",
            webgl2_shading_language_version="WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)",
            webgl1_extensions=WINDOWS_WEBGL1_EXTENSIONS,
            webgl2_extensions=WINDOWS_WEBGL2_EXTENSIONS,
            compressed_texture_formats=WINDOWS_COMPRESSED_TEXTURE_FORMATS,
            max_texture_size=16_384,
            max_cube_map_texture_size=16_384,
            max_renderbuffer_size=16_384,
            max_viewport_width=32_767,
            max_viewport_height=32_767,
            max_vertex_attribs=16,
            max_vertex_uniform_vectors=4_096,
            max_varying_vectors=30,
            max_fragment_uniform_vectors=1_024,
            max_vertex_texture_image_units=16,
            max_texture_image_units=16,
            max_combined_texture_image_units=32,
            subpixel_bits=4,
            webgl2_max_3d_texture_size=2_048,
            webgl2_max_array_texture_layers=2_048,
            webgl2_max_draw_buffers=8,
            webgl2_max_color_attachments=8,
            webgl2_max_samples=16,
            webgl2_max_vertex_uniform_components=16_384,
            webgl2_max_fragment_uniform_components=4_096,
            webgl2_max_varying_components=120,
            webgl2_max_vertex_output_components=120,
            webgl2_max_fragment_input_components=120,
            webgl2_max_vertex_uniform_blocks=12,
            webgl2_max_fragment_uniform_blocks=12,
            webgl2_max_combined_uniform_blocks=24,
            webgl2_max_uniform_buffer_bindings=24,
            webgl2_max_uniform_block_size=65_536,
            webgl2_max_combined_vertex_uniform_components=212_988,
            webgl2_max_combined_fragment_uniform_components=200_704,
            webgl2_max_transform_feedback_separate_attribs=4,
            webgl2_max_transform_feedback_interleaved_components=120,
            webgl2_max_transform_feedback_separate_components=4,
            webgl2_max_program_texel_offset=7,
            webgl2_max_elements_vertices=2_147_483_647,
            webgl2_max_elements_indices=2_147_483_647,
            webgl2_max_element_index=4_294_967_294,
            webgl2_max_texture_lod_bias=2.0,
            max_anisotropy=16.0,
            aliased_point_size_min=1.0,
            aliased_point_size_max=1_024.0,
            aliased_line_width_min=1.0,
            aliased_line_width_max=1.0,
            shader_precision_range_min=127,
            shader_precision_range_max=127,
            shader_precision_bits=23,
            context_alpha=True,
            context_antialias=True,
            context_depth=True,
            context_desynchronized=False,
            context_fail_if_major_performance_caveat=False,
            context_premultiplied_alpha=True,
            context_preserve_drawing_buffer=False,
            context_stencil=False,
            context_xr_compatible=False,
            context_power_preference="default",
        ),
        webgpu=WebGpuProfile(
            vendor="Microsoft",
            architecture="D3D12",
            device="Edge WebGPU Adapter",
            description="Microsoft Edge WebGPU software adapter",
            developer_features=False,
            subgroup_min_size=4,
            subgroup_max_size=128,
            is_fallback_adapter=False,
            features=("bgra8unorm-storage", "texture-compression-bc"),
            max_texture_dimension_1d=8_192,
            max_texture_dimension_2d=8_192,
            max_texture_dimension_3d=2_048,
            max_texture_array_layers=256,
            max_bind_groups=4,
            max_bind_groups_plus_vertex_buffers=24,
            max_bindings_per_bind_group=1_000,
            max_dynamic_uniform_buffers_per_pipeline_layout=8,
            max_dynamic_storage_buffers_per_pipeline_layout=4,
            max_sampled_textures_per_shader_stage=16,
            max_samplers_per_shader_stage=16,
            max_storage_buffers_per_shader_stage=8,
            max_storage_textures_per_shader_stage=4,
            max_uniform_buffers_per_shader_stage=12,
            max_uniform_buffer_binding_size=65_536,
            max_storage_buffer_binding_size=134_217_728,
            min_uniform_buffer_offset_alignment=256,
            min_storage_buffer_offset_alignment=256,
            max_vertex_buffers=8,
            max_buffer_size=268_435_456,
            max_vertex_attributes=16,
            max_vertex_buffer_array_stride=2_048,
            max_inter_stage_shader_variables=16,
            max_color_attachments=8,
            max_color_attachment_bytes_per_sample=32,
            max_compute_workgroup_storage_size=16_384,
            max_compute_invocations_per_workgroup=256,
            max_compute_workgroup_size_x=256,
            max_compute_workgroup_size_y=256,
            max_compute_workgroup_size_z=64,
            max_compute_workgroups_per_dimension=65_535,
            max_immediate_size=0,
            max_storage_buffers_in_fragment_stage=8,
            max_storage_textures_in_fragment_stage=4,
            max_storage_buffers_in_vertex_stage=8,
            max_storage_textures_in_vertex_stage=4,
        ),
        audio=WebAudioProfile(noise_seed=0x57494E44),
        storage=StorageProfile(1_073_741_824, 0, False),
        speech=SpeechProfile(
            voices=(
                SpeechVoiceProfile("Microsoft David - English (United States)", "Microsoft David - English (United States)", "en-US", True, True),
                SpeechVoiceProfile("Microsoft Zira - English (United States)", "Microsoft Zira - English (United States)", "en-US", True, False),
            )
        ),
        fonts=FontProfile(resolved_families, allow_unknown_font_families, resolved_local_fonts, resolved_metrics),
        css=CssProfile(
            body="display:block;margin:8px",
            input_common="",
            input_hidden="display:none;width:auto;height:auto;padding:0;border-width:0",
            input_search="display:inline-block;box-sizing:border-box;width:177px;height:21px;padding:1px 2px;border-width:2px",
            input_checkbox_radio="display:inline-block;box-sizing:border-box;width:13px;height:13px;padding:0;border-width:0",
            input_range="display:inline-block;box-sizing:content-box;width:129px;height:16px;padding:0;border-width:0",
            input_color="display:inline-block;box-sizing:border-box;width:50px;height:27px;padding:1px 2px;border-width:1px",
            input_date="display:inline-block;box-sizing:content-box;width:107.328125px;height:17.328125px;padding:0 0 0 1px;border-width:2px",
            input_time="display:inline-block;box-sizing:content-box;width:67px;height:20px;padding:0 0 0 1px;border-width:2px",
            input_datetime_local="display:inline-block;box-sizing:content-box;width:153.328125px;height:17.328125px;padding:0 0 0 1px;border-width:2px",
            input_month="display:inline-block;box-sizing:content-box;width:105.328125px;height:17.328125px;padding:0 0 0 1px;border-width:2px",
            input_week="display:inline-block;box-sizing:content-box;width:133.328125px;height:17.328125px;padding:0 0 0 1px;border-width:2px",
            input_image="display:inline-block;box-sizing:content-box;width:0;height:0;padding:0;border-width:0",
            input_button="display:inline-block;box-sizing:border-box;width:16px;height:21px;padding:1px 6px;border-width:2px",
            input_submit_reset="display:inline-block;box-sizing:border-box;width:42.671875px;height:25px;padding:1px 6px;border-width:2px",
            input_file="display:inline-block;box-sizing:content-box;width:253px;height:25px;padding:0;border-width:0",
            input_text="display:inline-block;box-sizing:content-box;width:169px;height:15px;padding:1px 2px;border-width:2px",
        ),
        media=MediaProfile(
            devices=(
                MediaDeviceProfile("", "audioinput", "", ""),
                MediaDeviceProfile("", "videoinput", "", ""),
                MediaDeviceProfile("", "audiooutput", "", ""),
            ),
            supported_constraints=("width", "height"),
            can_play_probably_types=("audio/mpeg", "audio/ogg", "audio/wav", "audio/webm", "video/mp4", "video/webm"),
            can_play_maybe_types=("audio/*", "video/*"),
            media_source_types=(
                "audio/mpeg",
                "audio/webm;codecs=opus*",
                "audio/webm;codecs=vorbis*",
                "video/webm;codecs=vp8*",
                "video/webm;codecs=vp09.*",
                "video/webm;codecs=av01.*",
                "video/mp4;codecs=avc1.*",
                "video/mp4;codecs=avc3.*",
                "video/mp4;codecs=hvc1.*",
                "video/mp4;codecs=hev1.*",
                "video/mp4;codecs=av01.*",
            ),
            media_recorder_types=(
                "",
                "video/webm",
                "audio/webm",
                "video/mp4",
                "audio/mp4",
                "video/webm;codecs=vp8*",
                "video/webm;codecs=vp09.*",
                "video/webm;codecs=h264*",
                "video/webm;codecs=av01.*",
                "audio/webm;codecs=opus*",
                "audio/webm;codecs=vorbis*",
                "video/mp4;codecs=avc1.*",
                "video/mp4;codecs=avc3.*",
                "video/mp4;codecs=av01.*",
                "audio/mp4;codecs=mp4a.*",
            ),
            decoding_supported_types=("*",),
            decoding_smooth_types=("*",),
            decoding_power_efficient_types=(),
            encoding_supported_types=(),
            encoding_smooth_types=(),
            encoding_power_efficient_types=(),
            image_decoder_types=("image/*",),
            audio_decoder_codecs=("mp4a.*", "flac", "mp3", "opus", "vorbis"),
            audio_encoder_codecs=("mp4a.*", "flac", "opus"),
            video_decoder_codecs=("av01.*", "avc1.*", "h264", "vp8", "vp09.*", "vp9"),
            video_encoder_codecs=("avc1.*", "h264", "vp8", "vp09.*", "vp9"),
            rtc_audio_codecs=(
                RtcCodecProfile("audio/opus", 48_000, channels=2),
                RtcCodecProfile("audio/G722", 8_000, channels=1),
                RtcCodecProfile("audio/PCMU", 8_000, channels=1),
                RtcCodecProfile("audio/PCMA", 8_000, channels=1),
            ),
            rtc_video_codecs=(
                RtcCodecProfile("video/VP8", 90_000),
                RtcCodecProfile("video/VP9", 90_000, sdp_fmtp_line="profile-id=0"),
                RtcCodecProfile("video/H264", 90_000, sdp_fmtp_line="level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f"),
            ),
            rtc_header_extensions=(
                RtcHeaderExtensionProfile("audio", "urn:ietf:params:rtp-hdrext:ssrc-audio-level"),
                RtcHeaderExtensionProfile("video", "urn:ietf:params:rtp-hdrext:sdes:mid"),
            ),
            rtc_offer_sdp="",
            rtc_answer_sdp="",
        ),
        permissions=PermissionsProfile(
            accelerometer="granted",
            background_sync="granted",
            camera="prompt",
            clipboard_read="prompt",
            clipboard_write="granted",
            geolocation="prompt",
            gyroscope="granted",
            local_fonts=local_fonts_permission,
            magnetometer="granted",
            microphone="prompt",
            midi="prompt",
            notifications="prompt",
            payment_handler="granted",
            persistent_storage="granted",
            speaker_selection="prompt",
            storage_access="granted",
            top_level_storage_access="granted",
            window_management="granted",
        ),
        battery=BatteryProfile(True, 0.0, float("inf"), 1.0),
        geolocation=GeolocationProfile(0.0, 0.0, None, 10_000.0, None, None, None),
        media_preferences=MediaPreferencesProfile(
            color_scheme="light",
            contrast="no-preference",
            reduced_motion=False,
            reduced_data=False,
            forced_colors=False,
            inverted_colors=False,
            monochrome_bits=0,
            color_gamut="srgb",
            pointer="fine",
            any_pointer="fine",
            hover="hover",
            any_hover="hover",
            display_mode="browser",
            dynamic_range="standard",
            scripting="enabled",
        ),
        plugins=_pdf_plugins(),
        hardware_devices=HardwareDevicesProfile(
            gamepads=(),
            usb_devices=(),
            hid_devices=(),
            serial_ports=(),
            bluetooth_available=True,
            bluetooth_devices=(),
            keyboard_layout=(),
            device_posture="continuous",
            midi_inputs=(),
            midi_outputs=(),
            midi_sysex_enabled=False,
        ),
        sensors=SensorsProfile(
            available=True,
            accelerometer=(0.0, 0.0, 0.0),
            gravity=(0.0, 0.0, 0.0),
            linear_acceleration=(0.0, 0.0, 0.0),
            gyroscope=(0.0, 0.0, 0.0),
            absolute_orientation_quaternion=(0.0, 0.0, 0.0, 1.0),
            relative_orientation_quaternion=(0.0, 0.0, 0.0, 1.0),
        ),
        timing=TimingProfile(clock_step_ms=1),
        xr=XrProfile(("inline",)),
        memory=MemoryProfile(
            performance_js_heap_size_limit=4_395_630_592,
            performance_total_js_heap_size=98_833_423,
            performance_used_js_heap_size=62_981_207,
            console_js_heap_size_limit=4_395_630_592,
            console_total_js_heap_size=98_833_423,
            console_used_js_heap_size=62_981_207,
        ),
    )
