pub(crate) const EDGE_150_INITIAL_COMPUTED_VALUES: &[(&str, &str)] = &[
    (r####"accent-color"####, r####"auto"####),
    (r####"align-content"####, r####"normal"####),
    (r####"align-items"####, r####"normal"####),
    (r####"align-self"####, r####"auto"####),
    (r####"alignment-baseline"####, r####"auto"####),
    (r####"anchor-name"####, r####"none"####),
    (r####"anchor-scope"####, r####"none"####),
    (r####"animation-composition"####, r####"replace"####),
    (r####"animation-delay"####, r####"0s"####),
    (r####"animation-direction"####, r####"normal"####),
    (r####"animation-duration"####, r####"0s"####),
    (r####"animation-fill-mode"####, r####"none"####),
    (r####"animation-iteration-count"####, r####"1"####),
    (r####"animation-name"####, r####"none"####),
    (r####"animation-play-state"####, r####"running"####),
    (r####"animation-range-end"####, r####"normal"####),
    (r####"animation-range-start"####, r####"normal"####),
    (r####"animation-timeline"####, r####"auto"####),
    (r####"animation-timing-function"####, r####"ease"####),
    (r####"animation-trigger"####, r####"none"####),
    (r####"app-region"####, r####"none"####),
    (r####"appearance"####, r####"none"####),
    (r####"aspect-ratio"####, r####"auto"####),
    (r####"backdrop-filter"####, r####"none"####),
    (r####"backface-visibility"####, r####"visible"####),
    (r####"background-attachment"####, r####"scroll"####),
    (r####"background-blend-mode"####, r####"normal"####),
    (r####"background-clip"####, r####"border-box"####),
    (r####"background-color"####, r####"rgba(0, 0, 0, 0)"####),
    (r####"background-image"####, r####"none"####),
    (r####"background-origin"####, r####"padding-box"####),
    (r####"background-position"####, r####"0% 0%"####),
    (r####"background-repeat"####, r####"repeat"####),
    (r####"background-size"####, r####"auto"####),
    (r####"baseline-shift"####, r####"0px"####),
    (r####"baseline-source"####, r####"auto"####),
    (r####"block-size"####, r####"auto"####),
    (r####"border-block-end-color"####, r####"currentcolor"####),
    (r####"border-block-end-style"####, r####"none"####),
    (r####"border-block-end-width"####, r####"0px"####),
    (r####"border-block-start-color"####, r####"currentcolor"####),
    (r####"border-block-start-style"####, r####"none"####),
    (r####"border-block-start-width"####, r####"0px"####),
    (r####"border-bottom-color"####, r####"currentcolor"####),
    (r####"border-bottom-left-radius"####, r####"0px"####),
    (r####"border-bottom-right-radius"####, r####"0px"####),
    (r####"border-bottom-style"####, r####"none"####),
    (r####"border-bottom-width"####, r####"0px"####),
    (r####"border-collapse"####, r####"separate"####),
    (r####"border-end-end-radius"####, r####"0px"####),
    (r####"border-end-start-radius"####, r####"0px"####),
    (r####"border-image-outset"####, r####"0"####),
    (r####"border-image-repeat"####, r####"stretch"####),
    (r####"border-image-slice"####, r####"100%"####),
    (r####"border-image-source"####, r####"none"####),
    (r####"border-image-width"####, r####"1"####),
    (r####"border-inline-end-color"####, r####"currentcolor"####),
    (r####"border-inline-end-style"####, r####"none"####),
    (r####"border-inline-end-width"####, r####"0px"####),
    (
        r####"border-inline-start-color"####,
        r####"currentcolor"####,
    ),
    (r####"border-inline-start-style"####, r####"none"####),
    (r####"border-inline-start-width"####, r####"0px"####),
    (r####"border-left-color"####, r####"currentcolor"####),
    (r####"border-left-style"####, r####"none"####),
    (r####"border-left-width"####, r####"0px"####),
    (r####"border-right-color"####, r####"currentcolor"####),
    (r####"border-right-style"####, r####"none"####),
    (r####"border-right-width"####, r####"0px"####),
    (r####"border-shape"####, r####"none"####),
    (r####"border-start-end-radius"####, r####"0px"####),
    (r####"border-start-start-radius"####, r####"0px"####),
    (r####"border-top-color"####, r####"currentcolor"####),
    (r####"border-top-left-radius"####, r####"0px"####),
    (r####"border-top-right-radius"####, r####"0px"####),
    (r####"border-top-style"####, r####"none"####),
    (r####"border-top-width"####, r####"0px"####),
    (r####"bottom"####, r####"auto"####),
    (r####"box-decoration-break"####, r####"slice"####),
    (r####"box-shadow"####, r####"none"####),
    (r####"box-sizing"####, r####"content-box"####),
    (r####"break-after"####, r####"auto"####),
    (r####"break-before"####, r####"auto"####),
    (r####"break-inside"####, r####"auto"####),
    (r####"buffered-rendering"####, r####"auto"####),
    (r####"caption-side"####, r####"top"####),
    (r####"caret-animation"####, r####"auto"####),
    (r####"caret-color"####, r####"currentcolor"####),
    (r####"caret-shape"####, r####"auto"####),
    (r####"clear"####, r####"none"####),
    (r####"clip"####, r####"auto"####),
    (r####"clip-path"####, r####"none"####),
    (r####"clip-rule"####, r####"nonzero"####),
    (r####"color"####, r####"rgb(0, 0, 0)"####),
    (r####"color-interpolation"####, r####"srgb"####),
    (r####"color-interpolation-filters"####, r####"linearrgb"####),
    (r####"color-rendering"####, r####"auto"####),
    (r####"color-scheme"####, r####"normal"####),
    (r####"column-count"####, r####"auto"####),
    (r####"column-fill"####, r####"balance"####),
    (r####"column-gap"####, r####"normal"####),
    (r####"column-height"####, r####"auto"####),
    (r####"column-rule-break"####, r####"normal"####),
    (r####"column-rule-color"####, r####"currentcolor"####),
    (r####"column-rule-inset-cap-end"####, r####"0px"####),
    (r####"column-rule-inset-cap-start"####, r####"0px"####),
    (r####"column-rule-inset-junction-end"####, r####"0px"####),
    (r####"column-rule-inset-junction-start"####, r####"0px"####),
    (r####"column-rule-style"####, r####"none"####),
    (r####"column-rule-visibility-items"####, r####"normal"####),
    (r####"column-rule-width"####, r####"3px"####),
    (r####"column-span"####, r####"none"####),
    (r####"column-width"####, r####"auto"####),
    (r####"column-wrap"####, r####"auto"####),
    (r####"contain"####, r####"none"####),
    (r####"contain-intrinsic-block-size"####, r####"none"####),
    (r####"contain-intrinsic-height"####, r####"none"####),
    (r####"contain-intrinsic-inline-size"####, r####"none"####),
    (r####"contain-intrinsic-size"####, r####"none"####),
    (r####"contain-intrinsic-width"####, r####"none"####),
    (r####"container-name"####, r####"none"####),
    (r####"container-type"####, r####"normal"####),
    (r####"content"####, r####"normal"####),
    (r####"content-visibility"####, r####"visible"####),
    (r####"corner-bottom-left-shape"####, r####"round"####),
    (r####"corner-bottom-right-shape"####, r####"round"####),
    (r####"corner-end-end-shape"####, r####"round"####),
    (r####"corner-end-start-shape"####, r####"round"####),
    (r####"corner-start-end-shape"####, r####"round"####),
    (r####"corner-start-start-shape"####, r####"round"####),
    (r####"corner-top-left-shape"####, r####"round"####),
    (r####"corner-top-right-shape"####, r####"round"####),
    (r####"counter-increment"####, r####"none"####),
    (r####"counter-reset"####, r####"none"####),
    (r####"counter-set"####, r####"none"####),
    (r####"cursor"####, r####"auto"####),
    (r####"cx"####, r####"0px"####),
    (r####"cy"####, r####"0px"####),
    (r####"d"####, r####"none"####),
    (r####"direction"####, r####"ltr"####),
    (r####"display"####, r####"inline"####),
    (r####"dominant-baseline"####, r####"auto"####),
    (r####"dynamic-range-limit"####, r####"no-limit"####),
    (r####"empty-cells"####, r####"show"####),
    (r####"field-sizing"####, r####"fixed"####),
    (r####"fill"####, r####"rgb(0, 0, 0)"####),
    (r####"fill-opacity"####, r####"1"####),
    (r####"fill-rule"####, r####"nonzero"####),
    (r####"filter"####, r####"none"####),
    (r####"flex-basis"####, r####"auto"####),
    (r####"flex-direction"####, r####"row"####),
    (r####"flex-grow"####, r####"0"####),
    (r####"flex-line-count"####, r####"1"####),
    (r####"flex-shrink"####, r####"1"####),
    (r####"flex-wrap"####, r####"nowrap"####),
    (r####"float"####, r####"none"####),
    (r####"flood-color"####, r####"rgb(0, 0, 0)"####),
    (r####"flood-opacity"####, r####"1"####),
    (r####"font-family"####, r####""Times New Roman""####),
    (r####"font-feature-settings"####, r####"normal"####),
    (r####"font-kerning"####, r####"auto"####),
    (r####"font-language-override"####, r####"normal"####),
    (r####"font-optical-sizing"####, r####"auto"####),
    (r####"font-palette"####, r####"normal"####),
    (r####"font-size"####, r####"16px"####),
    (r####"font-size-adjust"####, r####"none"####),
    (r####"font-stretch"####, r####"100%"####),
    (r####"font-style"####, r####"normal"####),
    (r####"font-synthesis-small-caps"####, r####"auto"####),
    (r####"font-synthesis-style"####, r####"auto"####),
    (r####"font-synthesis-weight"####, r####"auto"####),
    (r####"font-variant"####, r####"normal"####),
    (r####"font-variant-alternates"####, r####"normal"####),
    (r####"font-variant-caps"####, r####"normal"####),
    (r####"font-variant-east-asian"####, r####"normal"####),
    (r####"font-variant-emoji"####, r####"normal"####),
    (r####"font-variant-ligatures"####, r####"normal"####),
    (r####"font-variant-numeric"####, r####"normal"####),
    (r####"font-variant-position"####, r####"normal"####),
    (r####"font-variation-settings"####, r####"normal"####),
    (r####"font-weight"####, r####"400"####),
    (r####"forced-color-adjust"####, r####"auto"####),
    (r####"grid-auto-columns"####, r####"auto"####),
    (r####"grid-auto-flow"####, r####"row"####),
    (r####"grid-auto-rows"####, r####"auto"####),
    (r####"grid-column-end"####, r####"auto"####),
    (r####"grid-column-start"####, r####"auto"####),
    (r####"grid-row-end"####, r####"auto"####),
    (r####"grid-row-start"####, r####"auto"####),
    (r####"grid-template-areas"####, r####"none"####),
    (r####"grid-template-columns"####, r####"none"####),
    (r####"grid-template-rows"####, r####"none"####),
    (r####"height"####, r####"auto"####),
    (r####"hyphenate-character"####, r####"auto"####),
    (r####"hyphenate-limit-chars"####, r####"auto"####),
    (r####"hyphens"####, r####"manual"####),
    (r####"image-orientation"####, r####"from-image"####),
    (r####"image-rendering"####, r####"auto"####),
    (r####"initial-letter"####, r####"normal"####),
    (r####"inline-size"####, r####"auto"####),
    (r####"inset-block-end"####, r####"auto"####),
    (r####"inset-block-start"####, r####"auto"####),
    (r####"inset-inline-end"####, r####"auto"####),
    (r####"inset-inline-start"####, r####"auto"####),
    (r####"interactivity"####, r####"auto"####),
    (r####"interest-delay-end"####, r####"normal"####),
    (r####"interest-delay-start"####, r####"normal"####),
    (r####"interpolate-size"####, r####"numeric-only"####),
    (r####"isolation"####, r####"auto"####),
    (r####"justify-content"####, r####"normal"####),
    (r####"justify-items"####, r####"normal"####),
    (r####"justify-self"####, r####"auto"####),
    (r####"left"####, r####"auto"####),
    (r####"letter-spacing"####, r####"normal"####),
    (r####"lighting-color"####, r####"rgb(255, 255, 255)"####),
    (r####"line-break"####, r####"auto"####),
    (r####"line-height"####, r####"normal"####),
    (r####"list-style-image"####, r####"none"####),
    (r####"list-style-position"####, r####"outside"####),
    (r####"list-style-type"####, r####"disc"####),
    (r####"margin-block-end"####, r####"0px"####),
    (r####"margin-block-start"####, r####"0px"####),
    (r####"margin-bottom"####, r####"0px"####),
    (r####"margin-inline-end"####, r####"0px"####),
    (r####"margin-inline-start"####, r####"0px"####),
    (r####"margin-left"####, r####"0px"####),
    (r####"margin-right"####, r####"0px"####),
    (r####"margin-top"####, r####"0px"####),
    (r####"marker-end"####, r####"none"####),
    (r####"marker-mid"####, r####"none"####),
    (r####"marker-start"####, r####"none"####),
    (r####"mask-clip"####, r####"border-box"####),
    (r####"mask-composite"####, r####"add"####),
    (r####"mask-image"####, r####"none"####),
    (r####"mask-mode"####, r####"match-source"####),
    (r####"mask-origin"####, r####"border-box"####),
    (r####"mask-position"####, r####"0% 0%"####),
    (r####"mask-repeat"####, r####"repeat"####),
    (r####"mask-size"####, r####"auto"####),
    (r####"mask-type"####, r####"luminance"####),
    (r####"math-depth"####, r####"0"####),
    (r####"math-shift"####, r####"normal"####),
    (r####"math-style"####, r####"normal"####),
    (r####"max-block-size"####, r####"none"####),
    (r####"max-height"####, r####"none"####),
    (r####"max-inline-size"####, r####"none"####),
    (r####"max-width"####, r####"none"####),
    (r####"min-block-size"####, r####"0px"####),
    (r####"min-height"####, r####"0px"####),
    (r####"min-inline-size"####, r####"0px"####),
    (r####"min-width"####, r####"0px"####),
    (r####"mix-blend-mode"####, r####"normal"####),
    (r####"object-fit"####, r####"fill"####),
    (r####"object-position"####, r####"50% 50%"####),
    (r####"object-view-box"####, r####"none"####),
    (r####"offset-anchor"####, r####"auto"####),
    (r####"offset-distance"####, r####"0px"####),
    (r####"offset-path"####, r####"none"####),
    (r####"offset-position"####, r####"normal"####),
    (r####"offset-rotate"####, r####"auto 0deg"####),
    (r####"opacity"####, r####"1"####),
    (r####"order"####, r####"0"####),
    (r####"orphans"####, r####"2"####),
    (r####"outline-color"####, r####"currentcolor"####),
    (r####"outline-offset"####, r####"0px"####),
    (r####"outline-style"####, r####"none"####),
    (r####"outline-width"####, r####"3px"####),
    (r####"overflow-anchor"####, r####"auto"####),
    (r####"overflow-block"####, r####"visible"####),
    (r####"overflow-clip-margin"####, r####"0px"####),
    (r####"overflow-inline"####, r####"visible"####),
    (r####"overflow-wrap"####, r####"normal"####),
    (r####"overflow-x"####, r####"visible"####),
    (r####"overflow-y"####, r####"visible"####),
    (r####"overlay"####, r####"none"####),
    (r####"overscroll-behavior-block"####, r####"auto"####),
    (r####"overscroll-behavior-inline"####, r####"auto"####),
    (r####"overscroll-behavior-x"####, r####"auto"####),
    (r####"overscroll-behavior-y"####, r####"auto"####),
    (r####"padding-block-end"####, r####"0px"####),
    (r####"padding-block-start"####, r####"0px"####),
    (r####"padding-bottom"####, r####"0px"####),
    (r####"padding-inline-end"####, r####"0px"####),
    (r####"padding-inline-start"####, r####"0px"####),
    (r####"padding-left"####, r####"0px"####),
    (r####"padding-right"####, r####"0px"####),
    (r####"padding-top"####, r####"0px"####),
    (r####"paint-order"####, r####"normal"####),
    (r####"perspective"####, r####"none"####),
    (r####"perspective-origin"####, r####"50% 50%"####),
    (r####"pointer-events"####, r####"auto"####),
    (r####"position"####, r####"static"####),
    (r####"position-anchor"####, r####"none"####),
    (r####"position-area"####, r####"none"####),
    (r####"position-try-fallbacks"####, r####"none"####),
    (r####"position-try-order"####, r####"normal"####),
    (r####"position-visibility"####, r####"anchors-visible"####),
    (r####"print-color-adjust"####, r####"economy"####),
    (r####"quotes"####, r####"auto"####),
    (r####"r"####, r####"0px"####),
    (r####"reading-flow"####, r####"normal"####),
    (r####"reading-order"####, r####"0"####),
    (r####"resize"####, r####"none"####),
    (r####"right"####, r####"auto"####),
    (r####"rotate"####, r####"none"####),
    (r####"row-gap"####, r####"normal"####),
    (r####"row-rule-break"####, r####"normal"####),
    (r####"row-rule-color"####, r####"rgb(0, 0, 0)"####),
    (r####"row-rule-inset-cap-end"####, r####"0px"####),
    (r####"row-rule-inset-cap-start"####, r####"0px"####),
    (r####"row-rule-inset-junction-end"####, r####"0px"####),
    (r####"row-rule-inset-junction-start"####, r####"0px"####),
    (r####"row-rule-style"####, r####"none"####),
    (r####"row-rule-visibility-items"####, r####"normal"####),
    (r####"row-rule-width"####, r####"3px"####),
    (r####"ruby-align"####, r####"space-around"####),
    (r####"ruby-position"####, r####"over"####),
    (r####"rule-overlap"####, r####"row-over-column"####),
    (r####"rx"####, r####"auto"####),
    (r####"ry"####, r####"auto"####),
    (r####"scale"####, r####"none"####),
    (r####"scroll-behavior"####, r####"auto"####),
    (r####"scroll-initial-target"####, r####"none"####),
    (r####"scroll-margin-block-end"####, r####"0px"####),
    (r####"scroll-margin-block-start"####, r####"0px"####),
    (r####"scroll-margin-bottom"####, r####"0px"####),
    (r####"scroll-margin-inline-end"####, r####"0px"####),
    (r####"scroll-margin-inline-start"####, r####"0px"####),
    (r####"scroll-margin-left"####, r####"0px"####),
    (r####"scroll-margin-right"####, r####"0px"####),
    (r####"scroll-margin-top"####, r####"0px"####),
    (r####"scroll-marker-group"####, r####"none"####),
    (r####"scroll-padding-block-end"####, r####"auto"####),
    (r####"scroll-padding-block-start"####, r####"auto"####),
    (r####"scroll-padding-bottom"####, r####"auto"####),
    (r####"scroll-padding-inline-end"####, r####"auto"####),
    (r####"scroll-padding-inline-start"####, r####"auto"####),
    (r####"scroll-padding-left"####, r####"auto"####),
    (r####"scroll-padding-right"####, r####"auto"####),
    (r####"scroll-padding-top"####, r####"auto"####),
    (r####"scroll-snap-align"####, r####"none"####),
    (r####"scroll-snap-stop"####, r####"normal"####),
    (r####"scroll-snap-type"####, r####"none"####),
    (r####"scroll-target-group"####, r####"none"####),
    (r####"scroll-timeline-axis"####, r####"block"####),
    (r####"scroll-timeline-name"####, r####"none"####),
    (r####"scrollbar-color"####, r####"auto"####),
    (r####"scrollbar-gutter"####, r####"auto"####),
    (r####"scrollbar-width"####, r####"auto"####),
    (r####"shape-image-threshold"####, r####"0"####),
    (r####"shape-margin"####, r####"0px"####),
    (r####"shape-outside"####, r####"none"####),
    (r####"shape-rendering"####, r####"auto"####),
    (r####"speak"####, r####"normal"####),
    (r####"stop-color"####, r####"rgb(0, 0, 0)"####),
    (r####"stop-opacity"####, r####"1"####),
    (r####"stroke"####, r####"none"####),
    (r####"stroke-dasharray"####, r####"none"####),
    (r####"stroke-dashoffset"####, r####"0px"####),
    (r####"stroke-linecap"####, r####"butt"####),
    (r####"stroke-linejoin"####, r####"miter"####),
    (r####"stroke-miterlimit"####, r####"4"####),
    (r####"stroke-opacity"####, r####"1"####),
    (r####"stroke-width"####, r####"1px"####),
    (r####"tab-size"####, r####"8"####),
    (r####"table-layout"####, r####"auto"####),
    (r####"text-align"####, r####"start"####),
    (r####"text-align-last"####, r####"auto"####),
    (r####"text-anchor"####, r####"start"####),
    (r####"text-autospace"####, r####"no-autospace"####),
    (r####"text-box-edge"####, r####"auto"####),
    (r####"text-box-trim"####, r####"none"####),
    (r####"text-combine-upright"####, r####"none"####),
    (r####"text-decoration"####, r####"none"####),
    (r####"text-decoration-color"####, r####"currentcolor"####),
    (r####"text-decoration-line"####, r####"none"####),
    (r####"text-decoration-skip-ink"####, r####"auto"####),
    (r####"text-decoration-style"####, r####"solid"####),
    (r####"text-decoration-thickness"####, r####"auto"####),
    (r####"text-emphasis-color"####, r####"currentcolor"####),
    (r####"text-emphasis-position"####, r####"over"####),
    (r####"text-emphasis-style"####, r####"none"####),
    (r####"text-fit"####, r####"none"####),
    (r####"text-indent"####, r####"0px"####),
    (r####"text-justify"####, r####"auto"####),
    (r####"text-orientation"####, r####"mixed"####),
    (r####"text-overflow"####, r####"clip"####),
    (r####"text-rendering"####, r####"auto"####),
    (r####"text-shadow"####, r####"none"####),
    (r####"text-size-adjust"####, r####"auto"####),
    (r####"text-spacing-trim"####, r####"normal"####),
    (r####"text-transform"####, r####"none"####),
    (r####"text-underline-offset"####, r####"auto"####),
    (r####"text-underline-position"####, r####"auto"####),
    (r####"text-wrap-mode"####, r####"wrap"####),
    (r####"text-wrap-style"####, r####"auto"####),
    (r####"timeline-scope"####, r####"none"####),
    (
        r####"timeline-trigger-activation-range-end"####,
        r####"normal"####,
    ),
    (
        r####"timeline-trigger-activation-range-start"####,
        r####"normal"####,
    ),
    (
        r####"timeline-trigger-active-range-end"####,
        r####"auto"####,
    ),
    (
        r####"timeline-trigger-active-range-start"####,
        r####"auto"####,
    ),
    (r####"timeline-trigger-name"####, r####"none"####),
    (r####"timeline-trigger-source"####, r####"auto"####),
    (r####"top"####, r####"auto"####),
    (r####"touch-action"####, r####"auto"####),
    (r####"transform"####, r####"none"####),
    (r####"transform-box"####, r####"view-box"####),
    (r####"transform-origin"####, r####"50% 50% 0px"####),
    (r####"transform-style"####, r####"flat"####),
    (r####"transition-behavior"####, r####"normal"####),
    (r####"transition-delay"####, r####"0s"####),
    (r####"transition-duration"####, r####"0s"####),
    (r####"transition-property"####, r####"all"####),
    (r####"transition-timing-function"####, r####"ease"####),
    (r####"translate"####, r####"none"####),
    (r####"trigger-scope"####, r####"none"####),
    (r####"unicode-bidi"####, r####"isolate"####),
    (r####"user-select"####, r####"auto"####),
    (r####"vector-effect"####, r####"none"####),
    (r####"vertical-align"####, r####"baseline"####),
    (r####"view-timeline-axis"####, r####"block"####),
    (r####"view-timeline-inset"####, r####"auto"####),
    (r####"view-timeline-name"####, r####"none"####),
    (r####"view-transition-class"####, r####"none"####),
    (r####"view-transition-group"####, r####"normal"####),
    (r####"view-transition-name"####, r####"none"####),
    (r####"view-transition-scope"####, r####"none"####),
    (r####"visibility"####, r####"visible"####),
    (r####"white-space-collapse"####, r####"collapse"####),
    (r####"widows"####, r####"2"####),
    (r####"width"####, r####"auto"####),
    (r####"will-change"####, r####"auto"####),
    (r####"word-break"####, r####"normal"####),
    (r####"word-spacing"####, r####"0px"####),
    (r####"writing-mode"####, r####"horizontal-tb"####),
    (r####"x"####, r####"0px"####),
    (r####"y"####, r####"0px"####),
    (r####"z-index"####, r####"auto"####),
    (r####"zoom"####, r####"1"####),
    (r####"-webkit-border-horizontal-spacing"####, r####"0px"####),
    (r####"-webkit-border-image"####, r####"none"####),
    (r####"-webkit-border-vertical-spacing"####, r####"0px"####),
    (r####"-webkit-box-align"####, r####"stretch"####),
    (r####"-webkit-box-decoration-break"####, r####"slice"####),
    (r####"-webkit-box-direction"####, r####"normal"####),
    (r####"-webkit-box-flex"####, r####"0"####),
    (r####"-webkit-box-ordinal-group"####, r####"1"####),
    (r####"-webkit-box-orient"####, r####"horizontal"####),
    (r####"-webkit-box-pack"####, r####"start"####),
    (r####"-webkit-box-reflect"####, r####"none"####),
    (r####"-webkit-font-smoothing"####, r####"auto"####),
    (r####"-webkit-line-break"####, r####"auto"####),
    (r####"-webkit-line-clamp"####, r####"none"####),
    (r####"-webkit-locale"####, r####"auto"####),
    (r####"-webkit-mask-box-image"####, r####"none"####),
    (r####"-webkit-mask-box-image-outset"####, r####"0"####),
    (r####"-webkit-mask-box-image-repeat"####, r####"stretch"####),
    (r####"-webkit-mask-box-image-slice"####, r####"0 fill"####),
    (r####"-webkit-mask-box-image-source"####, r####"none"####),
    (r####"-webkit-mask-box-image-width"####, r####"auto"####),
    (r####"-webkit-mask-position-x"####, r####"0%"####),
    (r####"-webkit-mask-position-y"####, r####"0%"####),
    (r####"-webkit-rtl-ordering"####, r####"logical"####),
    (r####"-webkit-ruby-position"####, r####"before"####),
    (
        r####"-webkit-tap-highlight-color"####,
        r####"rgba(0, 0, 0, 0.18)"####,
    ),
    (r####"-webkit-text-combine"####, r####"none"####),
    (
        r####"-webkit-text-decorations-in-effect"####,
        r####"none"####,
    ),
    (r####"-webkit-text-fill-color"####, r####"currentcolor"####),
    (
        r####"-webkit-text-orientation"####,
        r####"vertical-right"####,
    ),
    (r####"-webkit-text-security"####, r####"none"####),
    (
        r####"-webkit-text-stroke-color"####,
        r####"currentcolor"####,
    ),
    (r####"-webkit-text-stroke-width"####, r####"0px"####),
    (r####"-webkit-user-drag"####, r####"auto"####),
    (r####"-webkit-user-modify"####, r####"read-only"####),
    (r####"-webkit-writing-mode"####, r####"horizontal-tb"####),
];

pub(crate) fn value(name: &str) -> Option<&'static str> {
    static LOOKUP: std::sync::OnceLock<std::collections::HashMap<&'static str, &'static str>> =
        std::sync::OnceLock::new();
    LOOKUP
        .get_or_init(|| EDGE_150_INITIAL_COMPUTED_VALUES.iter().copied().collect())
        .get(name)
        .copied()
}
