pub(crate) fn install(scope: &mut v8::PinScope<'_, '_>) -> Result<(), String> {
    // Chromium Android exposes both Shape Detection and Content Index inside
    // DedicatedWorkerGlobalScope. Desktop/version reconciliation removes them
    // from platforms whose HTTPS evidence does not contain these interfaces.
    super::barcode_detector::install(scope)?;
    super::content_index::install(scope)?;
    super::text_encoder::install(scope)?;
    super::text_decoder::install(scope)?;
    super::text_encoder_stream::install(scope)?;
    super::text_decoder_stream::install(scope)?;
    super::readable_stream::install(scope)?;
    super::readable_stream_default_reader::install(scope)?;
    super::readable_stream_default_controller::install(scope)?;
    super::readable_stream_byob_request::install(scope)?;
    super::readable_stream_byob_reader::install(scope)?;
    super::readable_byte_stream_controller::install(scope)?;
    super::writable_stream::install(scope)?;
    super::writable_stream_default_writer::install(scope)?;
    super::writable_stream_default_controller::install(scope)?;
    super::transform_stream::install(scope)?;
    super::transform_stream_default_controller::install(scope)?;
    super::compression_stream::install(scope)?;
    super::decompression_stream::install(scope)?;
    super::byte_length_queuing_strategy::install(scope)?;
    super::count_queuing_strategy::install(scope)?;
    super::web_socket::install(scope)?;
    super::web_socket_stream::install(scope)?;
    super::web_socket_error::install(scope)?;
    super::webgl_vertex_array_object::install(scope)?;
    super::webgl_uniform_location::install(scope)?;
    super::webgl_transform_feedback::install(scope)?;
    super::webgl_texture::install(scope)?;
    super::webgl_sync::install(scope)?;
    super::webgl_shader_precision_format::install(scope)?;
    super::webgl_shader::install(scope)?;
    super::webgl_sampler::install(scope)?;
    super::webgl_renderbuffer::install(scope)?;
    super::webgl_query::install(scope)?;
    super::webgl_program::install(scope)?;
    super::webgl_object::install(scope)?;
    super::webgl_framebuffer::install(scope)?;
    super::webgl_buffer::install(scope)?;
    super::webgl_active_info::install(scope)?;
    super::restriction_target::install(scope)?;
    super::rtc_data_channel::install(scope)?;
    super::rtc_encoded_video_frame::install(scope)?;
    super::rtc_encoded_audio_frame::install(scope)?;
    super::quota_exceeded_error::install(scope)?;
    super::push_subscription_options::install(scope)?;
    super::push_subscription::install(scope)?;
    super::push_manager::install(scope)?;
    super::periodic_sync_manager::install(scope)?;
    super::origin::install(scope)?;
    super::notification::install(scope)?;
    super::crop_target::install(scope)?;
    super::background_fetch_registration::install(scope)?;
    super::background_fetch_record::install(scope)?;
    super::background_fetch_manager::install(scope)?;
    super::xml_http_request::install(scope)?;
    super::xml_http_request_event_target::install(scope)?;
    super::xml_http_request_upload::install(scope)?;
    super::performance_entry::install(scope)?;
    super::performance_mark::install(scope)?;
    super::performance_measure::install(scope)?;
    super::performance_server_timing::install(scope)?;
    super::performance_resource_timing::install(scope)?;
    super::performance_observer_entry_list::install(scope)?;
    super::performance_observer::install(scope)?;
    super::image_bitmap::install(scope)?;
    super::image_bitmap_rendering_context::install(scope)?;
    super::image_data::install(scope)?;
    super::path2d::install(scope)?;
    super::text_metrics::install(scope)?;
    super::dom_matrix::install_standard_name(scope)?;
    super::dom_matrix_read_only::install(scope)?;
    super::dom_point::install(scope)?;
    super::dom_point_read_only::install(scope)?;
    super::dom_quad::install(scope)?;
    super::dom_rect::install(scope)?;
    super::dom_rect_read_only::install(scope)?;
    super::dom_string_list::install(scope)?;
    super::video_frame::install(scope)?;
    super::video_color_space::install(scope)?;
    super::user_activation::install(scope)?;
    super::trusted_type_policy::install(scope)?;
    super::trusted_script_url::install(scope)?;
    super::trusted_script::install(scope)?;
    super::trusted_html::install(scope)?;
    super::task_signal::install(scope)?;
    super::task_controller::install(scope)?;
    super::sync_manager::install(scope)?;
    super::subscriber::install(scope)?;
    super::source_buffer_list::install(scope)?;
    super::source_buffer::install(scope)?;
    super::reporting_observer::install(scope)?;
    super::report_body::install(scope)?;
    super::permissions::install(scope)?;
    super::permission_status::install(scope)?;
    super::observable::install(scope)?;
    super::network_information::install(scope)?;
    super::navigator_ua_data::install(scope)?;
    super::media_source_handle::install(scope)?;
    super::media_source::install(scope)?;
    super::media_capabilities::install(scope)?;
    super::idb_version_change_event::install(scope)?;
    super::idb_transaction::install(scope)?;
    super::idb_request::install(scope)?;
    super::idb_record::install(scope)?;
    super::idb_open_db_request::install(scope)?;
    super::idb_object_store::install(scope)?;
    super::idb_key_range::install(scope)?;
    super::idb_index::install(scope)?;
    super::idb_database::install(scope)?;
    super::idb_cursor_with_value::install(scope)?;
    super::idb_cursor::install(scope)?;
    super::font_face::install(scope)?;
    super::font_face_set::install(scope)?;
    super::file_list::install(scope)?;
    super::event_source::install(scope)?;
    super::encoded_video_chunk::install(scope)?;
    super::encoded_audio_chunk::install(scope)?;
    super::audio_data::install(scope)?;
    super::canvas_pattern::install(scope)?;
    super::canvas_gradient::install(scope)?;
    super::css_skew_y::install(scope)?;
    super::css_skew_x::install(scope)?;
    super::audio_decoder::install(scope)?;
    super::audio_encoder::install(scope)?;
    super::create_monitor::install(scope)?;
    super::gpu::install(scope)?;
    super::gpu_adapter::install(scope)?;
    super::gpu_adapter_info::install(scope)?;
    super::gpu_bind_group::install(scope)?;
    super::gpu_bind_group_layout::install(scope)?;
    super::gpu_buffer::install(scope)?;
    super::gpu_buffer_usage::install(scope)?;
    super::gpu_canvas_context::install(scope)?;
    super::gpu_color_write::install(scope)?;
    super::gpu_command_buffer::install(scope)?;
    super::gpu_command_encoder::install(scope)?;
    super::gpu_compilation_info::install(scope)?;
    super::gpu_compilation_message::install(scope)?;
    super::gpu_compute_pass_encoder::install(scope)?;
    super::gpu_compute_pipeline::install(scope)?;
    super::gpu_device::install(scope)?;
    super::gpu_device_lost_info::install(scope)?;
    super::gpu_error::install(scope)?;
    super::gpu_external_texture::install(scope)?;
    super::gpu_internal_error::install(scope)?;
    super::gpu_map_mode::install(scope)?;
    super::gpu_out_of_memory_error::install(scope)?;
    super::gpu_pipeline_error::install(scope)?;
    super::gpu_pipeline_layout::install(scope)?;
    super::gpu_query_set::install(scope)?;
    super::gpu_queue::install(scope)?;
    super::gpu_render_bundle::install(scope)?;
    super::gpu_render_bundle_encoder::install(scope)?;
    super::gpu_render_pass_encoder::install(scope)?;
    super::gpu_render_pipeline::install(scope)?;
    super::gpu_sampler::install(scope)?;
    super::gpu_shader_module::install(scope)?;
    super::gpu_shader_stage::install(scope)?;
    super::gpu_supported_features::install(scope)?;
    super::gpu_supported_limits::install(scope)?;
    super::gpu_texture::install(scope)?;
    super::gpu_texture_usage::install(scope)?;
    super::gpu_texture_view::install(scope)?;
    super::gpu_uncaptured_error_event::install(scope)?;
    super::gpu_validation_error::install(scope)?;
    super::idle_detector::install(scope)?;
    super::image_decoder::install(scope)?;
    super::image_track::install(scope)?;
    super::image_track_list::install(scope)?;
    super::navigation_preload_manager::install(scope)?;
    super::service_worker_registration::install(scope)?;
    super::storage_manager::install(scope)?;
    super::video_decoder::install(scope)?;
    super::video_encoder::install(scope)?;
    super::wgsl_language_features::install(scope)?;
    super::web_transport::install(scope)?;
    super::web_transport_bidirectional_stream::install(scope)?;
    super::web_transport_datagram_duplex_stream::install(scope)?;
    super::web_transport_error::install(scope)?;
    super::file_system_directory_handle::install(scope)?;
    super::file_system_handle::install(scope)?;
    super::file_system_writable_file_stream::install(scope)?;
    super::file_system_observer::install(scope)?;
    super::hid::install(scope)?;
    super::hid_connection_event::install(scope)?;
    super::hid_device::install(scope)?;
    super::hid_input_report_event::install(scope)?;
    super::lock::install(scope)?;
    super::lock_manager::install(scope)?;
    super::pressure_observer::install(scope)?;
    super::pressure_record::install(scope)?;
    super::serial::install(scope)?;
    super::serial_port::install(scope)?;
    super::storage_bucket::install(scope)?;
    super::storage_bucket_manager::install(scope)?;
    super::usb::install(scope)?;
    super::usb_alternate_interface::install(scope)?;
    super::usb_configuration::install(scope)?;
    super::usb_connection_event::install(scope)?;
    super::usb_device::install(scope)?;
    super::usb_endpoint::install(scope)?;
    super::usb_in_transfer_result::install(scope)?;
    super::usb_interface::install(scope)?;
    super::usb_isochronous_in_transfer_packet::install(scope)?;
    super::usb_isochronous_in_transfer_result::install(scope)?;
    super::usb_isochronous_out_transfer_packet::install(scope)?;
    super::usb_isochronous_out_transfer_result::install(scope)?;
    super::usb_out_transfer_result::install(scope)
}

pub(crate) fn cleanup(scope: &mut v8::PinScope<'_, '_>, realm_id: i32) {
    super::file_system_file_handle::cleanup_worker_realm(scope, realm_id);
    super::abort_controller::cleanup_realm(scope, realm_id);
    super::abort_signal::cleanup_realm(scope, realm_id);
    super::blob::cleanup_realm(scope, realm_id);
    super::broadcast_channel::cleanup_realm(scope, realm_id);
    super::cache::cleanup_realm(scope, realm_id);
    super::cache_storage::cleanup_realm(scope, realm_id);
    super::close_event::cleanup_realm(scope, realm_id);
    super::crypto::cleanup_realm(scope, realm_id);
    super::crypto_key::cleanup_realm(scope, realm_id);
    super::custom_event::cleanup_realm(scope, realm_id);
    super::dom_exception::cleanup_realm(scope, realm_id);
    super::error_event::cleanup_realm(scope, realm_id);
    super::event::cleanup_realm(scope, realm_id);
    super::event_target::cleanup_realm(scope, realm_id);
    super::file::cleanup_realm(scope, realm_id);
    super::file_reader::cleanup_realm(scope, realm_id);
    super::form_data::cleanup_realm(scope, realm_id);
    super::headers::cleanup_realm(scope, realm_id);
    super::idb_factory::cleanup_realm(scope, realm_id);
    super::message_channel::cleanup_realm(scope, realm_id);
    super::message_event::cleanup_realm(scope, realm_id);
    super::message_port::cleanup_realm(scope, realm_id);
    super::offscreen_canvas::cleanup_realm(scope, realm_id);
    super::offscreen_canvas_rendering_context_2d::cleanup_realm(scope, realm_id);
    super::performance::cleanup_realm(scope, realm_id);
    super::progress_event::cleanup_realm(scope, realm_id);
    super::promise_rejection_event::cleanup_realm(scope, realm_id);
    super::request::cleanup_realm(scope, realm_id);
    super::response::cleanup_realm(scope, realm_id);
    super::scheduler::cleanup_realm(scope, realm_id);
    super::security_policy_violation_event::cleanup_realm(scope, realm_id);
    super::task_priority_change_event::cleanup_realm(scope, realm_id);
    super::trusted_type_policy_factory::cleanup_realm(scope, realm_id);
    super::url::cleanup_realm(scope, realm_id);
    super::url_pattern::cleanup_realm(scope, realm_id);
    super::url_search_params::cleanup_realm(scope, realm_id);
    super::webgl2_rendering_context::cleanup_realm(scope, realm_id);
    super::webgl_context_event::cleanup_realm(scope, realm_id);
    super::webgl_rendering_context::cleanup_realm(scope, realm_id);
    super::audio_data::cleanup_realm(scope, realm_id);
    super::audio_decoder::cleanup_realm(scope, realm_id);
    super::audio_encoder::cleanup_realm(scope, realm_id);
    super::background_fetch_manager::cleanup_realm(scope, realm_id);
    super::background_fetch_record::cleanup_realm(scope, realm_id);
    super::background_fetch_registration::cleanup_realm(scope, realm_id);
    super::byte_length_queuing_strategy::cleanup_realm(scope, realm_id);
    super::canvas_gradient::cleanup_realm(scope, realm_id);
    super::canvas_pattern::cleanup_realm(scope, realm_id);
    super::compression_stream::cleanup_realm(scope, realm_id);
    super::count_queuing_strategy::cleanup_realm(scope, realm_id);
    super::create_monitor::cleanup_realm(scope, realm_id);
    super::crop_target::cleanup_realm(scope, realm_id);
    super::css_skew_x::cleanup_realm(scope, realm_id);
    super::css_skew_y::cleanup_realm(scope, realm_id);
    super::css_transform_component::cleanup_realm(scope, realm_id);
    super::decompression_stream::cleanup_realm(scope, realm_id);
    super::dom_matrix::cleanup_realm(scope, realm_id);
    super::dom_matrix_read_only::cleanup_realm(scope, realm_id);
    super::dom_point::cleanup_realm(scope, realm_id);
    super::dom_point_read_only::cleanup_realm(scope, realm_id);
    super::dom_quad::cleanup_realm(scope, realm_id);
    super::dom_rect::cleanup_realm(scope, realm_id);
    super::dom_rect_read_only::cleanup_realm(scope, realm_id);
    super::dom_string_list::cleanup_realm(scope, realm_id);
    super::encoded_audio_chunk::cleanup_realm(scope, realm_id);
    super::encoded_video_chunk::cleanup_realm(scope, realm_id);
    super::event_source::cleanup_realm(scope, realm_id);
    super::file_list::cleanup_realm(scope, realm_id);
    super::file_reader_sync::cleanup_realm(scope, realm_id);
    super::file_system_directory_handle::cleanup_realm(scope, realm_id);
    super::file_system_handle::cleanup_realm(scope, realm_id);
    super::file_system_observer::cleanup_realm(scope, realm_id);
    super::file_system_sync_access_handle::cleanup_realm(scope, realm_id);
    super::file_system_writable_file_stream::cleanup_realm(scope, realm_id);
    super::font_face::cleanup_realm(scope, realm_id);
    super::font_face_set::cleanup_realm(scope, realm_id);
    super::gpu::cleanup_realm(scope, realm_id);
    super::gpu_adapter::cleanup_realm(scope, realm_id);
    super::gpu_adapter_info::cleanup_realm(scope, realm_id);
    super::gpu_bind_group::cleanup_realm(scope, realm_id);
    super::gpu_bind_group_layout::cleanup_realm(scope, realm_id);
    super::gpu_buffer::cleanup_realm(scope, realm_id);
    super::gpu_canvas_context::cleanup_realm(scope, realm_id);
    super::gpu_command_buffer::cleanup_realm(scope, realm_id);
    super::gpu_command_encoder::cleanup_realm(scope, realm_id);
    super::gpu_compilation_info::cleanup_realm(scope, realm_id);
    super::gpu_compilation_message::cleanup_realm(scope, realm_id);
    super::gpu_compute_pass_encoder::cleanup_realm(scope, realm_id);
    super::gpu_compute_pipeline::cleanup_realm(scope, realm_id);
    super::gpu_device::cleanup_realm(scope, realm_id);
    super::gpu_device_lost_info::cleanup_realm(scope, realm_id);
    super::gpu_error::cleanup_realm(scope, realm_id);
    super::gpu_external_texture::cleanup_realm(scope, realm_id);
    super::gpu_internal_error::cleanup_realm(scope, realm_id);
    super::gpu_out_of_memory_error::cleanup_realm(scope, realm_id);
    super::gpu_pipeline_error::cleanup_realm(scope, realm_id);
    super::gpu_pipeline_layout::cleanup_realm(scope, realm_id);
    super::gpu_query_set::cleanup_realm(scope, realm_id);
    super::gpu_queue::cleanup_realm(scope, realm_id);
    super::gpu_render_bundle::cleanup_realm(scope, realm_id);
    super::gpu_render_bundle_encoder::cleanup_realm(scope, realm_id);
    super::gpu_render_pass_encoder::cleanup_realm(scope, realm_id);
    super::gpu_render_pipeline::cleanup_realm(scope, realm_id);
    super::gpu_sampler::cleanup_realm(scope, realm_id);
    super::gpu_shader_module::cleanup_realm(scope, realm_id);
    super::gpu_supported_features::cleanup_realm(scope, realm_id);
    super::gpu_supported_limits::cleanup_realm(scope, realm_id);
    super::gpu_texture::cleanup_realm(scope, realm_id);
    super::gpu_texture_view::cleanup_realm(scope, realm_id);
    super::gpu_uncaptured_error_event::cleanup_realm(scope, realm_id);
    super::gpu_validation_error::cleanup_realm(scope, realm_id);
    super::hid::cleanup_realm(scope, realm_id);
    super::hid_connection_event::cleanup_realm(scope, realm_id);
    super::hid_device::cleanup_realm(scope, realm_id);
    super::hid_input_report_event::cleanup_realm(scope, realm_id);
    super::idb_cursor::cleanup_realm(scope, realm_id);
    super::idb_cursor_with_value::cleanup_realm(scope, realm_id);
    super::idb_database::cleanup_realm(scope, realm_id);
    super::idb_index::cleanup_realm(scope, realm_id);
    super::idb_key_range::cleanup_realm(scope, realm_id);
    super::idb_object_store::cleanup_realm(scope, realm_id);
    super::idb_open_db_request::cleanup_realm(scope, realm_id);
    super::idb_record::cleanup_realm(scope, realm_id);
    super::idb_request::cleanup_realm(scope, realm_id);
    super::idb_transaction::cleanup_realm(scope, realm_id);
    super::idb_version_change_event::cleanup_realm(scope, realm_id);
    super::idle_detector::cleanup_realm(scope, realm_id);
    super::image_bitmap::cleanup_realm(scope, realm_id);
    super::image_bitmap_rendering_context::cleanup_realm(scope, realm_id);
    super::image_data::cleanup_realm(scope, realm_id);
    super::image_decoder::cleanup_realm(scope, realm_id);
    super::image_track::cleanup_realm(scope, realm_id);
    super::image_track_list::cleanup_realm(scope, realm_id);
    super::lock::cleanup_realm(scope, realm_id);
    super::lock_manager::cleanup_realm(scope, realm_id);
    super::media_capabilities::cleanup_realm(scope, realm_id);
    super::media_source::cleanup_realm(scope, realm_id);
    super::media_source_handle::cleanup_realm(scope, realm_id);
    super::navigation_preload_manager::cleanup_realm(scope, realm_id);
    super::navigator_ua_data::cleanup_realm(scope, realm_id);
    super::network_information::cleanup_realm(scope, realm_id);
    super::notification::cleanup_realm(scope, realm_id);
    super::observable::cleanup_realm(scope, realm_id);
    super::origin::cleanup_realm(scope, realm_id);
    super::path2d::cleanup_realm(scope, realm_id);
    super::performance_entry::cleanup_realm(scope, realm_id);
    super::performance_mark::cleanup_realm(scope, realm_id);
    super::performance_measure::cleanup_realm(scope, realm_id);
    super::performance_observer::cleanup_realm(scope, realm_id);
    super::rendering_performance_state::cleanup_realm(scope, realm_id);
    super::performance_observer_entry_list::cleanup_realm(scope, realm_id);
    super::performance_resource_timing::cleanup_realm(scope, realm_id);
    super::performance_server_timing::cleanup_realm(scope, realm_id);
    super::periodic_sync_manager::cleanup_realm(scope, realm_id);
    super::permission_status::cleanup_realm(scope, realm_id);
    super::permissions::cleanup_realm(scope, realm_id);
    super::pressure_observer::cleanup_realm(scope, realm_id);
    super::pressure_record::cleanup_realm(scope, realm_id);
    super::push_manager::cleanup_realm(scope, realm_id);
    super::push_subscription::cleanup_realm(scope, realm_id);
    super::push_subscription_options::cleanup_realm(scope, realm_id);
    super::quota_exceeded_error::cleanup_realm(scope, realm_id);
    super::readable_byte_stream_controller::cleanup_realm(scope, realm_id);
    super::readable_stream::cleanup_realm(scope, realm_id);
    super::readable_stream_byob_reader::cleanup_realm(scope, realm_id);
    super::readable_stream_byob_request::cleanup_realm(scope, realm_id);
    super::readable_stream_default_controller::cleanup_realm(scope, realm_id);
    super::readable_stream_default_reader::cleanup_realm(scope, realm_id);
    super::report_body::cleanup_realm(scope, realm_id);
    super::reporting_observer::cleanup_realm(scope, realm_id);
    super::restriction_target::cleanup_realm(scope, realm_id);
    super::rtc_data_channel::cleanup_realm(scope, realm_id);
    super::rtc_encoded_audio_frame::cleanup_realm(scope, realm_id);
    super::rtc_encoded_video_frame::cleanup_realm(scope, realm_id);
    super::rtc_rtp_script_transformer::cleanup_realm(scope, realm_id);
    super::rtc_transform_event::cleanup_realm(scope, realm_id);
    super::serial::cleanup_realm(scope, realm_id);
    super::serial_port::cleanup_realm(scope, realm_id);
    super::service_worker_registration::cleanup_realm(scope, realm_id);
    super::source_buffer::cleanup_realm(scope, realm_id);
    super::source_buffer_list::cleanup_realm(scope, realm_id);
    super::storage_bucket::cleanup_realm(scope, realm_id);
    super::storage_bucket_manager::cleanup_realm(scope, realm_id);
    super::storage_manager::cleanup_realm(scope, realm_id);
    super::subscriber::cleanup_realm(scope, realm_id);
    super::sync_manager::cleanup_realm(scope, realm_id);
    super::task_controller::cleanup_realm(scope, realm_id);
    super::task_signal::cleanup_realm(scope, realm_id);
    super::text_decoder::cleanup_realm(scope, realm_id);
    super::text_decoder_stream::cleanup_realm(scope, realm_id);
    super::text_encoder::cleanup_realm(scope, realm_id);
    super::text_encoder_stream::cleanup_realm(scope, realm_id);
    super::text_metrics::cleanup_realm(scope, realm_id);
    super::transform_stream::cleanup_realm(scope, realm_id);
    super::transform_stream_default_controller::cleanup_realm(scope, realm_id);
    super::trusted_html::cleanup_realm(scope, realm_id);
    super::trusted_script::cleanup_realm(scope, realm_id);
    super::trusted_script_url::cleanup_realm(scope, realm_id);
    super::trusted_type_policy::cleanup_realm(scope, realm_id);
    super::usb::cleanup_realm(scope, realm_id);
    super::usb_alternate_interface::cleanup_realm(scope, realm_id);
    super::usb_configuration::cleanup_realm(scope, realm_id);
    super::usb_connection_event::cleanup_realm(scope, realm_id);
    super::usb_device::cleanup_realm(scope, realm_id);
    super::usb_endpoint::cleanup_realm(scope, realm_id);
    super::usb_in_transfer_result::cleanup_realm(scope, realm_id);
    super::usb_interface::cleanup_realm(scope, realm_id);
    super::usb_isochronous_in_transfer_packet::cleanup_realm(scope, realm_id);
    super::usb_isochronous_in_transfer_result::cleanup_realm(scope, realm_id);
    super::usb_isochronous_out_transfer_packet::cleanup_realm(scope, realm_id);
    super::usb_isochronous_out_transfer_result::cleanup_realm(scope, realm_id);
    super::usb_out_transfer_result::cleanup_realm(scope, realm_id);
    super::user_activation::cleanup_realm(scope, realm_id);
    super::video_color_space::cleanup_realm(scope, realm_id);
    super::video_decoder::cleanup_realm(scope, realm_id);
    super::video_encoder::cleanup_realm(scope, realm_id);
    super::video_frame::cleanup_realm(scope, realm_id);
    super::web_socket::cleanup_realm(scope, realm_id);
    super::web_socket_error::cleanup_realm(scope, realm_id);
    super::web_socket_stream::cleanup_realm(scope, realm_id);
    super::web_transport::cleanup_realm(scope, realm_id);
    super::web_transport_bidirectional_stream::cleanup_realm(scope, realm_id);
    super::web_transport_datagram_duplex_stream::cleanup_realm(scope, realm_id);
    super::web_transport_error::cleanup_realm(scope, realm_id);
    super::webgl_active_info::cleanup_realm(scope, realm_id);
    super::webgl_buffer::cleanup_realm(scope, realm_id);
    super::webgl_framebuffer::cleanup_realm(scope, realm_id);
    super::webgl_object::cleanup_realm(scope, realm_id);
    super::webgl_program::cleanup_realm(scope, realm_id);
    super::webgl_query::cleanup_realm(scope, realm_id);
    super::webgl_renderbuffer::cleanup_realm(scope, realm_id);
    super::webgl_sampler::cleanup_realm(scope, realm_id);
    super::webgl_shader::cleanup_realm(scope, realm_id);
    super::webgl_shader_precision_format::cleanup_realm(scope, realm_id);
    super::webgl_sync::cleanup_realm(scope, realm_id);
    super::webgl_texture::cleanup_realm(scope, realm_id);
    super::webgl_transform_feedback::cleanup_realm(scope, realm_id);
    super::webgl_uniform_location::cleanup_realm(scope, realm_id);
    super::webgl_vertex_array_object::cleanup_realm(scope, realm_id);
    super::wgsl_language_features::cleanup_realm(scope, realm_id);
    super::writable_stream::cleanup_realm(scope, realm_id);
    super::writable_stream_default_controller::cleanup_realm(scope, realm_id);
    super::writable_stream_default_writer::cleanup_realm(scope, realm_id);
    super::xml_http_request::cleanup_realm(scope, realm_id);
    super::xml_http_request_event_target::cleanup_realm(scope, realm_id);
    super::xml_http_request_upload::cleanup_realm(scope, realm_id);
}
