"""Generate compact Rust browser-surface tables from official runtime captures.

The generated module contains only typed string slices.  Runtime code never
reads JSON, downloads a browser, or depends on the evidence cache.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "build" / "chromium-version-surfaces"
DEFAULT_OUTPUT = ROOT / "src" / "browser_surface_data.rs"
DEFAULT_ANDROID_INPUT = ROOT / "build" / "chromium-android-version-surfaces"
DEFAULT_ANDROID_OUTPUT = ROOT / "src" / "browser_android_surface_data.rs"


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_slice(lines: list[str], name: str, values: list[str]) -> None:
    lines.append(f"static {name}: &[&str] = &[")
    for value in values:
        lines.append(f"    {rust_string(value)},")
    lines.append("];")
    lines.append("")


def load_surfaces(directory: Path, android: bool = False) -> dict[int, dict[str, object]]:
    surfaces: dict[int, dict[str, object]] = {}
    for major in range(140, 152):
        path = directory / (
            f"chromium-android-{major}-https-surface.json"
            if android else f"chromium-{major}-surface.json"
        )
        if not path.is_file():
            raise FileNotFoundError(f"missing official surface capture: {path}")
        document = json.loads(path.read_text(encoding="utf-8"))
        actual = int(str(document["userAgent"]).split("Chrome/", 1)[1].split(".", 1)[0])
        if actual != major:
            raise ValueError(f"{path} contains Chromium {actual}, expected {major}")
        surfaces[major] = document
    return surfaces


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--android", action="store_true")
    arguments = parser.parse_args()
    input_directory = arguments.input or (DEFAULT_ANDROID_INPUT if arguments.android else DEFAULT_INPUT)
    output_path = arguments.output or (DEFAULT_ANDROID_OUTPUT if arguments.android else DEFAULT_OUTPUT)
    surfaces = load_surfaces(input_directory, arguments.android)

    lines = [
        "// @generated by tools/generate_browser_surface_data.py; do not edit by hand.",
        "// Evidence: official Chromium Android HTTPS runtime captures for majors 140-151."
        if arguments.android else
        "// Evidence: official Chrome for Testing HTTPS runtime captures for majors 140-151.",
        "",
    ]
    fields = {
        "WINDOW": lambda document: document["topWindowBeforeFrame"]["names"],
        "NAVIGATOR": lambda document: document["navigatorPrototype"]["names"],
        "WORKER_GLOBAL": lambda document: document["worker"]["global"]["names"],
        "WORKER_NAVIGATOR": lambda document: document["worker"]["navigatorPrototype"]["names"],
    }
    for prefix, select in fields.items():
        for major, document in surfaces.items():
            write_slice(lines, f"{prefix}_{major}", list(select(document)))

    for prefix, function in (
        ("WINDOW", "window_names"),
        ("NAVIGATOR", "navigator_names"),
        ("WORKER_GLOBAL", "worker_global_names"),
        ("WORKER_NAVIGATOR", "worker_navigator_names"),
    ):
        lines.append(f"pub(crate) fn {function}(major: u16) -> &'static [&'static str] {{")
        lines.append("    match major {")
        for major in surfaces:
            lines.append(f"        {major} => {prefix}_{major},")
        lines.append('        _ => unreachable!("validated browser major"),')
        lines.append("    }")
        lines.append("}")
        lines.append("")

    lines.append("#[cfg(test)]")
    lines.append("pub(crate) fn expected_window_descriptor_hash(major: u16) -> u32 {")
    lines.append("    match major {")
    for major, document in surfaces.items():
        descriptors = document["topWindowBeforeFrame"]["descriptors"]
        values: list[str] = []
        for name in document["topWindowBeforeFrame"]["names"]:
            descriptor = descriptors[name]
            values.append(
                name
                + ":"
                + ("d" if descriptor["kind"] == "data" else "a")
                + ":"
                + str(int(descriptor["enumerable"]))
                + str(int(descriptor["configurable"]))
                + str(int(bool(descriptor.get("writable", False))))
                + ":"
                + str(int(bool(descriptor.get("get"))))
                + str(int(bool(descriptor.get("set"))))
            )
        value = 2166136261
        for character in "\x1f".join(values):
            value = ((value ^ ord(character)) * 16777619) & 0xFFFFFFFF
        lines.append(f"        {major} => 0x{value:08x},")
    lines.append('        _ => unreachable!("validated browser major"),')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    def surface_records(document: dict[str, object], field: str) -> list[str]:
        records: list[str] = []
        for category in ("constructorPrototypes", "constructorStatics", "globalObjects"):
            for owner in sorted(document[category]):
                if owner == "0":
                    continue
                values = document[category][owner][field]
                records.append(category + ":" + owner + ":" + "\x1e".join(values))
        records.sort()
        return records

    def fnv1a_records(records: list[str]) -> int:
        value = 2166136261
        for character in "\x1f".join(records):
            value = ((value ^ ord(character)) * 16777619) & 0xFFFFFFFF
        return value

    lines.append("#[cfg(test)]")
    lines.append("pub(crate) fn expected_versioned_surface_hash(major: u16) -> u32 {")
    lines.append("    match major {")
    for major, document in surfaces.items():
        value = fnv1a_records(surface_records(document, "names"))
        lines.append(f"        {major} => 0x{value:08x},")
    lines.append('        _ => unreachable!("validated browser major"),')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("#[cfg(test)]")
    lines.append("pub(crate) fn expected_versioned_surface_keys_hash(major: u16) -> u32 {")
    lines.append("    match major {")
    for major, document in surfaces.items():
        value = fnv1a_records(surface_records(document, "keys"))
        lines.append(f"        {major} => 0x{value:08x},")
    lines.append('        _ => unreachable!("validated browser major"),')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("#[cfg(test)]")
    lines.append("pub(crate) fn expected_worker_versioned_surface_hash(major: u16) -> u32 {")
    lines.append("    match major {")
    for major, document in surfaces.items():
        worker = document["worker"]
        value = fnv1a_records(surface_records(worker, "names"))
        lines.append(f"        {major} => 0x{value:08x},")
    lines.append('        _ => unreachable!("validated browser major"),')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("#[cfg(test)]")
    lines.append("pub(crate) fn expected_worker_versioned_surface_keys_hash(major: u16) -> u32 {")
    lines.append("    match major {")
    for major, document in surfaces.items():
        value = fnv1a_records(surface_records(document["worker"], "keys"))
        lines.append(f"        {major} => 0x{value:08x},")
    lines.append('        _ => unreachable!("validated browser major"),')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    def generate_varying_tables(
        documents: dict[int, dict[str, object]],
        source_key: str,
        prefix: str,
        function_name: str,
        reconciled_invariant_owners: set[str] | None = None,
        reconcile_all_owners: bool = False,
    ) -> None:
        reconciled_invariant_owners = reconciled_invariant_owners or set()
        owners = sorted(set().union(*(document[source_key] for document in documents.values())))
        varying: list[str] = []
        for owner in owners:
            versions = [
                tuple(documents[major][source_key].get(owner, {}).get("names", []))
                for major in documents
            ]
            if (
                len(set(versions)) == 1
                and owner not in reconciled_invariant_owners
                and not reconcile_all_owners
            ):
                continue
            varying.append(owner)
            identifier = prefix + "_" + "".join(
                character.upper() if character.isalnum() else "_" for character in owner
            )
            for major, document in documents.items():
                values = list(document[source_key].get(owner, {}).get("names", []))
                write_slice(lines, f"{identifier}_{major}", values)
            lines.append(
                f"fn {function_name}_{len(varying) - 1}(major: u16) -> &'static [&'static str] {{"
            )
            lines.append("    match major {")
            for major in documents:
                lines.append(f"        {major} => {identifier}_{major},")
            lines.append('        _ => unreachable!("validated browser major"),')
            lines.append("    }")
            lines.append("}")
            lines.append("")
        lines.append(
            f"pub(crate) fn {function_name}(owner: &str, major: u16) -> Option<&'static [&'static str]> {{"
        )
        lines.append("    match owner {")
        for index, owner in enumerate(varying):
            lines.append(f"        {rust_string(owner)} => Some({function_name}_{index}(major)),")
        lines.append("        _ => None,")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    generate_varying_tables(
        surfaces,
        "constructorStatics",
        "STATIC",
        "constructor_static_names",
        reconcile_all_owners=arguments.android,
    )
    generate_varying_tables(
        surfaces,
        "globalObjects",
        "OBJECT",
        "global_object_names",
        reconcile_all_owners=arguments.android,
    )

    # These invariant Chrome surfaces intentionally participate in runtime
    # reconciliation because the sandbox's historical Edge-compat layer adds
    # non-Chromium members to them.  Keeping the allowlist in the generator
    # makes the generated target remain evidence-derived rather than encoding
    # the target names in runtime logic.
    reconciled_invariant_prototypes = {
        "GeolocationPosition",
        "HTMLInputElement",
        "NetworkInformation",
        "ServiceWorkerRegistration",
        "SubmitEvent",
        "HTMLVideoElement",
        "Notification",
        "SpeechSynthesis",
    }
    generate_varying_tables(
        surfaces,
        "constructorPrototypes",
        "PROTO",
        "prototype_names",
        reconciled_invariant_prototypes,
        arguments.android,
    )

    worker_documents = {major: document["worker"] for major, document in surfaces.items()}
    worker_invariant_statics = {
        "CropTarget",
        "IdleDetector",
        "Notification",
        "RestrictionTarget",
    }
    worker_invariant_objects = {"WebAssembly", "console"}
    worker_invariant_prototypes = {
        "DOMMatrix",
        "DOMMatrixReadOnly",
        "FileReaderSync",
        "FileSystemFileHandle",
        "FileSystemSyncAccessHandle",
        "HID",
        "MediaSource",
        "NetworkInformation",
        "Notification",
        "Performance",
        "Serial",
        "ServiceWorkerRegistration",
        "StorageBucket",
        "StorageManager",
        "USB",
        "WorkerLocation",
        "XMLHttpRequest",
    }
    generate_varying_tables(
        worker_documents,
        "constructorStatics",
        "WORKER_STATIC",
        "worker_constructor_static_names",
        worker_invariant_statics,
        arguments.android,
    )
    generate_varying_tables(
        worker_documents,
        "globalObjects",
        "WORKER_OBJECT",
        "worker_global_object_names",
        worker_invariant_objects,
        arguments.android,
    )
    generate_varying_tables(
        worker_documents,
        "constructorPrototypes",
        "WORKER_PROTO",
        "worker_prototype_names",
        worker_invariant_prototypes,
        arguments.android,
    )

    output_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(output_path)


if __name__ == "__main__":
    main()
